#!/bin/sh

export PGUSER="root"
export PGPASSWORD="inventUMIS"

pg_dump -h 192.168.3.240 -Fc ueab > /data/backups/days/ueab.backup

cp /data/backups/days/ueab.backup /home/tony/ueab.backup -f
chown tony /home/tony/ueab.backup

cp /data/backups/days/ueab.backup /home/samson/ueab.backup -f
chown samson /home/samson/ueab.backup

NOW=$(date +"%Y.%m.%d")
FILE="/data/backups/days/ueab.$NOW.backup"
pg_dump -h 192.168.3.240 -Fc ueab > $FILE

