insert into countrys (countryid,countryname) values ('AF','Afghanistan');
insert into countrys (countryid,countryname) values ('AL','Albania');
insert into countrys (countryid,countryname) values ('DZ','Algeria');
insert into countrys (countryid,countryname) values ('AS','American Samoa');
insert into countrys (countryid,countryname) values ('AD','Andorra');
insert into countrys (countryid,countryname) values ('AO','Angola');
insert into countrys (countryid,countryname) values ('AI','Anguilla');
insert into countrys (countryid,countryname) values ('AQ','Antarctica');
insert into countrys (countryid,countryname) values ('AG','Antigua and Barbuda');
insert into countrys (countryid,countryname) values ('AR','Argentina');
insert into countrys (countryid,countryname) values ('AM','Armenia');
insert into countrys (countryid,countryname) values ('AW','Aruba');
insert into countrys (countryid,countryname) values ('AU','Australia');
insert into countrys (countryid,countryname) values ('AT','Austria');
insert into countrys (countryid,countryname) values ('AZ','Azerbaidjan');
insert into countrys (countryid,countryname) values ('BS','Bahamas');
insert into countrys (countryid,countryname) values ('BH','Bahrain');
insert into countrys (countryid,countryname) values ('BD','Banglades');
insert into countrys (countryid,countryname) values ('BB','Barbados');
insert into countrys (countryid,countryname) values ('BY','Belarus');
insert into countrys (countryid,countryname) values ('BE','Belgium');
insert into countrys (countryid,countryname) values ('BZ','Belize');
insert into countrys (countryid,countryname) values ('BJ','Benin');
insert into countrys (countryid,countryname) values ('BM','Bermuda');
insert into countrys (countryid,countryname) values ('BO','Bolivia');
insert into countrys (countryid,countryname) values ('BA','Bosnia-Herzegovina');
insert into countrys (countryid,countryname) values ('BW','Botswana');
insert into countrys (countryid,countryname) values ('BV','Bouvet Island');
insert into countrys (countryid,countryname) values ('BR','Brazil');
insert into countrys (countryid,countryname) values ('IO','British Indian O. Terr.');
insert into countrys (countryid,countryname) values ('BN','Brunei Darussalam');
insert into countrys (countryid,countryname) values ('BG','Bulgaria');
insert into countrys (countryid,countryname) values ('BF','Burkina Faso');
insert into countrys (countryid,countryname) values ('BI','Burundi');
insert into countrys (countryid,countryname) values ('BT','Buthan');
insert into countrys (countryid,countryname) values ('KH','Cambodia');
insert into countrys (countryid,countryname) values ('CM','Cameroon');
insert into countrys (countryid,countryname) values ('CA','Canada');
insert into countrys (countryid,countryname) values ('CV','Cape Verde');
insert into countrys (countryid,countryname) values ('KY','Cayman Islands');
insert into countrys (countryid,countryname) values ('CF','Central African Rep.');
insert into countrys (countryid,countryname) values ('TD','Chad');
insert into countrys (countryid,countryname) values ('CL','Chile');
insert into countrys (countryid,countryname) values ('CN','China');
insert into countrys (countryid,countryname) values ('CX','Christmas Island');
insert into countrys (countryid,countryname) values ('CC','Cocos (Keeling) Isl.');
insert into countrys (countryid,countryname) values ('CO','Colombia');
insert into countrys (countryid,countryname) values ('KM','Comoros');
insert into countrys (countryid,countryname) values ('CG','Congo');
insert into countrys (countryid,countryname) values ('CK','Cook Islands');
insert into countrys (countryid,countryname) values ('CR','Costa Rica');
insert into countrys (countryid,countryname) values ('HR','Croatia');
insert into countrys (countryid,countryname) values ('CU','Cuba');
insert into countrys (countryid,countryname) values ('CY','Cyprus');
insert into countrys (countryid,countryname) values ('CZ','Czech Republic');
insert into countrys (countryid,countryname) values ('CS','Czechoslovakia');
insert into countrys (countryid,countryname) values ('DK','Denmark');
insert into countrys (countryid,countryname) values ('DJ','Djibouti');
insert into countrys (countryid,countryname) values ('DM','Dominica');
insert into countrys (countryid,countryname) values ('DO','Dominican Republic');
insert into countrys (countryid,countryname) values ('TP','East Timor');
insert into countrys (countryid,countryname) values ('EC','Ecuador');
insert into countrys (countryid,countryname) values ('EG','Egypt');
insert into countrys (countryid,countryname) values ('SV','El Salvador');
insert into countrys (countryid,countryname) values ('GQ','Equatorial Guinea');
insert into countrys (countryid,countryname) values ('EE','Estonia');
insert into countrys (countryid,countryname) values ('ET','Ethiopia');
insert into countrys (countryid,countryname) values ('ER','Eritrea Republic');
insert into countrys (countryid,countryname) values ('FK','Falkland Isl.(UK)');
insert into countrys (countryid,countryname) values ('FO','Faroe Islands');
insert into countrys (countryid,countryname) values ('FJ','Fiji');
insert into countrys (countryid,countryname) values ('FI','Finland');
insert into countrys (countryid,countryname) values ('FR','France');
insert into countrys (countryid,countryname) values ('FX','France (European Ter.)');
insert into countrys (countryid,countryname) values ('TF','French Southern Terr.');
insert into countrys (countryid,countryname) values ('GA','Gabon');
insert into countrys (countryid,countryname) values ('GM','Gambia');
insert into countrys (countryid,countryname) values ('GE','Georgia');
insert into countrys (countryid,countryname) values ('DE','Germany');
insert into countrys (countryid,countryname) values ('GH','Ghana');
insert into countrys (countryid,countryname) values ('GI','Gibraltar');
insert into countrys (countryid,countryname) values ('GB','Great Britain (UK)');
insert into countrys (countryid,countryname) values ('GR','Greece');
insert into countrys (countryid,countryname) values ('GL','Greenland');
insert into countrys (countryid,countryname) values ('GD','Grenada');
insert into countrys (countryid,countryname) values ('GP','Guadeloupe (Fr.)');
insert into countrys (countryid,countryname) values ('GU','Guam (US)');
insert into countrys (countryid,countryname) values ('GT','Guatemala');
insert into countrys (countryid,countryname) values ('GN','Guinea');
insert into countrys (countryid,countryname) values ('GW','Guinea Bissau');
insert into countrys (countryid,countryname) values ('GY','Guyana');
insert into countrys (countryid,countryname) values ('GF','Guyana (Fr.)');
insert into countrys (countryid,countryname) values ('HT','Haiti');
insert into countrys (countryid,countryname) values ('HM','Heard & McDonald Isl.');
insert into countrys (countryid,countryname) values ('HN','Honduras');
insert into countrys (countryid,countryname) values ('HK','Hong Kong');
insert into countrys (countryid,countryname) values ('HU','Hungary');
insert into countrys (countryid,countryname) values ('IS','Iceland');
insert into countrys (countryid,countryname) values ('IN','India');
insert into countrys (countryid,countryname) values ('ID','Indonesia');
insert into countrys (countryid,countryname) values ('IR','Iran');
insert into countrys (countryid,countryname) values ('IQ','Iraq');
insert into countrys (countryid,countryname) values ('IE','Ireland');
insert into countrys (countryid,countryname) values ('IL','Israel');
insert into countrys (countryid,countryname) values ('IT','Italy');
insert into countrys (countryid,countryname) values ('CI','Ivory Coast');
insert into countrys (countryid,countryname) values ('JM','Jamaica');
insert into countrys (countryid,countryname) values ('JP','Japan');
insert into countrys (countryid,countryname) values ('JO','Jordan');
insert into countrys (countryid,countryname) values ('KZ','Kazachstan');
insert into countrys (countryid,countryname) values ('KE','Kenya');
insert into countrys (countryid,countryname) values ('KG','Kirgistan');
insert into countrys (countryid,countryname) values ('KI','Kiribati');
insert into countrys (countryid,countryname) values ('KP','Korea (North)');
insert into countrys (countryid,countryname) values ('KR','Korea (South)');
insert into countrys (countryid,countryname) values ('KW','Kuwait');
insert into countrys (countryid,countryname) values ('LA','Laos');
insert into countrys (countryid,countryname) values ('LV','Latvia');
insert into countrys (countryid,countryname) values ('LB','Lebanon');
insert into countrys (countryid,countryname) values ('LS','Lesotho');
insert into countrys (countryid,countryname) values ('LR','Liberia');
insert into countrys (countryid,countryname) values ('LY','Libya');
insert into countrys (countryid,countryname) values ('LI','Liechtenstein');
insert into countrys (countryid,countryname) values ('LT','Lithuania');
insert into countrys (countryid,countryname) values ('LU','Luxembourg');
insert into countrys (countryid,countryname) values ('MO','Macau');
insert into countrys (countryid,countryname) values ('MG','Madagascar');
insert into countrys (countryid,countryname) values ('MW','Malawi');
insert into countrys (countryid,countryname) values ('MY','Malaysia');
insert into countrys (countryid,countryname) values ('MV','Maldives');
insert into countrys (countryid,countryname) values ('ML','Mali');
insert into countrys (countryid,countryname) values ('MT','Malta');
insert into countrys (countryid,countryname) values ('MH','Marshall Islands');
insert into countrys (countryid,countryname) values ('MQ','Martinique (Fr.)');
insert into countrys (countryid,countryname) values ('MR','Mauritania');
insert into countrys (countryid,countryname) values ('MU','Mauritius');
insert into countrys (countryid,countryname) values ('MX','Mexico');
insert into countrys (countryid,countryname) values ('FM','Micronesia');
insert into countrys (countryid,countryname) values ('MD','Moldavia');
insert into countrys (countryid,countryname) values ('MC','Monaco');
insert into countrys (countryid,countryname) values ('MN','Mongolia');
insert into countrys (countryid,countryname) values ('MS','Montserrat');
insert into countrys (countryid,countryname) values ('MA','Morocco');
insert into countrys (countryid,countryname) values ('MZ','Mozambique');
insert into countrys (countryid,countryname) values ('MM','Myanmar');
insert into countrys (countryid,countryname) values ('NA','Namibia');
insert into countrys (countryid,countryname) values ('NR','Nauru');
insert into countrys (countryid,countryname) values ('NP','Nepal');
insert into countrys (countryid,countryname) values ('AN','Netherland Antilles');
insert into countrys (countryid,countryname) values ('NL','Netherlands');
insert into countrys (countryid,countryname) values ('NT','Neutral Zone');
insert into countrys (countryid,countryname) values ('NC','New Caledonia (Fr.)');
insert into countrys (countryid,countryname) values ('NZ','New Zealand');
insert into countrys (countryid,countryname) values ('NI','Nicaragua');
insert into countrys (countryid,countryname) values ('NE','Niger');
insert into countrys (countryid,countryname) values ('NG','Nigeria');
insert into countrys (countryid,countryname) values ('NU','Niue');
insert into countrys (countryid,countryname) values ('NF','Norfolk Island');
insert into countrys (countryid,countryname) values ('MP','Northern Mariana Isl.');
insert into countrys (countryid,countryname) values ('NO','Norway');
insert into countrys (countryid,countryname) values ('OM','Oman');
insert into countrys (countryid,countryname) values ('PK','Pakistan');
insert into countrys (countryid,countryname) values ('PW','Palau');
insert into countrys (countryid,countryname) values ('PA','Panama');
insert into countrys (countryid,countryname) values ('PG','Papua New');
insert into countrys (countryid,countryname) values ('PY','Paraguay');
insert into countrys (countryid,countryname) values ('PE','Peru');
insert into countrys (countryid,countryname) values ('PH','Philippines');
insert into countrys (countryid,countryname) values ('PN','Pitcairn');
insert into countrys (countryid,countryname) values ('PL','Poland');
insert into countrys (countryid,countryname) values ('PF','Polynesia (Fr.)');
insert into countrys (countryid,countryname) values ('PT','Portugal');
insert into countrys (countryid,countryname) values ('PR','Puerto Rico (US)');
insert into countrys (countryid,countryname) values ('QA','Qatar');
insert into countrys (countryid,countryname) values ('RE','Reunion (Fr.)');
insert into countrys (countryid,countryname) values ('RO','Romania');
insert into countrys (countryid,countryname) values ('RU','Russian Federation');
insert into countrys (countryid,countryname) values ('RW','Rwanda');
insert into countrys (countryid,countryname) values ('LC','Saint Lucia');
insert into countrys (countryid,countryname) values ('WS','Samoa');
insert into countrys (countryid,countryname) values ('SM','San Marino');
insert into countrys (countryid,countryname) values ('SA','Saudi Arabia');
insert into countrys (countryid,countryname) values ('SN','Senegal');
insert into countrys (countryid,countryname) values ('SC','Seychelles');
insert into countrys (countryid,countryname) values ('SL','Sierra Leone');
insert into countrys (countryid,countryname) values ('SG','Singapore');
insert into countrys (countryid,countryname) values ('SK','Slovak Republic');
insert into countrys (countryid,countryname) values ('SI','Slovenia');
insert into countrys (countryid,countryname) values ('SB','Solomon Islands');
insert into countrys (countryid,countryname) values ('SO','Somalia');
insert into countrys (countryid,countryname) values ('ZA','South Africa');
insert into countrys (countryid,countryname) values ('SU','Soviet Union');
insert into countrys (countryid,countryname) values ('ES','Spain');
insert into countrys (countryid,countryname) values ('LK','Sri Lanka');
insert into countrys (countryid,countryname) values ('SH','St. Helena');
insert into countrys (countryid,countryname) values ('PM','St. Pierre & Miquelon');
insert into countrys (countryid,countryname) values ('ST','St. Tome and Principe');
insert into countrys (countryid,countryname) values ('KN','St.Kitts Nevis Anguilla');
insert into countrys (countryid,countryname) values ('VC','St.Vincent & Grenadines');
insert into countrys (countryid,countryname) values ('SD','Sudan');
insert into countrys (countryid,countryname) values ('SR','Suriname');
insert into countrys (countryid,countryname) values ('SJ','Svalbard & Jan Mayen Is');
insert into countrys (countryid,countryname) values ('SZ','Swaziland');
insert into countrys (countryid,countryname) values ('SE','Sweden');
insert into countrys (countryid,countryname) values ('CH','Switzerland');
insert into countrys (countryid,countryname) values ('SY','Syria');
insert into countrys (countryid,countryname) values ('TJ','Tadjikistan');
insert into countrys (countryid,countryname) values ('TW','Taiwan');
insert into countrys (countryid,countryname) values ('TZ','Tanzania');
insert into countrys (countryid,countryname) values ('TH','Thailand');
insert into countrys (countryid,countryname) values ('TG','Togo');
insert into countrys (countryid,countryname) values ('TK','Tokelau');
insert into countrys (countryid,countryname) values ('TO','Tonga');
insert into countrys (countryid,countryname) values ('TT','Trinidad & Tobago');
insert into countrys (countryid,countryname) values ('TN','Tunisia');
insert into countrys (countryid,countryname) values ('TR','Turkey');
insert into countrys (countryid,countryname) values ('TM','Turkmenistan');
insert into countrys (countryid,countryname) values ('TC','Turks & Caicos Islands');
insert into countrys (countryid,countryname) values ('TV','Tuvalu');
insert into countrys (countryid,countryname) values ('UG','Uganda');
insert into countrys (countryid,countryname) values ('UA','Ukraine');
insert into countrys (countryid,countryname) values ('AE','United Arab Emirates');
insert into countrys (countryid,countryname) values ('UK','United Kingdom');
insert into countrys (countryid,countryname) values ('US','United States');
insert into countrys (countryid,countryname) values ('UY','Uruguay');
insert into countrys (countryid,countryname) values ('UM','US Minor outlying Isl.');
insert into countrys (countryid,countryname) values ('UZ','Uzbekistan');
insert into countrys (countryid,countryname) values ('VU','Vanuatu');
insert into countrys (countryid,countryname) values ('VA','Vatican City State');
insert into countrys (countryid,countryname) values ('VE','Venezuela');
insert into countrys (countryid,countryname) values ('VN','Vietnam');
insert into countrys (countryid,countryname) values ('VG','Virgin Islands (British)');
insert into countrys (countryid,countryname) values ('VI','Virgin Islands (US)');
insert into countrys (countryid,countryname) values ('WF','Wallis & Futuna Islands');
insert into countrys (countryid,countryname) values ('EH','Western Sahara');
insert into countrys (countryid,countryname) values ('YE','Yemen');
insert into countrys (countryid,countryname) values ('YU','Yugoslavia');
insert into countrys (countryid,countryname) values ('ZR','Zaire');
insert into countrys (countryid,countryname) values ('ZM','Zambia');
insert into countrys (countryid,countryname) values ('ZW','Zimbabwe');
