DROP TABLE new_students;
CREATE TABLE new_students (
	MATRIC_NO			varchar(50),
	SURNAME				varchar(50),
	FIRST_NAME			varchar(50),
	MIDDLE_NAME			varchar(50),
	MODULE				varchar(50),
	BURSARY_ACCT_NO		varchar(50),
	majorid				varchar(50),
	DEGREE_IN_VIEW		varchar(50)
);


INSERT INTO new_students (MATRIC_NO, SURNAME, FIRST_NAME, MIDDLE_NAME, MODULE, BURSARY_ACCT_NO, majorid, DEGREE_IN_VIEW) VALUES ('PG/14/0164', 'OLUMBA', 'CHUKWUDI', 'CHARLES', 'REGULAR', 'SOLUCH0012', 'PDAG', 'PhD');
INSERT INTO new_students (MATRIC_NO, SURNAME, FIRST_NAME, MIDDLE_NAME, MODULE, BURSARY_ACCT_NO, majorid, DEGREE_IN_VIEW) VALUES ('PG/14/0165', 'FOLORUNSHO', 'OLADELE', 'IDRIS', 'REGULAR', 'SFOLOL0028', 'PDAG', 'PhD');
INSERT INTO new_students (MATRIC_NO, SURNAME, FIRST_NAME, MIDDLE_NAME, MODULE, BURSARY_ACCT_NO, majorid, DEGREE_IN_VIEW) VALUES ('PG/14/0166', 'ABIOLA', 'FOLAKEMI', 'RONKE', 'REGULAR', 'SABIFO0006', 'PMAE', 'M.Sc');
INSERT INTO new_students (MATRIC_NO, SURNAME, FIRST_NAME, MIDDLE_NAME, MODULE, BURSARY_ACCT_NO, majorid, DEGREE_IN_VIEW) VALUES ('PG/14/0167', 'AKINBOYE', 'OLUFUNSHO', 'EMMANUEL', 'REGULAR', 'SAKIOL0216', 'PDAG', 'PhD');
INSERT INTO new_students (MATRIC_NO, SURNAME, FIRST_NAME, MIDDLE_NAME, MODULE, BURSARY_ACCT_NO, majorid, DEGREE_IN_VIEW) VALUES ('PG/14/0168', 'JOHN-JAJA', 'SYLVIA', 'ALWELL', 'REGULAR', 'SJOHSY0001', 'PMAS', 'M.Sc');
INSERT INTO new_students (MATRIC_NO, SURNAME, FIRST_NAME, MIDDLE_NAME, MODULE, BURSARY_ACCT_NO, majorid, DEGREE_IN_VIEW) VALUES ('PG/14/0151', 'EMMANUEL', 'TOSIN', 'JOEL', 'REGULAR', 'SEMMTO0001', 'PGAC', 'M.Sc');
INSERT INTO new_students (MATRIC_NO, SURNAME, FIRST_NAME, MIDDLE_NAME, MODULE, BURSARY_ACCT_NO, majorid, DEGREE_IN_VIEW) VALUES ('PG/14/0152', 'OWOLABI', 'BABTUNDE', 'AYODEJI', 'REGULAR', 'SOWOBA0007', 'PGAC', 'M.Sc');
INSERT INTO new_students (MATRIC_NO, SURNAME, FIRST_NAME, MIDDLE_NAME, MODULE, BURSARY_ACCT_NO, majorid, DEGREE_IN_VIEW) VALUES ('PG/14/0153', 'IDRIS', 'BENUH', 'ADAMA', 'REGULAR', 'SIDRBE0001', 'PGAC', 'M.Sc');
INSERT INTO new_students (MATRIC_NO, SURNAME, FIRST_NAME, MIDDLE_NAME, MODULE, BURSARY_ACCT_NO, majorid, DEGREE_IN_VIEW) VALUES ('PG/14/0154', 'IREDELE', 'OLUMAYOWA', 'OLALEKAN', 'REGULAR', 'SIREOL0002', 'PDAC', 'PhD');
INSERT INTO new_students (MATRIC_NO, SURNAME, FIRST_NAME, MIDDLE_NAME, MODULE, BURSARY_ACCT_NO, majorid, DEGREE_IN_VIEW) VALUES ('PG/14/0155', 'OYEKOLA', 'OLUREMI', 'FRANCIS', 'REGULAR', 'SOYEOL0132', 'PDAC', 'PhD');
INSERT INTO new_students (MATRIC_NO, SURNAME, FIRST_NAME, MIDDLE_NAME, MODULE, BURSARY_ACCT_NO, majorid, DEGREE_IN_VIEW) VALUES ('PG/14/0156', 'ADEKOLA', 'ADEOLA', 'ADEBAYO', 'REGULAR', 'SADEAD0683', 'PDAC', 'PhD');
INSERT INTO new_students (MATRIC_NO, SURNAME, FIRST_NAME, MIDDLE_NAME, MODULE, BURSARY_ACCT_NO, majorid, DEGREE_IN_VIEW) VALUES ('PG/14/0157', 'ADELUSI', 'ABOSEDE', 'IFEOLUWA', 'REGULAR', 'SADEAB0103', 'PGAC', 'M.Sc');
INSERT INTO new_students (MATRIC_NO, SURNAME, FIRST_NAME, MIDDLE_NAME, MODULE, BURSARY_ACCT_NO, majorid, DEGREE_IN_VIEW) VALUES ('PG/14/0158', 'AJIBADE', 'TEMILOLUWA', 'IYANUOLUWA', 'REGULAR', 'SAJITE0004', 'PGAC', 'M.Sc');
INSERT INTO new_students (MATRIC_NO, SURNAME, FIRST_NAME, MIDDLE_NAME, MODULE, BURSARY_ACCT_NO, majorid, DEGREE_IN_VIEW) VALUES ('PG/14/0159', 'OGUNDANA', 'OYEBISI', 'MARY', 'REGULAR', 'SOGUOY0017', 'PDAC', 'PhD');
INSERT INTO new_students (MATRIC_NO, SURNAME, FIRST_NAME, MIDDLE_NAME, MODULE, BURSARY_ACCT_NO, majorid, DEGREE_IN_VIEW) VALUES ('PG/14/0160', 'OLAYINKA', 'OLUWATOBILOBA ', 'GRACE', 'REGULAR', 'SOLAOL0338', 'PGAC', 'M.Sc');
INSERT INTO new_students (MATRIC_NO, SURNAME, FIRST_NAME, MIDDLE_NAME, MODULE, BURSARY_ACCT_NO, majorid, DEGREE_IN_VIEW) VALUES ('PG/14/0161', 'DAHUNSI', 'ADEOLA', 'CHRISTIANA', 'REGULAR', 'SDAHAD0001', 'PGAC', 'M.Sc');
INSERT INTO new_students (MATRIC_NO, SURNAME, FIRST_NAME, MIDDLE_NAME, MODULE, BURSARY_ACCT_NO, majorid, DEGREE_IN_VIEW) VALUES ('PG/14/0162', 'USIFOH', 'OLUWAFUNMILAYO', 'OMORILEWA', 'REGULAR', 'SUSIOL0001', 'PGAC', 'M.Sc');
INSERT INTO new_students (MATRIC_NO, SURNAME, FIRST_NAME, MIDDLE_NAME, MODULE, BURSARY_ACCT_NO, majorid, DEGREE_IN_VIEW) VALUES ('PG/14/0163', 'ADERETI', 'ADEBOLA ', 'OLUWATOYIN', 'REGULAR', 'SADEAD0684', 'PGAC', 'M.Sc');
INSERT INTO new_students (MATRIC_NO, SURNAME, FIRST_NAME, MIDDLE_NAME, MODULE, BURSARY_ACCT_NO, majorid, DEGREE_IN_VIEW) VALUES ('PG/14/0175', 'AKINBODE', 'OLUFEMI', 'OLUWADAMILOLA', 'REGULAR', 'SAKIOL0217', 'PGBA', 'M.Sc');
INSERT INTO new_students (MATRIC_NO, SURNAME, FIRST_NAME, MIDDLE_NAME, MODULE, BURSARY_ACCT_NO, majorid, DEGREE_IN_VIEW) VALUES ('PG/14/0176', 'UMUKORO', 'OLAOLUWA', 'ELISE', 'REGULAR', 'SUMUOL0001', 'PGBA', 'M.Sc');
INSERT INTO new_students (MATRIC_NO, SURNAME, FIRST_NAME, MIDDLE_NAME, MODULE, BURSARY_ACCT_NO, majorid, DEGREE_IN_VIEW) VALUES ('PG/14/0177', 'COLE ', 'ABIMBOLA', '', 'REGULAR', 'SCOLAB0002', 'PDBA', 'PhD');
INSERT INTO new_students (MATRIC_NO, SURNAME, FIRST_NAME, MIDDLE_NAME, MODULE, BURSARY_ACCT_NO, majorid, DEGREE_IN_VIEW) VALUES ('PG/14/0178', 'AKARANTA ', 'PRINCE', 'CHIMEZIRIM', 'REGULAR', 'SAKAPR0001', 'PGBA', 'M.Sc');
INSERT INTO new_students (MATRIC_NO, SURNAME, FIRST_NAME, MIDDLE_NAME, MODULE, BURSARY_ACCT_NO, majorid, DEGREE_IN_VIEW) VALUES ('PG/14/0179', 'ABIONA', 'OREOLUWA', 'ADESEYE ', 'REGULAR', 'SABIOR0002', 'PGBA', 'M.Sc');
INSERT INTO new_students (MATRIC_NO, SURNAME, FIRST_NAME, MIDDLE_NAME, MODULE, BURSARY_ACCT_NO, majorid, DEGREE_IN_VIEW) VALUES ('PG/14/0180', 'APANISILE', 'EXODUS', 'KEHINDE', 'REGULAR', 'SAPAEX0001', 'PDBA', 'PhD');
INSERT INTO new_students (MATRIC_NO, SURNAME, FIRST_NAME, MIDDLE_NAME, MODULE, BURSARY_ACCT_NO, majorid, DEGREE_IN_VIEW) VALUES ('PG/14/0182', 'ETTI', 'KEHINDE ', 'AFOLAKE', 'REGULAR', 'SETTKE0001', 'PDBA', 'PhD');
INSERT INTO new_students (MATRIC_NO, SURNAME, FIRST_NAME, MIDDLE_NAME, MODULE, BURSARY_ACCT_NO, majorid, DEGREE_IN_VIEW) VALUES ('PG/14/0183', 'AYOOLA-AKINBIYI', 'OLAYEMI', 'OMOWUNMI', 'REGULAR', 'SAYOOL0045', 'PDBA', 'PhD');
INSERT INTO new_students (MATRIC_NO, SURNAME, FIRST_NAME, MIDDLE_NAME, MODULE, BURSARY_ACCT_NO, majorid, DEGREE_IN_VIEW) VALUES ('PG/14/0184', 'AGBEDE ', 'AYOTUNDE', 'ELYCE-MAUREEN', 'REGULAR', 'SAGBAY0008', 'PGBA', 'M.Sc');
INSERT INTO new_students (MATRIC_NO, SURNAME, FIRST_NAME, MIDDLE_NAME, MODULE, BURSARY_ACCT_NO, majorid, DEGREE_IN_VIEW) VALUES ('PG/14/0185', 'BOT ', 'JAMES', 'BADUNG', 'REGULAR', 'SBOTJA0001', 'PGBA', 'MBA');
INSERT INTO new_students (MATRIC_NO, SURNAME, FIRST_NAME, MIDDLE_NAME, MODULE, BURSARY_ACCT_NO, majorid, DEGREE_IN_VIEW) VALUES ('PG/14/0186', 'AJIJOLA ', 'DOLAPO ', 'MUYIDEEN', 'REGULAR', 'SAJIDO0002', 'PGBA', 'M.Sc');
INSERT INTO new_students (MATRIC_NO, SURNAME, FIRST_NAME, MIDDLE_NAME, MODULE, BURSARY_ACCT_NO, majorid, DEGREE_IN_VIEW) VALUES ('PG/12/0452', 'CHUIGBU', 'ISHMAEL', 'OKECHUKWU', 'REGULAR', 'SCHUIS0004', 'PDBA', 'PhD');
INSERT INTO new_students (MATRIC_NO, SURNAME, FIRST_NAME, MIDDLE_NAME, MODULE, BURSARY_ACCT_NO, majorid, DEGREE_IN_VIEW) VALUES ('07/0840', 'ADEGOKE ', 'ADETUTU', 'ARINOLA', 'REGULAR', 'SADEAD0685', 'PGBA', 'M.Sc');
INSERT INTO new_students (MATRIC_NO, SURNAME, FIRST_NAME, MIDDLE_NAME, MODULE, BURSARY_ACCT_NO, majorid, DEGREE_IN_VIEW) VALUES ('PG/14/0189', 'OYENEYIN ', 'KEHINDE ', '', 'REGULAR', 'SOYEKE0005', 'PGBA', 'M.Sc');
INSERT INTO new_students (MATRIC_NO, SURNAME, FIRST_NAME, MIDDLE_NAME, MODULE, BURSARY_ACCT_NO, majorid, DEGREE_IN_VIEW) VALUES ('PG/14/0190', 'AKINABO', 'BABTUNDE', 'HAMED', 'REGULAR', 'SAKIBA0012', 'PDBA', 'PhD');
INSERT INTO new_students (MATRIC_NO, SURNAME, FIRST_NAME, MIDDLE_NAME, MODULE, BURSARY_ACCT_NO, majorid, DEGREE_IN_VIEW) VALUES ('PG/14/0191', 'OYETI', 'OLUWAFEMI', 'OLUSEGUN', 'REGULAR', 'SOYEOL0133', 'PGBA', 'PGD');
INSERT INTO new_students (MATRIC_NO, SURNAME, FIRST_NAME, MIDDLE_NAME, MODULE, BURSARY_ACCT_NO, majorid, DEGREE_IN_VIEW) VALUES ('PG/14/0192', 'ADETUNJI', 'ADETOLA', 'ADEDUNMOLA', 'REGULAR', 'SADEAD0686', 'PDBA', 'PhD');
INSERT INTO new_students (MATRIC_NO, SURNAME, FIRST_NAME, MIDDLE_NAME, MODULE, BURSARY_ACCT_NO, majorid, DEGREE_IN_VIEW) VALUES ('PG/14/0193', 'BUARI', 'AYOOLA', 'LATEEF', 'REGULAR', 'SBUAAY0001', 'PDBA', 'PhD');
INSERT INTO new_students (MATRIC_NO, SURNAME, FIRST_NAME, MIDDLE_NAME, MODULE, BURSARY_ACCT_NO, majorid, DEGREE_IN_VIEW) VALUES ('PG/14/0194', 'OSIKOMAIYA', 'TAYOOLUWA', 'IFEDAYO', 'REGULAR', 'SOSITA0002', 'PGBA', 'PGD');
INSERT INTO new_students (MATRIC_NO, SURNAME, FIRST_NAME, MIDDLE_NAME, MODULE, BURSARY_ACCT_NO, majorid, DEGREE_IN_VIEW) VALUES ('PG/14/0195', 'SAMUEL', 'ADEDIMEJI', 'MOBOLAJI', 'REGULAR', 'SSAMAD0005', 'PGBA', 'MBA');
INSERT INTO new_students (MATRIC_NO, SURNAME, FIRST_NAME, MIDDLE_NAME, MODULE, BURSARY_ACCT_NO, majorid, DEGREE_IN_VIEW) VALUES ('PG/14/0196', 'OYETADE', 'OLANREWAJU', 'OLUGBENGA', 'REGULAR', 'SOYEOL0134', 'PDBA', 'PhD');
INSERT INTO new_students (MATRIC_NO, SURNAME, FIRST_NAME, MIDDLE_NAME, MODULE, BURSARY_ACCT_NO, majorid, DEGREE_IN_VIEW) VALUES ('PG/14/0197', 'OREMODU', 'SOLOMON', 'AKINSANYA', 'REGULAR', 'SORESO0001', 'PDBA', 'PhD');
INSERT INTO new_students (MATRIC_NO, SURNAME, FIRST_NAME, MIDDLE_NAME, MODULE, BURSARY_ACCT_NO, majorid, DEGREE_IN_VIEW) VALUES ('PG/14/0198', 'FATOBA', 'DAMILOLA', 'TEMITOPE', 'REGULAR', 'SFATDA0003', 'PGBA', 'MBA');
INSERT INTO new_students (MATRIC_NO, SURNAME, FIRST_NAME, MIDDLE_NAME, MODULE, BURSARY_ACCT_NO, majorid, DEGREE_IN_VIEW) VALUES ('PG/14/0199', 'EVWIERHURHOMA', 'FELIX', 'OSHEO', 'REGULAR', 'SEVWFE0001', 'PGBA', 'MBA');
INSERT INTO new_students (MATRIC_NO, SURNAME, FIRST_NAME, MIDDLE_NAME, MODULE, BURSARY_ACCT_NO, majorid, DEGREE_IN_VIEW) VALUES ('PG/14/0200', 'ANINKAN', 'DAVID', 'OLUSEGUN', 'REGULAR', 'SANIDA0003', 'PDBA', 'PhD');
INSERT INTO new_students (MATRIC_NO, SURNAME, FIRST_NAME, MIDDLE_NAME, MODULE, BURSARY_ACCT_NO, majorid, DEGREE_IN_VIEW) VALUES ('PG/14/0201', 'KAYODE', 'AYOMIDE', 'DEBORAH', 'REGULAR', 'SKAYAY0001', 'PGBA', 'M.Sc');
INSERT INTO new_students (MATRIC_NO, SURNAME, FIRST_NAME, MIDDLE_NAME, MODULE, BURSARY_ACCT_NO, majorid, DEGREE_IN_VIEW) VALUES ('PG/14/0202', 'EREJUWA', 'TAIWO', 'SANDRA', 'REGULAR', 'SERETA0001', 'PGBA', 'MBA');
INSERT INTO new_students (MATRIC_NO, SURNAME, FIRST_NAME, MIDDLE_NAME, MODULE, BURSARY_ACCT_NO, majorid, DEGREE_IN_VIEW) VALUES ('PG/14/0203', 'ALASE', 'ROTIMI', 'SAMUSIDEEN', 'REGULAR', 'SALARO0002', 'PGBA', 'M.Sc');
INSERT INTO new_students (MATRIC_NO, SURNAME, FIRST_NAME, MIDDLE_NAME, MODULE, BURSARY_ACCT_NO, majorid, DEGREE_IN_VIEW) VALUES ('PG/14/0204', 'APELOGUN', 'KEHINDE ', 'HUSSEIN', 'REGULAR', 'SAPEKE0001', 'PDBA', 'PhD');
INSERT INTO new_students (MATRIC_NO, SURNAME, FIRST_NAME, MIDDLE_NAME, MODULE, BURSARY_ACCT_NO, majorid, DEGREE_IN_VIEW) VALUES ('PG/14/0218', 'YADI ', 'ADAEZE', 'DORIS', 'REGULAR', 'SYADAD0001', 'PGFI', 'M.Sc');
INSERT INTO new_students (MATRIC_NO, SURNAME, FIRST_NAME, MIDDLE_NAME, MODULE, BURSARY_ACCT_NO, majorid, DEGREE_IN_VIEW) VALUES ('PG/14/0219', 'OLALEYE', 'ADENIKE', 'OLUWAFUNMILAYO', 'REGULAR', 'SOLAAD0068', 'PGFI', 'M.Sc');
INSERT INTO new_students (MATRIC_NO, SURNAME, FIRST_NAME, MIDDLE_NAME, MODULE, BURSARY_ACCT_NO, majorid, DEGREE_IN_VIEW) VALUES ('07/0532', 'EZENWAJI', 'UCHECHUKWU', 'GIFT', 'REGULAR', 'SEZEUC0007', 'PGFI', 'M.Sc');
INSERT INTO new_students (MATRIC_NO, SURNAME, FIRST_NAME, MIDDLE_NAME, MODULE, BURSARY_ACCT_NO, majorid, DEGREE_IN_VIEW) VALUES ('09/1808', 'OMOTAYO', 'SOUNGBOGBO', 'RUTH', 'REGULAR', 'SOMOSO0006', 'PGFI', 'M.Sc');
INSERT INTO new_students (MATRIC_NO, SURNAME, FIRST_NAME, MIDDLE_NAME, MODULE, BURSARY_ACCT_NO, majorid, DEGREE_IN_VIEW) VALUES ('PG/14/0222', 'OWOPETU ', 'CHRISTIANA', 'ADETOUN', 'REGULAR', 'SOWOCH0001', 'PDIR', 'PhD');
INSERT INTO new_students (MATRIC_NO, SURNAME, FIRST_NAME, MIDDLE_NAME, MODULE, BURSARY_ACCT_NO, majorid, DEGREE_IN_VIEW) VALUES ('PG/14/0223', 'FIJABI', 'NUBONTIN', 'MARIE-LOUISE', 'REGULAR', 'SFIJNU0001', 'PDIR', 'PhD');
INSERT INTO new_students (MATRIC_NO, SURNAME, FIRST_NAME, MIDDLE_NAME, MODULE, BURSARY_ACCT_NO, majorid, DEGREE_IN_VIEW) VALUES ('06/0020', 'UKANGWA', 'CHINEMEREM', 'CLEMENT', 'REGULAR', 'SUKACH0012', 'PDIR', 'PhD');
INSERT INTO new_students (MATRIC_NO, SURNAME, FIRST_NAME, MIDDLE_NAME, MODULE, BURSARY_ACCT_NO, majorid, DEGREE_IN_VIEW) VALUES ('PG/14/0225', 'OSUNKOYA', 'MOJISOLA ', 'YETUNDE ', 'REGULAR', 'SOSUMO0001', 'PDIR', 'PhD');
INSERT INTO new_students (MATRIC_NO, SURNAME, FIRST_NAME, MIDDLE_NAME, MODULE, BURSARY_ACCT_NO, majorid, DEGREE_IN_VIEW) VALUES ('PG/14/0226', 'ADEREMI', 'EDIRIN', 'ANNE', 'REGULAR', 'SADEED0001', 'PGIR', 'MIRM');
INSERT INTO new_students (MATRIC_NO, SURNAME, FIRST_NAME, MIDDLE_NAME, MODULE, BURSARY_ACCT_NO, majorid, DEGREE_IN_VIEW) VALUES ('PG/14/0227', 'AKPOVIRE ', 'EUNICE', 'VOKE', 'REGULAR', 'SAKPEU0002', 'PGIR', 'MIRM');
INSERT INTO new_students (MATRIC_NO, SURNAME, FIRST_NAME, MIDDLE_NAME, MODULE, BURSARY_ACCT_NO, majorid, DEGREE_IN_VIEW) VALUES ('PG/10/0170', 'AFAGHA ', 'IKISIKPO ', 'BENEDICT', 'REGULAR', 'SAFAIK0001', 'PDIR', 'PhD');
INSERT INTO new_students (MATRIC_NO, SURNAME, FIRST_NAME, MIDDLE_NAME, MODULE, BURSARY_ACCT_NO, majorid, DEGREE_IN_VIEW) VALUES ('PG/14/0229', 'OWOLABI', 'ADENIKE', 'AARINOLA', 'REGULAR', 'SOWOAD0010', 'PGIR', 'MIRM');
INSERT INTO new_students (MATRIC_NO, SURNAME, FIRST_NAME, MIDDLE_NAME, MODULE, BURSARY_ACCT_NO, majorid, DEGREE_IN_VIEW) VALUES ('PG/14/0230', 'AWOTILOKUN', 'BEATRICE', 'CHUNUDUNG', 'REGULAR', 'SAWOBE0001', 'PGIR', 'MIRM');
INSERT INTO new_students (MATRIC_NO, SURNAME, FIRST_NAME, MIDDLE_NAME, MODULE, BURSARY_ACCT_NO, majorid, DEGREE_IN_VIEW) VALUES ('PG/14/0231', 'OLAGOKE', 'DOLAPO ', 'PETER', 'REGULAR', 'SOLADO0013', 'PGIR', 'MIRM');
INSERT INTO new_students (MATRIC_NO, SURNAME, FIRST_NAME, MIDDLE_NAME, MODULE, BURSARY_ACCT_NO, majorid, DEGREE_IN_VIEW) VALUES ('PG/14/0232', 'BAMGBELU', 'SAMUEL', 'ADELEKE', 'REGULAR', 'SBAMSA0003', 'PGIR', 'MIRM');
INSERT INTO new_students (MATRIC_NO, SURNAME, FIRST_NAME, MIDDLE_NAME, MODULE, BURSARY_ACCT_NO, majorid, DEGREE_IN_VIEW) VALUES ('09/0021', 'OKUNADE ', 'ISAAC', 'OLUKAYODE', 'REGULAR', 'SOKUIS0003', 'PGIR', 'MIRM');
INSERT INTO new_students (MATRIC_NO, SURNAME, FIRST_NAME, MIDDLE_NAME, MODULE, BURSARY_ACCT_NO, majorid, DEGREE_IN_VIEW) VALUES ('08/1172', 'ADERANTI', 'PAUL', 'ADEWOLE', 'REGULAR', 'SADEPA0010', 'PGIR', 'MIRM');
INSERT INTO new_students (MATRIC_NO, SURNAME, FIRST_NAME, MIDDLE_NAME, MODULE, BURSARY_ACCT_NO, majorid, DEGREE_IN_VIEW) VALUES ('07/1465', 'ALONGE ', 'OLUSOLA', 'MICHAEL', 'REGULAR', 'SALOOL0011', 'PGIR', 'MIRM');
INSERT INTO new_students (MATRIC_NO, SURNAME, FIRST_NAME, MIDDLE_NAME, MODULE, BURSARY_ACCT_NO, majorid, DEGREE_IN_VIEW) VALUES ('PG/11/0037', 'SULE ', 'MOSES', 'BOYEDE', 'REGULAR', 'SSULMO0005', 'PDIR', 'PhD');
INSERT INTO new_students (MATRIC_NO, SURNAME, FIRST_NAME, MIDDLE_NAME, MODULE, BURSARY_ACCT_NO, majorid, DEGREE_IN_VIEW) VALUES ('PG/14/0237', 'OMOLE', 'SEGUN', 'MICHAEL', 'REGULAR', 'SOMOSE0003', 'PDIR', 'PhD');
INSERT INTO new_students (MATRIC_NO, SURNAME, FIRST_NAME, MIDDLE_NAME, MODULE, BURSARY_ACCT_NO, majorid, DEGREE_IN_VIEW) VALUES ('PG/14/0238', 'OLAWOYIN', 'OLAJUMOKE ', 'REBECCA', 'REGULAR', 'SOLAOL0339', 'PDIR', 'PhD');
INSERT INTO new_students (MATRIC_NO, SURNAME, FIRST_NAME, MIDDLE_NAME, MODULE, BURSARY_ACCT_NO, majorid, DEGREE_IN_VIEW) VALUES ('PG/14/0239', 'ONOYEYAN', 'GLORY ', 'OGBEBULE', 'REGULAR', 'SONOGL0002', 'PDIR', 'PhD');
INSERT INTO new_students (MATRIC_NO, SURNAME, FIRST_NAME, MIDDLE_NAME, MODULE, BURSARY_ACCT_NO, majorid, DEGREE_IN_VIEW) VALUES ('PG/14/0240', 'AGBESE-UNAZI', 'FLORENCE', 'ADA ', 'REGULAR', 'SAGBFL0002', 'PDIR', 'PhD');
INSERT INTO new_students (MATRIC_NO, SURNAME, FIRST_NAME, MIDDLE_NAME, MODULE, BURSARY_ACCT_NO, majorid, DEGREE_IN_VIEW) VALUES ('PG/14/0242', 'FONUM', 'BLESSING', 'CHIKA', 'REGULAR', 'SFONBL0001', 'PDIR', 'PhD');
INSERT INTO new_students (MATRIC_NO, SURNAME, FIRST_NAME, MIDDLE_NAME, MODULE, BURSARY_ACCT_NO, majorid, DEGREE_IN_VIEW) VALUES ('PG/14/0205', 'OKOLIE', 'AZUKA ', 'EMMANUEL', 'REGULAR', 'SOKOAZ0002', 'PGMA', 'M.Sc');
INSERT INTO new_students (MATRIC_NO, SURNAME, FIRST_NAME, MIDDLE_NAME, MODULE, BURSARY_ACCT_NO, majorid, DEGREE_IN_VIEW) VALUES ('PG/14/0241', 'OSOKO', 'ABISOLA', 'OLUTOLA', 'REGULAR', 'SOSOAB0003', 'PGMA', 'M.Sc');
INSERT INTO new_students (MATRIC_NO, SURNAME, FIRST_NAME, MIDDLE_NAME, MODULE, BURSARY_ACCT_NO, majorid, DEGREE_IN_VIEW) VALUES ('PG/14/0243', 'EYITAYO', 'MUFUTAU', 'SIKIRU', 'REGULAR', 'SEYIMU0001', 'PGMA', 'M.Sc');
INSERT INTO new_students (MATRIC_NO, SURNAME, FIRST_NAME, MIDDLE_NAME, MODULE, BURSARY_ACCT_NO, majorid, DEGREE_IN_VIEW) VALUES ('06/0984', 'ALAO ', 'OLUWAFISAYO', 'OLUBUKOLA', 'REGULAR', 'SALAOL0061', 'PDMC', 'PhD');
INSERT INTO new_students (MATRIC_NO, SURNAME, FIRST_NAME, MIDDLE_NAME, MODULE, BURSARY_ACCT_NO, majorid, DEGREE_IN_VIEW) VALUES ('PG/14/0245', 'MAIGADI', 'KYAUTA', 'BARJE', 'REGULAR', 'SMAIKY0001', 'PMMC', 'M.Sc');
INSERT INTO new_students (MATRIC_NO, SURNAME, FIRST_NAME, MIDDLE_NAME, MODULE, BURSARY_ACCT_NO, majorid, DEGREE_IN_VIEW) VALUES ('PG/14/0246', 'AKANDE', 'BOLANLE', 'OLUWABUNMI', 'REGULAR', 'SAKABO0006', 'PMMC', 'M.Sc');
INSERT INTO new_students (MATRIC_NO, SURNAME, FIRST_NAME, MIDDLE_NAME, MODULE, BURSARY_ACCT_NO, majorid, DEGREE_IN_VIEW) VALUES ('PG/13/0174', 'TUROTI', 'OLUWAFUNMILAYO', 'ELIZABETH', 'REGULAR', 'STUROL0002', 'PMMC', 'M.Sc');
INSERT INTO new_students (MATRIC_NO, SURNAME, FIRST_NAME, MIDDLE_NAME, MODULE, BURSARY_ACCT_NO, majorid, DEGREE_IN_VIEW) VALUES ('PG/14/0248', 'FANIYI ', 'BELINDA', 'AMEZE', 'REGULAR', 'SFANBE0001', 'PDMC', 'PhD');
INSERT INTO new_students (MATRIC_NO, SURNAME, FIRST_NAME, MIDDLE_NAME, MODULE, BURSARY_ACCT_NO, majorid, DEGREE_IN_VIEW) VALUES ('PG/14/0249', 'AGBEDE ', 'AYOBAMI', 'MARIUS', 'REGULAR', 'SAGBAY0009', 'PDMC', 'PGD');
INSERT INTO new_students (MATRIC_NO, SURNAME, FIRST_NAME, MIDDLE_NAME, MODULE, BURSARY_ACCT_NO, majorid, DEGREE_IN_VIEW) VALUES ('08/1489', 'DAVIS', 'TOLUWANIMI ', 'LOIS', 'REGULAR', 'SDAVTO0003', 'PMMC', 'M.Sc');
INSERT INTO new_students (MATRIC_NO, SURNAME, FIRST_NAME, MIDDLE_NAME, MODULE, BURSARY_ACCT_NO, majorid, DEGREE_IN_VIEW) VALUES ('08/1669', 'ANABA', 'NANCY ', 'NNENNA', 'REGULAR', 'SANANA0001', 'PMMC', 'M.Sc');
INSERT INTO new_students (MATRIC_NO, SURNAME, FIRST_NAME, MIDDLE_NAME, MODULE, BURSARY_ACCT_NO, majorid, DEGREE_IN_VIEW) VALUES ('PG/14/0252', 'OTUN', 'OLALEKAN', 'SALMON', 'REGULAR', 'SOTUOL0011', 'PDMC', 'PhD');
INSERT INTO new_students (MATRIC_NO, SURNAME, FIRST_NAME, MIDDLE_NAME, MODULE, BURSARY_ACCT_NO, majorid, DEGREE_IN_VIEW) VALUES ('PG/14/0253', 'EGBERONGBE', 'GBOLAHAN', 'QUDUS', 'REGULAR', 'SEGBGB0001', 'PDMC', 'PGD');
INSERT INTO new_students (MATRIC_NO, SURNAME, FIRST_NAME, MIDDLE_NAME, MODULE, BURSARY_ACCT_NO, majorid, DEGREE_IN_VIEW) VALUES ('PG/14/0254', 'ALAMU', 'ADEDAMOLA', 'OLUWATOBI', 'REGULAR', 'SALAAD0030', 'PMMC', 'M.Sc');
INSERT INTO new_students (MATRIC_NO, SURNAME, FIRST_NAME, MIDDLE_NAME, MODULE, BURSARY_ACCT_NO, majorid, DEGREE_IN_VIEW) VALUES ('04/0089', 'ATAKITI', 'IFEOLUWA', 'OLABISI', 'REGULAR', 'SATAIF0002', 'PDMC', 'PhD');
INSERT INTO new_students (MATRIC_NO, SURNAME, FIRST_NAME, MIDDLE_NAME, MODULE, BURSARY_ACCT_NO, majorid, DEGREE_IN_VIEW) VALUES ('PG/14/0256', 'EDAFEJIRHAYE', 'VINCENT', 'IDIADA', 'REGULAR', 'SEDAVI0001', 'PDMC', 'Mphil');
INSERT INTO new_students (MATRIC_NO, SURNAME, FIRST_NAME, MIDDLE_NAME, MODULE, BURSARY_ACCT_NO, majorid, DEGREE_IN_VIEW) VALUES ('PG/14/0257', 'IHEJIRIKA', 'SANDRA', 'CHISOM', 'REGULAR', 'SIHESA0001', 'PMMC', 'M.Sc');
INSERT INTO new_students (MATRIC_NO, SURNAME, FIRST_NAME, MIDDLE_NAME, MODULE, BURSARY_ACCT_NO, majorid, DEGREE_IN_VIEW) VALUES ('PG/14/0181', 'IJOMA-ABARA', 'MARVELLOUS', 'CHINYERE', 'REGULAR', 'SIJOMA0001', 'PGPS', 'M.Sc');
INSERT INTO new_students (MATRIC_NO, SURNAME, FIRST_NAME, MIDDLE_NAME, MODULE, BURSARY_ACCT_NO, majorid, DEGREE_IN_VIEW) VALUES ('PG/14/0268', 'AGORO ', 'FATAI', 'AYOWOLE', 'REGULAR', 'SAGOFA0001', 'PDPS', 'PhD');
INSERT INTO new_students (MATRIC_NO, SURNAME, FIRST_NAME, MIDDLE_NAME, MODULE, BURSARY_ACCT_NO, majorid, DEGREE_IN_VIEW) VALUES ('PG/14/0269', 'ADENUGA', 'GBEKE', 'ADEBOWALE', 'REGULAR', 'SADEGB0017', 'PDPS', 'PhD');
INSERT INTO new_students (MATRIC_NO, SURNAME, FIRST_NAME, MIDDLE_NAME, MODULE, BURSARY_ACCT_NO, majorid, DEGREE_IN_VIEW) VALUES ('PG/14/0270', 'NWAWOLO', 'HOPE', 'AKUNNA', 'REGULAR', 'SNWAHO0005', 'PDPS', 'PhD');
INSERT INTO new_students (MATRIC_NO, SURNAME, FIRST_NAME, MIDDLE_NAME, MODULE, BURSARY_ACCT_NO, majorid, DEGREE_IN_VIEW) VALUES ('PG/14/0271', 'ADEDAYO', 'ABOLADE', 'ENIOLA', 'REGULAR', 'SADEAB0104', 'PGPS', 'MPM');
INSERT INTO new_students (MATRIC_NO, SURNAME, FIRST_NAME, MIDDLE_NAME, MODULE, BURSARY_ACCT_NO, majorid, DEGREE_IN_VIEW) VALUES ('PG/14/0272', 'NWOKO', 'CHIDI', '', 'REGULAR', 'SNWOCH0037', 'PGPS', 'MPM');
INSERT INTO new_students (MATRIC_NO, SURNAME, FIRST_NAME, MIDDLE_NAME, MODULE, BURSARY_ACCT_NO, majorid, DEGREE_IN_VIEW) VALUES ('PG/14/0273', 'AGBOR', 'OLUBUNMI', '', 'REGULAR', 'SAGBOL0049', 'PDPS', 'PhD');
INSERT INTO new_students (MATRIC_NO, SURNAME, FIRST_NAME, MIDDLE_NAME, MODULE, BURSARY_ACCT_NO, majorid, DEGREE_IN_VIEW) VALUES ('PG/14/0274', 'ALABI', 'BOLAJI', '', 'REGULAR', 'SALABO0003', 'PDPS', 'PhD');
INSERT INTO new_students (MATRIC_NO, SURNAME, FIRST_NAME, MIDDLE_NAME, MODULE, BURSARY_ACCT_NO, majorid, DEGREE_IN_VIEW) VALUES ('PG/14/0275', 'ADEYEMI', 'ADEWUMI', 'AYOMIDE', 'REGULAR', 'SADEAD0687', 'PGPS', 'M.Sc');
INSERT INTO new_students (MATRIC_NO, SURNAME, FIRST_NAME, MIDDLE_NAME, MODULE, BURSARY_ACCT_NO, majorid, DEGREE_IN_VIEW) VALUES ('PG/14/0276', 'ABORISADE', 'DANIEL', '', 'REGULAR', 'SABODA0003', 'PDPS', 'PhD');
INSERT INTO new_students (MATRIC_NO, SURNAME, FIRST_NAME, MIDDLE_NAME, MODULE, BURSARY_ACCT_NO, majorid, DEGREE_IN_VIEW) VALUES ('PG/12/0471', 'OLOJEDE', 'IBUKUNOLUWA', 'ABOSEDE', 'REGULAR', 'SOLOIB0008', 'PDPS', 'PhD');
INSERT INTO new_students (MATRIC_NO, SURNAME, FIRST_NAME, MIDDLE_NAME, MODULE, BURSARY_ACCT_NO, majorid, DEGREE_IN_VIEW) VALUES ('PG/14/0278', 'OKEDELE', 'ADEBUSOLA', '', 'REGULAR', 'SOKEAD0013', 'PDPS', 'PhD');
INSERT INTO new_students (MATRIC_NO, SURNAME, FIRST_NAME, MIDDLE_NAME, MODULE, BURSARY_ACCT_NO, majorid, DEGREE_IN_VIEW) VALUES ('08/1055', 'OYETORAN', 'ADERONKE', '', 'REGULAR', 'SOYEAD0041', 'PGPS', 'M.Sc');
INSERT INTO new_students (MATRIC_NO, SURNAME, FIRST_NAME, MIDDLE_NAME, MODULE, BURSARY_ACCT_NO, majorid, DEGREE_IN_VIEW) VALUES ('PG/14/0280', 'BABTUNDE', 'ADEOLA', 'MUTIU', 'REGULAR', 'SBABAD0028', 'PGPS', 'M.Sc');
INSERT INTO new_students (MATRIC_NO, SURNAME, FIRST_NAME, MIDDLE_NAME, MODULE, BURSARY_ACCT_NO, majorid, DEGREE_IN_VIEW) VALUES ('08/0975', 'AKINBAMIJO', 'IBUKUNOLUWA', '', 'REGULAR', 'SAKIIB0006', 'PGPS', 'M.Sc');
INSERT INTO new_students (MATRIC_NO, SURNAME, FIRST_NAME, MIDDLE_NAME, MODULE, BURSARY_ACCT_NO, majorid, DEGREE_IN_VIEW) VALUES ('PG/14/0282', 'KOLEDADE', 'ABIODUN', '', 'REGULAR', 'SKOLAB0003', 'PGPS', '');
INSERT INTO new_students (MATRIC_NO, SURNAME, FIRST_NAME, MIDDLE_NAME, MODULE, BURSARY_ACCT_NO, majorid, DEGREE_IN_VIEW) VALUES ('PG/14/0283', 'IRECHUKWU ', 'GODWIN', 'NDUBUISI', 'REGULAR', 'SIREGO0001', 'PGPS', 'Mphil');
INSERT INTO new_students (MATRIC_NO, SURNAME, FIRST_NAME, MIDDLE_NAME, MODULE, BURSARY_ACCT_NO, majorid, DEGREE_IN_VIEW) VALUES ('PG/14/0284', 'AKINOLU', 'REMI ', 'CHRISTY', 'REGULAR', 'SAKIRE0006', 'PGPS', 'MPM');
INSERT INTO new_students (MATRIC_NO, SURNAME, FIRST_NAME, MIDDLE_NAME, MODULE, BURSARY_ACCT_NO, majorid, DEGREE_IN_VIEW) VALUES ('PG/14/0285', 'OKETOKUN', 'FATAI', 'OLALEKAN', 'REGULAR', 'SOKEFA0003', 'PDPS', 'PhD');
INSERT INTO new_students (MATRIC_NO, SURNAME, FIRST_NAME, MIDDLE_NAME, MODULE, BURSARY_ACCT_NO, majorid, DEGREE_IN_VIEW) VALUES ('PG/14/0258', 'UKPONG', 'EKAETTE', 'OPEYEMI', 'REGULAR', 'SUKPEK0001', 'PGMI', 'M.sc');
INSERT INTO new_students (MATRIC_NO, SURNAME, FIRST_NAME, MIDDLE_NAME, MODULE, BURSARY_ACCT_NO, majorid, DEGREE_IN_VIEW) VALUES ('PG/14/0259', 'FATADE', 'OLUWABUSOLA', 'OMOLOLA', 'REGULAR', 'SFATOL0019', 'PGMI', 'M.Sc');
INSERT INTO new_students (MATRIC_NO, SURNAME, FIRST_NAME, MIDDLE_NAME, MODULE, BURSARY_ACCT_NO, majorid, DEGREE_IN_VIEW) VALUES ('PG/14/0260', 'ODESANYA', 'OLUWAYEMISI', 'FOLUKE', 'REGULAR', 'SODEOL0046', 'PGMI', 'M.Sc');
INSERT INTO new_students (MATRIC_NO, SURNAME, FIRST_NAME, MIDDLE_NAME, MODULE, BURSARY_ACCT_NO, majorid, DEGREE_IN_VIEW) VALUES ('PG/14/0261', 'ETIAKA', 'HENRIETTA', 'OKWIE', 'REGULAR', 'SETIHE0001', 'PGMI', 'M.Sc');
INSERT INTO new_students (MATRIC_NO, SURNAME, FIRST_NAME, MIDDLE_NAME, MODULE, BURSARY_ACCT_NO, majorid, DEGREE_IN_VIEW) VALUES ('PG/14/0169', 'ADETONA', 'MIUTIAT', 'OLUTOPE', 'REGULAR', 'SADEMI0010', 'PDBI', 'PhD');
INSERT INTO new_students (MATRIC_NO, SURNAME, FIRST_NAME, MIDDLE_NAME, MODULE, BURSARY_ACCT_NO, majorid, DEGREE_IN_VIEW) VALUES ('PG/14/0170', 'HANNAFI', 'OLUFUNMILAYO', 'OLUTOLA', 'REGULAR', 'SHANOL0001', 'PDBI', 'Mphil');
INSERT INTO new_students (MATRIC_NO, SURNAME, FIRST_NAME, MIDDLE_NAME, MODULE, BURSARY_ACCT_NO, majorid, DEGREE_IN_VIEW) VALUES ('PG/14/0171', 'AJAGUNNA', 'ADESOLA', 'JULIANAH', 'REGULAR', 'SAJAAD0014', 'PDBI', 'M.Sc');
INSERT INTO new_students (MATRIC_NO, SURNAME, FIRST_NAME, MIDDLE_NAME, MODULE, BURSARY_ACCT_NO, majorid, DEGREE_IN_VIEW) VALUES ('PG/14/0172', 'OLUSUYI', 'MOHAMMED', 'ADEKUNLE', 'REGULAR', 'SOLUMO0023', 'PDBI', 'PhD');
INSERT INTO new_students (MATRIC_NO, SURNAME, FIRST_NAME, MIDDLE_NAME, MODULE, BURSARY_ACCT_NO, majorid, DEGREE_IN_VIEW) VALUES ('PG/14/0173', 'ALAGBE', 'MONICA', 'OYETORO', 'REGULAR', 'SALAMO0012', 'PDBI', 'PhD');
INSERT INTO new_students (MATRIC_NO, SURNAME, FIRST_NAME, MIDDLE_NAME, MODULE, BURSARY_ACCT_NO, majorid, DEGREE_IN_VIEW) VALUES ('PG/11/0266', 'BADEJO-ADEYEMI', 'MARIA ', 'MODUPE', 'REGULAR', 'SBADMA0007', 'PDBI', 'PhD');
INSERT INTO new_students (MATRIC_NO, SURNAME, FIRST_NAME, MIDDLE_NAME, MODULE, BURSARY_ACCT_NO, majorid, DEGREE_IN_VIEW) VALUES ('PG/12/0463', 'EBIESUWA', 'OLUWASEUN', 'OLUWOLE', 'REGULAR', 'SEBIOL0002', 'PDCS', 'PhD');
INSERT INTO new_students (MATRIC_NO, SURNAME, FIRST_NAME, MIDDLE_NAME, MODULE, BURSARY_ACCT_NO, majorid, DEGREE_IN_VIEW) VALUES ('PG/14/0207', 'BALOGUN', 'ABOSEDE', 'ANTHONIA', 'REGULAR', 'SBALAB0009', 'PMCS', 'M.Sc');
INSERT INTO new_students (MATRIC_NO, SURNAME, FIRST_NAME, MIDDLE_NAME, MODULE, BURSARY_ACCT_NO, majorid, DEGREE_IN_VIEW) VALUES ('08/0666', 'CHUKWU', 'EMMANUEL', 'ARUCHI', 'REGULAR', 'SCHUEM0006', 'PMCS', 'M.Sc');
INSERT INTO new_students (MATRIC_NO, SURNAME, FIRST_NAME, MIDDLE_NAME, MODULE, BURSARY_ACCT_NO, majorid, DEGREE_IN_VIEW) VALUES ('PG/11/0285', 'ONUIRI', 'ERNEST', 'ENYINNAYA', 'REGULAR', 'SONUER0002', 'PDCS', 'PhD');
INSERT INTO new_students (MATRIC_NO, SURNAME, FIRST_NAME, MIDDLE_NAME, MODULE, BURSARY_ACCT_NO, majorid, DEGREE_IN_VIEW) VALUES ('PG/14/0210', 'AKINLADE', 'BENEDICTA', 'ADEOLUWA', 'REGULAR', 'SAKIBE0001', 'PDCS', 'PGD');
INSERT INTO new_students (MATRIC_NO, SURNAME, FIRST_NAME, MIDDLE_NAME, MODULE, BURSARY_ACCT_NO, majorid, DEGREE_IN_VIEW) VALUES ('PG/12/0570', 'ADESEGUN', 'OREOLUWA', 'AYODEJI', 'REGULAR', 'SADEOR0018', 'PDCS', 'PhD');
INSERT INTO new_students (MATRIC_NO, SURNAME, FIRST_NAME, MIDDLE_NAME, MODULE, BURSARY_ACCT_NO, majorid, DEGREE_IN_VIEW) VALUES ('PG/14/0212', 'NGIGE', 'OGUCHUKWU', 'CONSTANCE', 'REGULAR', 'SNGIOG0001', 'PMCS', 'M.sc');
INSERT INTO new_students (MATRIC_NO, SURNAME, FIRST_NAME, MIDDLE_NAME, MODULE, BURSARY_ACCT_NO, majorid, DEGREE_IN_VIEW) VALUES ('PG/14/0213', 'CHIBUDIKE ', 'CHINEDUM', 'EUNICE', 'REGULAR', 'SCHICH0035', 'PMCS', 'M.sc');
INSERT INTO new_students (MATRIC_NO, SURNAME, FIRST_NAME, MIDDLE_NAME, MODULE, BURSARY_ACCT_NO, majorid, DEGREE_IN_VIEW) VALUES ('PG/14/0214', 'MAMINOR', 'GBUBEMI', 'UKEH', 'REGULAR', 'SMAMGB0001', 'PMCS', 'M.Sc');
INSERT INTO new_students (MATRIC_NO, SURNAME, FIRST_NAME, MIDDLE_NAME, MODULE, BURSARY_ACCT_NO, majorid, DEGREE_IN_VIEW) VALUES ('PG/14/0215', 'ADEGOKE ', 'OLASUPO ', 'MODUPE', 'REGULAR', 'SADEOL0619', 'PDCS', 'PGD');
INSERT INTO new_students (MATRIC_NO, SURNAME, FIRST_NAME, MIDDLE_NAME, MODULE, BURSARY_ACCT_NO, majorid, DEGREE_IN_VIEW) VALUES ('PG/14/0216', 'SOREMI', 'MOTUNRATO', 'AJIBOLA', 'REGULAR', 'SSORMO0002', 'PMCS', 'M.Sc');
INSERT INTO new_students (MATRIC_NO, SURNAME, FIRST_NAME, MIDDLE_NAME, MODULE, BURSARY_ACCT_NO, majorid, DEGREE_IN_VIEW) VALUES ('PG/14/0217', 'FATADE', 'EMMANUEL', 'OLUFEMI', 'REGULAR', 'SFATEM0002', 'PDCS', 'PGD');
INSERT INTO new_students (MATRIC_NO, SURNAME, FIRST_NAME, MIDDLE_NAME, MODULE, BURSARY_ACCT_NO, majorid, DEGREE_IN_VIEW) VALUES ('PG/14/0298', 'FALOLA', 'IDRIS', 'DARE', 'REGULAR', 'SFALID0001', 'PGHI', 'M.A.');
INSERT INTO new_students (MATRIC_NO, SURNAME, FIRST_NAME, MIDDLE_NAME, MODULE, BURSARY_ACCT_NO, majorid, DEGREE_IN_VIEW) VALUES ('PG/14/0299', 'SODIPE ', 'OLUFIKAYO', 'OLUSOLA', 'REGULAR', 'SSODOL0018', 'PGHI', 'M.A.');
INSERT INTO new_students (MATRIC_NO, SURNAME, FIRST_NAME, MIDDLE_NAME, MODULE, BURSARY_ACCT_NO, majorid, DEGREE_IN_VIEW) VALUES ('PG/14/0300', 'OBASI ', 'UBI', 'NKECHI', 'REGULAR', 'SOBAUB0001', 'PGHI', 'M.A.');
INSERT INTO new_students (MATRIC_NO, SURNAME, FIRST_NAME, MIDDLE_NAME, MODULE, BURSARY_ACCT_NO, majorid, DEGREE_IN_VIEW) VALUES ('PG/14/0262', 'MINAMOR ', 'SOLOMON', '', 'REGULAR', 'SMINSO0002', 'PDRP', 'PGD');
INSERT INTO new_students (MATRIC_NO, SURNAME, FIRST_NAME, MIDDLE_NAME, MODULE, BURSARY_ACCT_NO, majorid, DEGREE_IN_VIEW) VALUES ('PG/14/0263', 'UBOJI ', 'MILLER', 'MONDAY', 'REGULAR', 'SUBOMI0001', 'PDRP', 'PGD');
INSERT INTO new_students (MATRIC_NO, SURNAME, FIRST_NAME, MIDDLE_NAME, MODULE, BURSARY_ACCT_NO, majorid, DEGREE_IN_VIEW) VALUES ('PG/14/0264', 'AGOMUO', 'BASSEY', 'NDUBUISI', 'REGULAR', 'SAGOBA0001', 'PDRP', 'PGD');
INSERT INTO new_students (MATRIC_NO, SURNAME, FIRST_NAME, MIDDLE_NAME, MODULE, BURSARY_ACCT_NO, majorid, DEGREE_IN_VIEW) VALUES ('PG/14/0265', 'NATHANIEL', 'AHAMEFULA', 'CHIMAOBI', 'REGULAR', 'SNATAH0001', 'PDRP', 'PGD');
INSERT INTO new_students (MATRIC_NO, SURNAME, FIRST_NAME, MIDDLE_NAME, MODULE, BURSARY_ACCT_NO, majorid, DEGREE_IN_VIEW) VALUES ('PG/14/0266', 'UZOARU', 'GODSON ', 'CHETACHI', 'REGULAR', 'SUZOGO0003', 'PDRP', 'PGD');
INSERT INTO new_students (MATRIC_NO, SURNAME, FIRST_NAME, MIDDLE_NAME, MODULE, BURSARY_ACCT_NO, majorid, DEGREE_IN_VIEW) VALUES ('PG/14/0267', 'OLANIPEKUN', 'ADEBAYO', 'OLUFEMI', 'REGULAR', 'SOLAAD0069', 'PDRP', 'PGD');
INSERT INTO new_students (MATRIC_NO, SURNAME, FIRST_NAME, MIDDLE_NAME, MODULE, BURSARY_ACCT_NO, majorid, DEGREE_IN_VIEW) VALUES ('08/0852', 'OSIBERU', 'ADENIKE', 'ABISOLA', 'REGULAR', 'SOSIAD0019', 'PGPH', 'MPH');
INSERT INTO new_students (MATRIC_NO, SURNAME, FIRST_NAME, MIDDLE_NAME, MODULE, BURSARY_ACCT_NO, majorid, DEGREE_IN_VIEW) VALUES ('PG/14/0287', 'ENAWORU', 'OGHENETEJIRI', 'IBRUREH', 'REGULAR', 'SENAOG0002', 'PGPH', 'PhD');
INSERT INTO new_students (MATRIC_NO, SURNAME, FIRST_NAME, MIDDLE_NAME, MODULE, BURSARY_ACCT_NO, majorid, DEGREE_IN_VIEW) VALUES ('PG/14/0288', 'ELEMORO-YISA', 'MAKIAM', 'BOLATITO', 'REGULAR', 'SELEMA0002', 'PGPH', 'MPH');
INSERT INTO new_students (MATRIC_NO, SURNAME, FIRST_NAME, MIDDLE_NAME, MODULE, BURSARY_ACCT_NO, majorid, DEGREE_IN_VIEW) VALUES ('PG/14/0289', 'JOSEPH', 'OLUSOLA', 'OLUSEYI', 'REGULAR', 'SJOSOL0013', 'PGPH', 'MPH');
INSERT INTO new_students (MATRIC_NO, SURNAME, FIRST_NAME, MIDDLE_NAME, MODULE, BURSARY_ACCT_NO, majorid, DEGREE_IN_VIEW) VALUES ('PG/14/0290', 'AKINBODE', 'ABIOLA', 'OLUWATOYIN', 'REGULAR', 'SAKIAB0043', 'PGPH', 'MPH');
INSERT INTO new_students (MATRIC_NO, SURNAME, FIRST_NAME, MIDDLE_NAME, MODULE, BURSARY_ACCT_NO, majorid, DEGREE_IN_VIEW) VALUES ('PG/14/0291', 'AKHIGBEMIDU', 'WINIFRED', 'EHIAGHE', 'REGULAR', 'SAKHWI0001', 'PGPH', 'MPH');
INSERT INTO new_students (MATRIC_NO, SURNAME, FIRST_NAME, MIDDLE_NAME, MODULE, BURSARY_ACCT_NO, majorid, DEGREE_IN_VIEW) VALUES ('PG/14/0292', 'OLUGBOJA', 'OLAFIMIHAN', 'SAMUEL', 'REGULAR', 'SOLUOL0173', 'PGPH', 'MPH');
INSERT INTO new_students (MATRIC_NO, SURNAME, FIRST_NAME, MIDDLE_NAME, MODULE, BURSARY_ACCT_NO, majorid, DEGREE_IN_VIEW) VALUES ('07/1255', 'NWOGU', 'OLUCHI', 'CHIALUKAM', 'REGULAR', 'SNWOOL0004', 'PGPH', 'MPH');
INSERT INTO new_students (MATRIC_NO, SURNAME, FIRST_NAME, MIDDLE_NAME, MODULE, BURSARY_ACCT_NO, majorid, DEGREE_IN_VIEW) VALUES ('07/1246', 'ISOLA', 'OLUBUKOLA', 'OLUREMI', 'REGULAR', 'SISOOL0005', 'PGPH', 'MPH');
INSERT INTO new_students (MATRIC_NO, SURNAME, FIRST_NAME, MIDDLE_NAME, MODULE, BURSARY_ACCT_NO, majorid, DEGREE_IN_VIEW) VALUES ('PG/14/0295', 'EICHIE', 'ESTHER', 'ILOBEKEME', 'REGULAR', 'SEICES0002', 'PGPH', 'MPH');
INSERT INTO new_students (MATRIC_NO, SURNAME, FIRST_NAME, MIDDLE_NAME, MODULE, BURSARY_ACCT_NO, majorid, DEGREE_IN_VIEW) VALUES ('07/1211', 'ADUROJA', 'POSI', 'EMMANUEL', 'REGULAR', 'SADUPO0002', 'PGPH', 'MPH');
INSERT INTO new_students (MATRIC_NO, SURNAME, FIRST_NAME, MIDDLE_NAME, MODULE, BURSARY_ACCT_NO, majorid, DEGREE_IN_VIEW) VALUES ('PG/14/0297', 'BELLO ', 'AYOBANJO', 'DEBORAH', 'REGULAR', 'SBELAY0002', 'PGPH', 'MPH');

INSERT INTO students (denominationid, org_id, Sex, MaritalStatus, Nationality, countrycodeid, gcountrycodeid, stateid, 
	studentid, surname, firstname, othernames, 
	accountnumber, departmentid)

SELECT 'CHRI', 2, 'M', 'S', 'NG', 'NG', 'NG', 39, 
	upper(trim(new_students.MATRIC_NO)), new_students.SURNAME, new_students.FIRST_NAME, new_students.MIDDLE_NAME, 
	new_students.BURSARY_ACCT_NO, majors.departmentid

FROM new_students INNER JOIN majors ON trim(upper(new_students.majorid)) = trim(upper(majors.majorid))
LEFT JOIN students ON upper(trim(new_students.MATRIC_NO)) = students.studentid

WHERE students.studentid is null;


UPDATE new_students SET DEGREE_IN_VIEW = 'PHD' WHERE DEGREE_IN_VIEW = 'PhD';
UPDATE new_students SET DEGREE_IN_VIEW = 'PHD' WHERE DEGREE_IN_VIEW = 'MPM';
UPDATE new_students SET DEGREE_IN_VIEW = 'PHD' WHERE DEGREE_IN_VIEW = 'Mphil';
UPDATE new_students SET DEGREE_IN_VIEW = 'MAST' WHERE DEGREE_IN_VIEW = 'M.Sc';
UPDATE new_students SET DEGREE_IN_VIEW = 'MAST' WHERE DEGREE_IN_VIEW = 'M.A';
UPDATE new_students SET DEGREE_IN_VIEW = 'MAST' WHERE DEGREE_IN_VIEW = '';
UPDATE new_students SET DEGREE_IN_VIEW = 'MAST' WHERE DEGREE_IN_VIEW is null;
UPDATE new_students SET DEGREE_IN_VIEW = 'MAST' WHERE DEGREE_IN_VIEW = 'M.sc';
UPDATE new_students SET DEGREE_IN_VIEW = 'MAST' WHERE DEGREE_IN_VIEW = 'M.A.';
UPDATE new_students SET DEGREE_IN_VIEW = 'PGDI' WHERE DEGREE_IN_VIEW = 'PGD';


SELECT new_students.DEGREE_IN_VIEW
FROM new_students LEFT JOIN sublevels ON new_students.DEGREE_IN_VIEW = sublevels.sublevelid
WHERE sublevels.sublevelid is null
GROUP BY new_students.DEGREE_IN_VIEW;

INSERT INTO studentdegrees (degreeid, sublevelid, bulletingid, org_id, studentid)
SELECT 'MA', new_students.DEGREE_IN_VIEW, 3, 2, new_students.MATRIC_NO
FROM new_students LEFT JOIN studentdegrees ON (new_students.MATRIC_NO = studentdegrees.studentid) 
WHERE (studentdegrees.studentid is null);

INSERT INTO studentmajors (studentdegreeid, majorid, org_id)
SELECT studentdegrees.studentdegreeid, new_students.majorid, 2
FROM (new_students INNER JOIN studentdegrees ON studentdegrees.studentid = new_students.MATRIC_NO)
	LEFT JOIN  studentmajors ON studentdegrees.studentdegreeid = studentmajors.studentdegreeid
WHERE (studentmajors.studentdegreeid is null);







