DROP TABLE new_students2;
CREATE TABLE new_students2 (
	MATRIC_NO			varchar(50),
	SURNAME				varchar(50),
	FIRST_NAME			varchar(50),
	MIDDLE_NAME			varchar(50),
	MODULE				varchar(50),
	BURSARY_ACCT_NO		varchar(50),
	majorid				varchar(50),
	DEGREE_IN_VIEW		varchar(50)
);

INSERT INTO new_students2 (MATRIC_NO, SURNAME, FIRST_NAME, MIDDLE_NAME, MODULE, BURSARY_ACCT_NO, majorid, DEGREE_IN_VIEW) VALUES ('PG/14/0046', 'ISOLA', 'JOSEPH', 'OLUWASEGUN', 'ELONGATED', 'SISOJO0001', 'PGAC', 'M.Sc.');
INSERT INTO new_students2 (MATRIC_NO, SURNAME, FIRST_NAME, MIDDLE_NAME, MODULE, BURSARY_ACCT_NO, majorid, DEGREE_IN_VIEW) VALUES ('12/3807', 'UCHEAGWU', 'CHUKWUMA', 'JAMES', 'ELONGATED', 'SUCHCH0005', 'PGAC', 'M.Sc.');
INSERT INTO new_students2 (MATRIC_NO, SURNAME, FIRST_NAME, MIDDLE_NAME, MODULE, BURSARY_ACCT_NO, majorid, DEGREE_IN_VIEW) VALUES ('12/3815', 'OSIANOR', 'ELIJAH', 'AMANOGHENE', 'ELONGATED', 'SOSIEL0001', 'PGAC', 'M.Sc.');
INSERT INTO new_students2 (MATRIC_NO, SURNAME, FIRST_NAME, MIDDLE_NAME, MODULE, BURSARY_ACCT_NO, majorid, DEGREE_IN_VIEW) VALUES ('PG/14/0013', 'IWALA', 'ANDREW', 'TAIWO', 'ELONGATED', 'SIWAAN0001', 'PGAC', 'M.Sc.');
INSERT INTO new_students2 (MATRIC_NO, SURNAME, FIRST_NAME, MIDDLE_NAME, MODULE, BURSARY_ACCT_NO, majorid, DEGREE_IN_VIEW) VALUES ('11/4283', 'AUDU', 'MONDAY', 'ATADOGAH', 'ELONGATED', 'SAUDMO0001', 'PGAC', 'M.Sc.');
INSERT INTO new_students2 (MATRIC_NO, SURNAME, FIRST_NAME, MIDDLE_NAME, MODULE, BURSARY_ACCT_NO, majorid, DEGREE_IN_VIEW) VALUES ('PG/14/0100', 'AKINTOYE', 'OMOTAYO', 'OLURANTI', 'ELONGATED', 'SAKIOM0036', 'PGAC', 'M.Sc.');
INSERT INTO new_students2 (MATRIC_NO, SURNAME, FIRST_NAME, MIDDLE_NAME, MODULE, BURSARY_ACCT_NO, majorid, DEGREE_IN_VIEW) VALUES ('PG/14/0051', 'OGUNDALU ', 'DORCAS', 'OLAJUMOKE', 'ELONGATED', 'SOGUDA0034', 'PGAC', 'M.Sc.');
INSERT INTO new_students2 (MATRIC_NO, SURNAME, FIRST_NAME, MIDDLE_NAME, MODULE, BURSARY_ACCT_NO, majorid, DEGREE_IN_VIEW) VALUES ('PG/14/0053', 'ABU', 'OLUSOLA', 'SILVANUS', 'ELONGATED', 'SABUOL0003', 'PGAC', 'M.Sc.');
INSERT INTO new_students2 (MATRIC_NO, SURNAME, FIRST_NAME, MIDDLE_NAME, MODULE, BURSARY_ACCT_NO, majorid, DEGREE_IN_VIEW) VALUES ('PG/14/0054', 'ADESEMOWO ', 'MODUPEOLA', 'MORENIKE', 'ELONGATED', 'SADEMO0077', 'PGAC', 'M.Sc.');
INSERT INTO new_students2 (MATRIC_NO, SURNAME, FIRST_NAME, MIDDLE_NAME, MODULE, BURSARY_ACCT_NO, majorid, DEGREE_IN_VIEW) VALUES ('12/3819', 'UGWAEGBUNAM', 'BENNETH', '', 'ELONGATED', 'SUGWBE0003', 'PGAC', 'M.Sc.');
INSERT INTO new_students2 (MATRIC_NO, SURNAME, FIRST_NAME, MIDDLE_NAME, MODULE, BURSARY_ACCT_NO, majorid, DEGREE_IN_VIEW) VALUES ('12/3808', 'OWOLABI ', 'TOSIN', 'AINDE', 'ELONGATED', 'SOWOTO0010', 'PGAC', 'M.Sc.');
INSERT INTO new_students2 (MATRIC_NO, SURNAME, FIRST_NAME, MIDDLE_NAME, MODULE, BURSARY_ACCT_NO, majorid, DEGREE_IN_VIEW) VALUES ('PG/14/0016', 'AHANNAYA', 'CHINEDU', 'GANDOLPH', 'ELONGATED', 'SAHACH0005', 'PGAC', 'M.Sc.');
INSERT INTO new_students2 (MATRIC_NO, SURNAME, FIRST_NAME, MIDDLE_NAME, MODULE, BURSARY_ACCT_NO, majorid, DEGREE_IN_VIEW) VALUES ('12/3806', 'JIMOH', 'SIKIRU', '', 'ELONGATED', 'SJIMSI0001', 'PGAC', 'M.Sc.');
INSERT INTO new_students2 (MATRIC_NO, SURNAME, FIRST_NAME, MIDDLE_NAME, MODULE, BURSARY_ACCT_NO, majorid, DEGREE_IN_VIEW) VALUES ('PG/14/0026', 'OREKOYA', 'MOSUNMOLA', 'MORENIKE', 'ELONGATED', 'SOREMO0003', 'PGAC', 'M.Sc.');
INSERT INTO new_students2 (MATRIC_NO, SURNAME, FIRST_NAME, MIDDLE_NAME, MODULE, BURSARY_ACCT_NO, majorid, DEGREE_IN_VIEW) VALUES ('PG/14/0021', 'EKPENI', 'KEVIN', 'CHINWE', 'ELONGATED', 'SKEVEK0001', 'PGAC', 'M.Sc.');
INSERT INTO new_students2 (MATRIC_NO, SURNAME, FIRST_NAME, MIDDLE_NAME, MODULE, BURSARY_ACCT_NO, majorid, DEGREE_IN_VIEW) VALUES ('PG/14/0057', 'OYEBANJI', 'JULIUS', 'OLUDAYO', 'ELONGATED', 'SOYEJU0001', 'PGAC', 'M.Sc.');
INSERT INTO new_students2 (MATRIC_NO, SURNAME, FIRST_NAME, MIDDLE_NAME, MODULE, BURSARY_ACCT_NO, majorid, DEGREE_IN_VIEW) VALUES ('PG/14/0043', 'IDOWU', 'ISMAILA', 'AYODEJI', 'ELONGATED', 'SIDOIS0001', 'PGAC', 'M.Sc.');
INSERT INTO new_students2 (MATRIC_NO, SURNAME, FIRST_NAME, MIDDLE_NAME, MODULE, BURSARY_ACCT_NO, majorid, DEGREE_IN_VIEW) VALUES ('PG/14/0098', 'SANNI', 'ADEYEMI', 'SHERIFF', 'ELONGATED', 'SSANAD0016', 'PGAC', 'M.Sc.');
INSERT INTO new_students2 (MATRIC_NO, SURNAME, FIRST_NAME, MIDDLE_NAME, MODULE, BURSARY_ACCT_NO, majorid, DEGREE_IN_VIEW) VALUES ('PG/14/0097', 'OREYINGBO', 'ADEGBOLA', 'ADEBAYO', 'ELONGATED', 'SOREAD0012', 'PGAC', 'M.Sc.');
INSERT INTO new_students2 (MATRIC_NO, SURNAME, FIRST_NAME, MIDDLE_NAME, MODULE, BURSARY_ACCT_NO, majorid, DEGREE_IN_VIEW) VALUES ('PG/14/0099', 'ADELOWO', 'JOSHUA', 'ROTIMI', 'ELONGATED', 'SADEJO0027', 'PGAC', 'M.Sc.');
INSERT INTO new_students2 (MATRIC_NO, SURNAME, FIRST_NAME, MIDDLE_NAME, MODULE, BURSARY_ACCT_NO, majorid, DEGREE_IN_VIEW) VALUES ('PG/14/0032', 'ODEWOLE', 'OLABISI', 'BOLARINWA', 'ELONGATED', 'SODEOL0045', 'PDBA', 'Mphil');
INSERT INTO new_students2 (MATRIC_NO, SURNAME, FIRST_NAME, MIDDLE_NAME, MODULE, BURSARY_ACCT_NO, majorid, DEGREE_IN_VIEW) VALUES ('PG/14/0085', 'ASEMOTA', 'ANTHONY', 'OSAYANDE', 'ELONGATED', 'SASEAN0002', 'PMBA', 'MBA');
INSERT INTO new_students2 (MATRIC_NO, SURNAME, FIRST_NAME, MIDDLE_NAME, MODULE, BURSARY_ACCT_NO, majorid, DEGREE_IN_VIEW) VALUES ('PG/14/0088', 'ARIGUZO', 'VIVIAN', 'ADAOBI', 'ELONGATED', 'SARIVI0001', 'PMBA', 'MBA');
INSERT INTO new_students2 (MATRIC_NO, SURNAME, FIRST_NAME, MIDDLE_NAME, MODULE, BURSARY_ACCT_NO, majorid, DEGREE_IN_VIEW) VALUES ('PG/14/0023', 'KUFORIJI', 'ARAMIDE', 'ARINOLA', 'ELONGATED', 'SKUFAR0001', 'PDBA', 'PhD');
INSERT INTO new_students2 (MATRIC_NO, SURNAME, FIRST_NAME, MIDDLE_NAME, MODULE, BURSARY_ACCT_NO, majorid, DEGREE_IN_VIEW) VALUES ('PG/14/0101', 'OLISE', 'KENNETH', '', 'ELONGATED', 'SOLIKE0001', 'PDBA', 'PhD');
INSERT INTO new_students2 (MATRIC_NO, SURNAME, FIRST_NAME, MIDDLE_NAME, MODULE, BURSARY_ACCT_NO, majorid, DEGREE_IN_VIEW) VALUES ('PG/14/0102', 'IKECHI-EKPENDU', 'CHIOMA', 'VICTORIA', 'ELONGATED', 'SIKECH0020', 'PDBA', 'PhD');
INSERT INTO new_students2 (MATRIC_NO, SURNAME, FIRST_NAME, MIDDLE_NAME, MODULE, BURSARY_ACCT_NO, majorid, DEGREE_IN_VIEW) VALUES ('PG/14/0041', 'ADEOYE', 'SOLOMON', 'OLUSEGUN', 'ELONGATED', 'SADESO0011', 'PDBA', 'Mphil');
INSERT INTO new_students2 (MATRIC_NO, SURNAME, FIRST_NAME, MIDDLE_NAME, MODULE, BURSARY_ACCT_NO, majorid, DEGREE_IN_VIEW) VALUES ('PG/14/0028', 'AKOMOLAFE', 'RUFUS', 'ZACCHEAUS', 'ELONGATED', 'SAKORU0001', 'PDBA', 'PhD');
INSERT INTO new_students2 (MATRIC_NO, SURNAME, FIRST_NAME, MIDDLE_NAME, MODULE, BURSARY_ACCT_NO, majorid, DEGREE_IN_VIEW) VALUES ('03/0293', 'FALUYI', 'ANUOLUWAPO', 'ESTHER', 'ELONGATED', 'SFALAN0001', 'PMBA', 'M.Sc.');
INSERT INTO new_students2 (MATRIC_NO, SURNAME, FIRST_NAME, MIDDLE_NAME, MODULE, BURSARY_ACCT_NO, majorid, DEGREE_IN_VIEW) VALUES ('PG/14/0076', 'ONADEKO', 'BABATUNDE', 'BABASOLA', 'ELONGATED', 'SONABA0003', 'PDBA', 'PhD');
INSERT INTO new_students2 (MATRIC_NO, SURNAME, FIRST_NAME, MIDDLE_NAME, MODULE, BURSARY_ACCT_NO, majorid, DEGREE_IN_VIEW) VALUES ('PG/14/0077', 'ONAFOWORA', 'OLAJUMOKE', 'TEMITOPE', 'ELONGATED', 'SONAOL0063', 'PDBA', 'PGD');
INSERT INTO new_students2 (MATRIC_NO, SURNAME, FIRST_NAME, MIDDLE_NAME, MODULE, BURSARY_ACCT_NO, majorid, DEGREE_IN_VIEW) VALUES ('PG/14/0078', 'OLANIYAN', 'JIDE', 'BODURIN', 'ELONGATED', 'SOLAJI0001', 'PDBA', 'PhD');
INSERT INTO new_students2 (MATRIC_NO, SURNAME, FIRST_NAME, MIDDLE_NAME, MODULE, BURSARY_ACCT_NO, majorid, DEGREE_IN_VIEW) VALUES ('PG/14/0079', 'BAKARE', 'OLAYINKA', 'KAYODE', 'ELONGATED', 'SBAKOL0021', 'PMBA', 'MBA');
INSERT INTO new_students2 (MATRIC_NO, SURNAME, FIRST_NAME, MIDDLE_NAME, MODULE, BURSARY_ACCT_NO, majorid, DEGREE_IN_VIEW) VALUES ('PG/14/0080', 'ODUNSI', 'KEHINDE', 'OLA', 'ELONGATED', 'SODUKE0006', 'PDBA', 'PhD');
INSERT INTO new_students2 (MATRIC_NO, SURNAME, FIRST_NAME, MIDDLE_NAME, MODULE, BURSARY_ACCT_NO, majorid, DEGREE_IN_VIEW) VALUES ('PG/14/0081', 'AKOREDE', 'ADENIKE', 'MORONKEJI', 'ELONGATED', 'SAKOAD/0003', 'PDBA', 'Mphil');
INSERT INTO new_students2 (MATRIC_NO, SURNAME, FIRST_NAME, MIDDLE_NAME, MODULE, BURSARY_ACCT_NO, majorid, DEGREE_IN_VIEW) VALUES ('PG/14/0033', 'ODUTAYO', 'FUNMILLOLA', 'ABIOSEDE', 'ELONGATED', 'SODUFU0004', 'PDBA', 'PGD');
INSERT INTO new_students2 (MATRIC_NO, SURNAME, FIRST_NAME, MIDDLE_NAME, MODULE, BURSARY_ACCT_NO, majorid, DEGREE_IN_VIEW) VALUES ('PG/14/0082', 'FADEBI', 'ABEL', 'SUNDAY', 'ELONGATED', 'SFADAB0004', 'PDBA', 'Mphil');
INSERT INTO new_students2 (MATRIC_NO, SURNAME, FIRST_NAME, MIDDLE_NAME, MODULE, BURSARY_ACCT_NO, majorid, DEGREE_IN_VIEW) VALUES ('PG/14/0083', 'IBHIEDU', 'AMOS', 'OMONKHOMIOMHEN', 'ELONGATED', 'SIBHAM0001', 'PDBA', 'Mphil');
INSERT INTO new_students2 (MATRIC_NO, SURNAME, FIRST_NAME, MIDDLE_NAME, MODULE, BURSARY_ACCT_NO, majorid, DEGREE_IN_VIEW) VALUES ('PG/14/0001', 'ELUENI', 'BEAUTY', 'ANN', 'ELONGATED', 'SELUBE0001', 'PDBA', 'Mphil');
INSERT INTO new_students2 (MATRIC_NO, SURNAME, FIRST_NAME, MIDDLE_NAME, MODULE, BURSARY_ACCT_NO, majorid, DEGREE_IN_VIEW) VALUES ('PG/14/0030', 'OLUSESAN', 'OLATUNDE', 'OLUROPO', 'ELONGATED', 'SOLUOL0173', 'PDBA', 'PGD');
INSERT INTO new_students2 (MATRIC_NO, SURNAME, FIRST_NAME, MIDDLE_NAME, MODULE, BURSARY_ACCT_NO, majorid, DEGREE_IN_VIEW) VALUES ('PG/14/0086', 'OGUNTUASE ', 'DAVID', 'AYOBAMI', 'ELONGATED', 'SOGUDA0034', 'PDBA', 'Mphil');
INSERT INTO new_students2 (MATRIC_NO, SURNAME, FIRST_NAME, MIDDLE_NAME, MODULE, BURSARY_ACCT_NO, majorid, DEGREE_IN_VIEW) VALUES ('PG/14/0020', 'AIGBOJE', 'PATRICK', 'OYAREGBE', 'ELONGATED', 'SAIGPA0001', 'PDBA', 'Mphil');
INSERT INTO new_students2 (MATRIC_NO, SURNAME, FIRST_NAME, MIDDLE_NAME, MODULE, BURSARY_ACCT_NO, majorid, DEGREE_IN_VIEW) VALUES ('PG/14/0007', 'NWAULUNE', 'JUDE', 'CHEKWUME', 'ELONGATED', 'SNWAJU0001', 'PMBA', 'M.Sc.');
INSERT INTO new_students2 (MATRIC_NO, SURNAME, FIRST_NAME, MIDDLE_NAME, MODULE, BURSARY_ACCT_NO, majorid, DEGREE_IN_VIEW) VALUES ('PG/14/0087', 'IWERE ', 'FESTUS', 'ABAYE', 'ELONGATED', 'SIWEFE0001', 'PDBA', 'Mphil');
INSERT INTO new_students2 (MATRIC_NO, SURNAME, FIRST_NAME, MIDDLE_NAME, MODULE, BURSARY_ACCT_NO, majorid, DEGREE_IN_VIEW) VALUES ('02/0512', 'GBAGBA', 'ADEMOLA', 'SULAIMAN', 'ELONGATED', 'SGBAAD0004', 'PMBA', 'M.Sc.');
INSERT INTO new_students2 (MATRIC_NO, SURNAME, FIRST_NAME, MIDDLE_NAME, MODULE, BURSARY_ACCT_NO, majorid, DEGREE_IN_VIEW) VALUES ('PG/14/0006', 'ADIELE', 'MICHEAL', 'AKOBUNDU', 'ELONGATED', 'SADIMI0002', 'PDBA', 'PGD');
INSERT INTO new_students2 (MATRIC_NO, SURNAME, FIRST_NAME, MIDDLE_NAME, MODULE, BURSARY_ACCT_NO, majorid, DEGREE_IN_VIEW) VALUES ('07/0952', 'FASHOLA', 'KOFOWOROLA', 'WINIFRED', 'ELONGATED', 'SFASKO0001', 'PMBA', 'MBA');
INSERT INTO new_students2 (MATRIC_NO, SURNAME, FIRST_NAME, MIDDLE_NAME, MODULE, BURSARY_ACCT_NO, majorid, DEGREE_IN_VIEW) VALUES ('PG/14/0089', 'MAFIMISEBI', 'ADEDATIWA', 'BABATUNDE', 'ELONGATED', 'SMAFAD0002', 'PDBA', 'PhD');
INSERT INTO new_students2 (MATRIC_NO, SURNAME, FIRST_NAME, MIDDLE_NAME, MODULE, BURSARY_ACCT_NO, majorid, DEGREE_IN_VIEW) VALUES ('PG/14/0090', 'SHOLESI', 'OLAYINKA', 'YUSUF', 'ELONGATED', 'SSHOOL0038', 'PDBA', 'PhD');
INSERT INTO new_students2 (MATRIC_NO, SURNAME, FIRST_NAME, MIDDLE_NAME, MODULE, BURSARY_ACCT_NO, majorid, DEGREE_IN_VIEW) VALUES ('PG/14/0029', 'ADEYEMI', 'JOSHUA', 'AKINLOLU', 'ELONGATED', 'SADEJO0028', 'PMBA', 'MBA');
INSERT INTO new_students2 (MATRIC_NO, SURNAME, FIRST_NAME, MIDDLE_NAME, MODULE, BURSARY_ACCT_NO, majorid, DEGREE_IN_VIEW) VALUES ('PG/14/0031', 'ADENUGA', 'ADEBOYE', 'BABAFEMI', 'ELONGATED', 'SADEAD0667', 'PDBA', 'Mphil');
INSERT INTO new_students2 (MATRIC_NO, SURNAME, FIRST_NAME, MIDDLE_NAME, MODULE, BURSARY_ACCT_NO, majorid, DEGREE_IN_VIEW) VALUES ('PG/14/0091', 'CHIMEZIE', 'CHIKADIBIA', 'OLUWASEGUN', 'ELONGATED', 'SCHICH0035', 'PMBA', 'M.Sc.');
INSERT INTO new_students2 (MATRIC_NO, SURNAME, FIRST_NAME, MIDDLE_NAME, MODULE, BURSARY_ACCT_NO, majorid, DEGREE_IN_VIEW) VALUES ('PG/14/0092', 'ABOLARIN', 'OMOTOLA', 'ADEDAMOLA', 'ELONGATED', 'SABOOM0003', 'PMBA', 'M.Sc.');
INSERT INTO new_students2 (MATRIC_NO, SURNAME, FIRST_NAME, MIDDLE_NAME, MODULE, BURSARY_ACCT_NO, majorid, DEGREE_IN_VIEW) VALUES ('PG/14/0093', 'BABALOLA', 'ODUNOLA', 'OLUBUKOLA', 'ELONGATED', 'SBABOD0002', 'PMBA', 'M.Sc.');
INSERT INTO new_students2 (MATRIC_NO, SURNAME, FIRST_NAME, MIDDLE_NAME, MODULE, BURSARY_ACCT_NO, majorid, DEGREE_IN_VIEW) VALUES ('PG/14/0022', 'OHIMAI', 'SYLVESTER', 'IMOHIOSEN', 'ELONGATED', 'SOHISY0001', 'PMBA', 'M.Sc.');
INSERT INTO new_students2 (MATRIC_NO, SURNAME, FIRST_NAME, MIDDLE_NAME, MODULE, BURSARY_ACCT_NO, majorid, DEGREE_IN_VIEW) VALUES ('PG/14/0019', 'ADESINA', 'OPEYEMI', 'ADEFUNKE', 'ELONGATED', 'SADEOP0039', 'PDBA', 'PGD');
INSERT INTO new_students2 (MATRIC_NO, SURNAME, FIRST_NAME, MIDDLE_NAME, MODULE, BURSARY_ACCT_NO, majorid, DEGREE_IN_VIEW) VALUES ('PG/14/0094', 'OLATUNDE', 'OLUSANJO', 'OLALERE', 'ELONGATED', 'SOLAOL0338', 'PDBA', 'PGD');
INSERT INTO new_students2 (MATRIC_NO, SURNAME, FIRST_NAME, MIDDLE_NAME, MODULE, BURSARY_ACCT_NO, majorid, DEGREE_IN_VIEW) VALUES ('PG/14/0103', 'ALHASSAN ', 'HARUNA', '', 'ELONGATED', 'SALHHA0001', 'PDBA', 'PGD');
INSERT INTO new_students2 (MATRIC_NO, SURNAME, FIRST_NAME, MIDDLE_NAME, MODULE, BURSARY_ACCT_NO, majorid, DEGREE_IN_VIEW) VALUES ('PG/14/0104', 'ONAFOWORA', 'ADEBAYO ', 'OLADIPUPO', 'ELONGATED', 'SONAAD0014', 'PDBA', 'PGD');
INSERT INTO new_students2 (MATRIC_NO, SURNAME, FIRST_NAME, MIDDLE_NAME, MODULE, BURSARY_ACCT_NO, majorid, DEGREE_IN_VIEW) VALUES ('PG/14/0105', 'OYENEYIN', 'KEHINDE', '', 'ELONGATED', 'SOYEKE0005', 'PMBA', 'M.Sc.');
INSERT INTO new_students2 (MATRIC_NO, SURNAME, FIRST_NAME, MIDDLE_NAME, MODULE, BURSARY_ACCT_NO, majorid, DEGREE_IN_VIEW) VALUES ('PG/14/0068', 'ODUNAYO', 'YEWANDE', 'ADEYOSOLA', 'ELONGATED', 'SODUYE0007', 'PGCS', 'M.Sc.');
INSERT INTO new_students2 (MATRIC_NO, SURNAME, FIRST_NAME, MIDDLE_NAME, MODULE, BURSARY_ACCT_NO, majorid, DEGREE_IN_VIEW) VALUES ('PG/14/0069', 'SOLANKE', 'OLUWOLE', 'BABAFEMI', 'ELONGATED', 'SSOLOL0023', 'PGCS', 'M.Sc.');
INSERT INTO new_students2 (MATRIC_NO, SURNAME, FIRST_NAME, MIDDLE_NAME, MODULE, BURSARY_ACCT_NO, majorid, DEGREE_IN_VIEW) VALUES ('PG/14/0070', 'OKAFOR', 'TOCHUKWU', 'ADAOBI', 'ELONGATED', 'SOKATO0004', 'PGCS', 'Mphil');
INSERT INTO new_students2 (MATRIC_NO, SURNAME, FIRST_NAME, MIDDLE_NAME, MODULE, BURSARY_ACCT_NO, majorid, DEGREE_IN_VIEW) VALUES ('PG/14/0071', 'GBADEBO', 'AKEEM', 'OLADIMEJI', 'ELONGATED', 'SGBAAK0002', 'PGCS', 'M.Sc.');
INSERT INTO new_students2 (MATRIC_NO, SURNAME, FIRST_NAME, MIDDLE_NAME, MODULE, BURSARY_ACCT_NO, majorid, DEGREE_IN_VIEW) VALUES ('PG/14/0072', 'EZUGBOR', 'ANTHONY', '', 'ELONGATED', 'SEZUAN0001', 'PGCS', 'M.Sc.');
INSERT INTO new_students2 (MATRIC_NO, SURNAME, FIRST_NAME, MIDDLE_NAME, MODULE, BURSARY_ACCT_NO, majorid, DEGREE_IN_VIEW) VALUES ('PG/14/0073', 'EPHRAIM', 'JOSEPH', 'HARUNA', 'ELONGATED', 'SEPHJO0001', 'PDCS', 'PGD');
INSERT INTO new_students2 (MATRIC_NO, SURNAME, FIRST_NAME, MIDDLE_NAME, MODULE, BURSARY_ACCT_NO, majorid, DEGREE_IN_VIEW) VALUES ('PG/14/0074', 'ENOSEGBE ', 'DANIEL', 'LUCKY', 'ELONGATED', 'SENODA0001', 'PDCS', 'PhD');
INSERT INTO new_students2 (MATRIC_NO, SURNAME, FIRST_NAME, MIDDLE_NAME, MODULE, BURSARY_ACCT_NO, majorid, DEGREE_IN_VIEW) VALUES ('PG/14/0008', 'DADA', 'OLUWASAYO', 'AYODELE', 'ELONGATED', 'SDADOL0044', 'PGFI', 'M.Sc.');
INSERT INTO new_students2 (MATRIC_NO, SURNAME, FIRST_NAME, MIDDLE_NAME, MODULE, BURSARY_ACCT_NO, majorid, DEGREE_IN_VIEW) VALUES ('PG/14/0052', 'ACHORI ', 'EMMANUEL', 'ADEBAYO', 'ELONGATED', 'SACHEM0004', 'PGFI', 'M.Sc.');
INSERT INTO new_students2 (MATRIC_NO, SURNAME, FIRST_NAME, MIDDLE_NAME, MODULE, BURSARY_ACCT_NO, majorid, DEGREE_IN_VIEW) VALUES ('PG/14/0059', 'EGBULE', 'CHUKWUKA', '', 'ELONGATED', 'SEGBCH0011', 'PGFI', 'M.Sc.');
INSERT INTO new_students2 (MATRIC_NO, SURNAME, FIRST_NAME, MIDDLE_NAME, MODULE, BURSARY_ACCT_NO, majorid, DEGREE_IN_VIEW) VALUES ('PG/14/0060', 'OKORIE', 'NICHOLAS', 'NAWOKE', 'ELONGATED', 'SOKONI0003', 'PGFI', 'M.Sc.');
INSERT INTO new_students2 (MATRIC_NO, SURNAME, FIRST_NAME, MIDDLE_NAME, MODULE, BURSARY_ACCT_NO, majorid, DEGREE_IN_VIEW) VALUES ('PG/14/0005', 'KEHINDE', 'MICHAEL', '', 'ELONGATED', 'SKEHMI0003', 'PGFI', 'M.Sc.');
INSERT INTO new_students2 (MATRIC_NO, SURNAME, FIRST_NAME, MIDDLE_NAME, MODULE, BURSARY_ACCT_NO, majorid, DEGREE_IN_VIEW) VALUES ('PG/14/0003', 'ADETAYO ', 'ARIMOLA', 'NUSIRAT', 'ELONGATED', 'SADEAR0007', 'PGFI', 'M.Sc.');
INSERT INTO new_students2 (MATRIC_NO, SURNAME, FIRST_NAME, MIDDLE_NAME, MODULE, BURSARY_ACCT_NO, majorid, DEGREE_IN_VIEW) VALUES ('PG/14/0037', 'CHUKWU ', 'ALEXANDER', 'OKORO', 'ELONGATED', 'SCHUAL0001', 'PGFI', 'M.Sc.');
INSERT INTO new_students2 (MATRIC_NO, SURNAME, FIRST_NAME, MIDDLE_NAME, MODULE, BURSARY_ACCT_NO, majorid, DEGREE_IN_VIEW) VALUES ('PG/14/0038', 'ADELEKE ', 'ABIDEMI', 'HEPHZIBAH', 'ELONGATED', 'SADEAB0102', 'PGFI', 'M.Sc.');
INSERT INTO new_students2 (MATRIC_NO, SURNAME, FIRST_NAME, MIDDLE_NAME, MODULE, BURSARY_ACCT_NO, majorid, DEGREE_IN_VIEW) VALUES ('PG/14/0061', 'AYODELE', 'OLANIYI', '', 'ELONGATED', 'SALAAY0003', 'PGFI', 'M.Sc.');
INSERT INTO new_students2 (MATRIC_NO, SURNAME, FIRST_NAME, MIDDLE_NAME, MODULE, BURSARY_ACCT_NO, majorid, DEGREE_IN_VIEW) VALUES ('PG/14/0042', 'ODUNAYO', 'HENRY', 'ADEWALE', 'ELONGATED', 'SODUHE0001', 'PGFI', 'M.Sc.');
INSERT INTO new_students2 (MATRIC_NO, SURNAME, FIRST_NAME, MIDDLE_NAME, MODULE, BURSARY_ACCT_NO, majorid, DEGREE_IN_VIEW) VALUES ('06/0322', 'ISHOLA', 'JOSEPH', 'OLUWASEUN', 'ELONGATED', 'SISHJO0002', 'PGFI', 'M.Sc.');
INSERT INTO new_students2 (MATRIC_NO, SURNAME, FIRST_NAME, MIDDLE_NAME, MODULE, BURSARY_ACCT_NO, majorid, DEGREE_IN_VIEW) VALUES ('PG/14/0045', 'AKOMOLAFE', 'MAYOWA ', 'OLAYEMI', 'ELONGATED', 'SAKOMA0001', 'PMIR', 'MIRM');
INSERT INTO new_students2 (MATRIC_NO, SURNAME, FIRST_NAME, MIDDLE_NAME, MODULE, BURSARY_ACCT_NO, majorid, DEGREE_IN_VIEW) VALUES ('00/0654', 'FOLORUNSO-AKO', 'ADENIKE', 'ADUNOLA', 'ELONGATED', 'SFOLAD0003', 'PDIR', 'PhD');
INSERT INTO new_students2 (MATRIC_NO, SURNAME, FIRST_NAME, MIDDLE_NAME, MODULE, BURSARY_ACCT_NO, majorid, DEGREE_IN_VIEW) VALUES ('PG/14/0035', 'OKEWUMI', 'TITILAYO', 'MARIAM', 'ELONGATED', 'SOKETI0004', 'PMIR', 'MIRM');
INSERT INTO new_students2 (MATRIC_NO, SURNAME, FIRST_NAME, MIDDLE_NAME, MODULE, BURSARY_ACCT_NO, majorid, DEGREE_IN_VIEW) VALUES ('PG/14/0036', 'AINA', 'MOJISOLA ', 'IRETI', 'ELONGATED', 'SAINMO0003', 'PDIR', 'PhD');
INSERT INTO new_students2 (MATRIC_NO, SURNAME, FIRST_NAME, MIDDLE_NAME, MODULE, BURSARY_ACCT_NO, majorid, DEGREE_IN_VIEW) VALUES ('PG/14/0018', 'DADA', 'OLUFUNMILOLA ', 'RACHEAL', 'ELONGATED', 'SDADOL0043', 'PMIR', 'Mphil');
INSERT INTO new_students2 (MATRIC_NO, SURNAME, FIRST_NAME, MIDDLE_NAME, MODULE, BURSARY_ACCT_NO, majorid, DEGREE_IN_VIEW) VALUES ('PG/14/0044', 'SEIDU', 'ISAH', 'OSIMETHA', 'ELONGATED', 'SSEIIS0002', 'PMIR', 'MIRM');
INSERT INTO new_students2 (MATRIC_NO, SURNAME, FIRST_NAME, MIDDLE_NAME, MODULE, BURSARY_ACCT_NO, majorid, DEGREE_IN_VIEW) VALUES ('PG/14/0047', 'ADELEYE ', 'ADEYINKA', '', 'ELONGATED', 'SADEAD0682', 'PMIR', 'MIRM');
INSERT INTO new_students2 (MATRIC_NO, SURNAME, FIRST_NAME, MIDDLE_NAME, MODULE, BURSARY_ACCT_NO, majorid, DEGREE_IN_VIEW) VALUES ('PG/14/0048', 'ALAO ', 'ABIMBOLA', 'OLADEHINDE', 'ELONGATED', 'SALAAB0015', 'PMIR', 'Mphil');
INSERT INTO new_students2 (MATRIC_NO, SURNAME, FIRST_NAME, MIDDLE_NAME, MODULE, BURSARY_ACCT_NO, majorid, DEGREE_IN_VIEW) VALUES ('PG/14/0010', 'IDIEGBEYAN-OSE', 'JEROME', '', 'ELONGATED', 'SIDIJE0002', 'PMIR', 'MIRM');
INSERT INTO new_students2 (MATRIC_NO, SURNAME, FIRST_NAME, MIDDLE_NAME, MODULE, BURSARY_ACCT_NO, majorid, DEGREE_IN_VIEW) VALUES ('PG/14/0025', 'OLAYEMI ', 'RACHAEL', 'OLUSOLA', 'ELONGATED', 'SOLARA0004', 'PMIR', 'MIRM');
INSERT INTO new_students2 (MATRIC_NO, SURNAME, FIRST_NAME, MIDDLE_NAME, MODULE, BURSARY_ACCT_NO, majorid, DEGREE_IN_VIEW) VALUES ('PG/14/0050', 'SAMUEL ', 'TOYOSI ', 'DANIEL', 'ELONGATED', 'SSAMTO0002', 'PDIR', 'PhD');
INSERT INTO new_students2 (MATRIC_NO, SURNAME, FIRST_NAME, MIDDLE_NAME, MODULE, BURSARY_ACCT_NO, majorid, DEGREE_IN_VIEW) VALUES ('PG/14/0058', 'OWOLABI ', 'ADENIKE ', 'AARINOLA', 'ELONGATED', 'SOWOAD0010', 'PMIR', 'MBA');
INSERT INTO new_students2 (MATRIC_NO, SURNAME, FIRST_NAME, MIDDLE_NAME, MODULE, BURSARY_ACCT_NO, majorid, DEGREE_IN_VIEW) VALUES ('05/0004', 'AJIKE ', 'CHIDINMA', 'FLORENCE', 'ELONGATED', 'SAJIFL0001', 'PDIR', 'PhD');
INSERT INTO new_students2 (MATRIC_NO, SURNAME, FIRST_NAME, MIDDLE_NAME, MODULE, BURSARY_ACCT_NO, majorid, DEGREE_IN_VIEW) VALUES ('PG/14/0017', 'POPOOLA', 'OLUWAFOLAKEMI', 'GRACE', 'ELONGATED', 'SPOPOL0017', 'PMIR', 'MIRM');
INSERT INTO new_students2 (MATRIC_NO, SURNAME, FIRST_NAME, MIDDLE_NAME, MODULE, BURSARY_ACCT_NO, majorid, DEGREE_IN_VIEW) VALUES ('PG/14/0049', 'BADMUS', 'IBRAHIM', 'TEMITOPE', 'ELONGATED', 'SBADIB0001', 'PMIR', 'MIRM');
INSERT INTO new_students2 (MATRIC_NO, SURNAME, FIRST_NAME, MIDDLE_NAME, MODULE, BURSARY_ACCT_NO, majorid, DEGREE_IN_VIEW) VALUES ('PG/14/0027', 'ABIOYE', 'VICTORIA', 'OLUFUNKE', 'ELONGATED', 'SABIVI0002', 'PMIR', 'MIRM');
INSERT INTO new_students2 (MATRIC_NO, SURNAME, FIRST_NAME, MIDDLE_NAME, MODULE, BURSARY_ACCT_NO, majorid, DEGREE_IN_VIEW) VALUES ('PG/14/0040', 'OYEFUGA ', 'OLUYEMI ', 'HELEN', 'ELONGATED', 'SOYEOL0131', 'PMIR', 'MIRM');
INSERT INTO new_students2 (MATRIC_NO, SURNAME, FIRST_NAME, MIDDLE_NAME, MODULE, BURSARY_ACCT_NO, majorid, DEGREE_IN_VIEW) VALUES ('PG/14/0039', 'ADEMUYIWA', 'IYABO', 'YEWANDE', 'ELONGATED', 'SADEIY0010', 'PDIR', 'PhD');
INSERT INTO new_students2 (MATRIC_NO, SURNAME, FIRST_NAME, MIDDLE_NAME, MODULE, BURSARY_ACCT_NO, majorid, DEGREE_IN_VIEW) VALUES ('PG/14/0106', 'OLAOKE', 'DOLAPO', 'PETER', 'ELONGATED', 'SOLADO0014', 'PMIR', 'MIRM');
INSERT INTO new_students2 (MATRIC_NO, SURNAME, FIRST_NAME, MIDDLE_NAME, MODULE, BURSARY_ACCT_NO, majorid, DEGREE_IN_VIEW) VALUES ('PG/14/0014', 'BALOGUN', 'SEGUN', 'GODWIN', 'ELONGATED', 'SBALSE0002', 'PGMC', 'M.Sc.');
INSERT INTO new_students2 (MATRIC_NO, SURNAME, FIRST_NAME, MIDDLE_NAME, MODULE, BURSARY_ACCT_NO, majorid, DEGREE_IN_VIEW) VALUES ('PG/14/0024', 'OGUNWOLE ', 'OLUSEGUN', 'ABIODUN', 'ELONGATED', 'SOGUOL0283', 'PDMC', 'PhD');
INSERT INTO new_students2 (MATRIC_NO, SURNAME, FIRST_NAME, MIDDLE_NAME, MODULE, BURSARY_ACCT_NO, majorid, DEGREE_IN_VIEW) VALUES ('PG/14/0034', 'EDOMI', 'OYIBO', 'OVIE', 'ELONGATED', 'SEDOOY0001', 'PGMC', 'M.Sc.');
INSERT INTO new_students2 (MATRIC_NO, SURNAME, FIRST_NAME, MIDDLE_NAME, MODULE, BURSARY_ACCT_NO, majorid, DEGREE_IN_VIEW) VALUES ('06/0955', 'SHOFOWORA', 'OLUWABUKOLA', 'OLUWAPELUMI', 'ELONGATED', 'SSOFOL0006', 'PGMC', 'M.Sc.');
INSERT INTO new_students2 (MATRIC_NO, SURNAME, FIRST_NAME, MIDDLE_NAME, MODULE, BURSARY_ACCT_NO, majorid, DEGREE_IN_VIEW) VALUES ('08/1289', 'UZEGBU-WILSON', 'CHIKA ', '', 'ELONGATED', 'SUZUCH0003', 'PGMC', 'M.Sc.');
INSERT INTO new_students2 (MATRIC_NO, SURNAME, FIRST_NAME, MIDDLE_NAME, MODULE, BURSARY_ACCT_NO, majorid, DEGREE_IN_VIEW) VALUES ('PG/14/0107', 'FANIYI', 'BELINDA', 'AMEZE', 'ELONGATED', 'SFANBE0001', 'PDMC', 'PhD');
INSERT INTO new_students2 (MATRIC_NO, SURNAME, FIRST_NAME, MIDDLE_NAME, MODULE, BURSARY_ACCT_NO, majorid, DEGREE_IN_VIEW) VALUES ('PG/14/0062', 'AHAOMA', 'ONYEBUCHI', '', 'ELONGATED', 'SAHAON0001', 'PGPS', 'M.Sc.');
INSERT INTO new_students2 (MATRIC_NO, SURNAME, FIRST_NAME, MIDDLE_NAME, MODULE, BURSARY_ACCT_NO, majorid, DEGREE_IN_VIEW) VALUES ('PG/14/0063', 'EJIKEMEUWA', 'NGOZI', 'JOY', 'ELONGATED', 'SEJING0003', 'PGPS', 'M.Sc.');
INSERT INTO new_students2 (MATRIC_NO, SURNAME, FIRST_NAME, MIDDLE_NAME, MODULE, BURSARY_ACCT_NO, majorid, DEGREE_IN_VIEW) VALUES ('PG/14/0064', 'NDIEN', 'AUGUSTINE', 'P', 'ELONGATED', 'SNDIAU0001', 'PDPS', 'Mphil');
INSERT INTO new_students2 (MATRIC_NO, SURNAME, FIRST_NAME, MIDDLE_NAME, MODULE, BURSARY_ACCT_NO, majorid, DEGREE_IN_VIEW) VALUES ('PG/14/0065', 'OLAYINKA', 'OLUWABUSAYO', 'AWENI', 'ELONGATED', 'SOLAOL0337', 'PDPS', 'Mphil');
INSERT INTO new_students2 (MATRIC_NO, SURNAME, FIRST_NAME, MIDDLE_NAME, MODULE, BURSARY_ACCT_NO, majorid, DEGREE_IN_VIEW) VALUES ('PG/14/0066', 'OLORUNSHOLA', 'ERICMORE', 'OLABOWALE', 'ELONGATED', 'SOLOER0001', 'PDPS', 'PhD');
INSERT INTO new_students2 (MATRIC_NO, SURNAME, FIRST_NAME, MIDDLE_NAME, MODULE, BURSARY_ACCT_NO, majorid, DEGREE_IN_VIEW) VALUES ('PG/10/0195', 'UNEGBU', 'CHIGOZIE', 'PEARL', 'ELONGATED', 'SUNGPE0001', 'PDPS', 'Mphil');
INSERT INTO new_students2 (MATRIC_NO, SURNAME, FIRST_NAME, MIDDLE_NAME, MODULE, BURSARY_ACCT_NO, majorid, DEGREE_IN_VIEW) VALUES ('PG/14/0004', 'OGUNDIPE', 'ATILADE', 'DAVIDE', 'ELONGATED', 'SOGUAT0003', 'PDPS', 'Mphil');
INSERT INTO new_students2 (MATRIC_NO, SURNAME, FIRST_NAME, MIDDLE_NAME, MODULE, BURSARY_ACCT_NO, majorid, DEGREE_IN_VIEW) VALUES ('PG/14/0160', 'OKORONKWO', 'PATIENCE', 'NNSINNA', 'ELONGATED', 'SOKOPA0007', 'PDPS', 'Mphil');
INSERT INTO new_students2 (MATRIC_NO, SURNAME, FIRST_NAME, MIDDLE_NAME, MODULE, BURSARY_ACCT_NO, majorid, DEGREE_IN_VIEW) VALUES ('PG/14/0084', 'ISHOLA', 'ADEBOLA', 'OLUBUNMI', 'ELONGATED', 'SISHAD0002', 'PDPS', 'Mphil');
INSERT INTO new_students2 (MATRIC_NO, SURNAME, FIRST_NAME, MIDDLE_NAME, MODULE, BURSARY_ACCT_NO, majorid, DEGREE_IN_VIEW) VALUES ('PG/14/0095', 'ADIRO', 'LUKMAN', 'OLUFEMI', 'ELONGATED', 'SADILU0001', 'PDPS', 'PhD');
INSERT INTO new_students2 (MATRIC_NO, SURNAME, FIRST_NAME, MIDDLE_NAME, MODULE, BURSARY_ACCT_NO, majorid, DEGREE_IN_VIEW) VALUES ('PG/10/0088', 'AKO ', 'IKHIANOSIMHE', 'BENJAMIN', 'ELONGATED', 'SAKOIK0001', 'PDPS', 'PhD');
INSERT INTO new_students2 (MATRIC_NO, SURNAME, FIRST_NAME, MIDDLE_NAME, MODULE, BURSARY_ACCT_NO, majorid, DEGREE_IN_VIEW) VALUES ('PG/14/0015', 'IRO', 'ULOMA', 'CHINWE', 'ELONGATED', 'SIROUL0001', 'PDPS', 'MPM');
INSERT INTO new_students2 (MATRIC_NO, SURNAME, FIRST_NAME, MIDDLE_NAME, MODULE, BURSARY_ACCT_NO, majorid, DEGREE_IN_VIEW) VALUES ('PG/14/0108', 'BABALOLA', 'BOLA', 'TAIWO', 'ELONGATED', 'SBABBO0005', 'PDPS', 'Mphil');
INSERT INTO new_students2 (MATRIC_NO, SURNAME, FIRST_NAME, MIDDLE_NAME, MODULE, BURSARY_ACCT_NO, majorid, DEGREE_IN_VIEW) VALUES ('PG/14/0002', 'FAYOMI', 'OMOTOLA', 'OLAITAN', 'ELONGATED', 'SFAYOM0002', 'PGPH', 'MPH');
INSERT INTO new_students2 (MATRIC_NO, SURNAME, FIRST_NAME, MIDDLE_NAME, MODULE, BURSARY_ACCT_NO, majorid, DEGREE_IN_VIEW) VALUES ('PG/14/0109', 'UGIAGBE', 'OLUWATOSIN', 'OMOBOLA', 'ELONGATED', 'SUGIOL0001', 'PGPH', 'MPH');

INSERT INTO students (denominationid, org_id, Sex, MaritalStatus, Nationality, countrycodeid, gcountrycodeid, stateid, 
	studentid, surname, firstname, othernames, 
	accountnumber, departmentid)

SELECT 'CHRI', 2, 'M', 'S', 'NG', 'NG', 'NG', 39, 
	upper(trim(new_students2.MATRIC_NO)), new_students2.SURNAME, new_students2.FIRST_NAME, new_students2.MIDDLE_NAME, 
	new_students2.BURSARY_ACCT_NO, majors.departmentid

FROM new_students2 INNER JOIN majors ON trim(upper(new_students2.majorid)) = trim(upper(majors.majorid))
LEFT JOIN students ON upper(trim(new_students2.MATRIC_NO)) = upper(trim(students.studentid))

WHERE students.studentid is null;

UPDATE new_students2 SET DEGREE_IN_VIEW = 'PHD' WHERE DEGREE_IN_VIEW = 'Mphil';
UPDATE new_students2 SET DEGREE_IN_VIEW = 'PHD' WHERE DEGREE_IN_VIEW = 'PhD';
UPDATE new_students2 SET DEGREE_IN_VIEW = 'MAST' WHERE DEGREE_IN_VIEW = 'MPM';
UPDATE new_students2 SET DEGREE_IN_VIEW = 'MAST' WHERE DEGREE_IN_VIEW = 'M.Sc.';
UPDATE new_students2 SET DEGREE_IN_VIEW = 'MAST' WHERE DEGREE_IN_VIEW is null;
UPDATE new_students2 SET DEGREE_IN_VIEW = 'PGDI' WHERE DEGREE_IN_VIEW = 'PGD';

INSERT INTO studentdegrees (degreeid, sublevelid, bulletingid, org_id, studentid)
SELECT 'MA', new_students2.DEGREE_IN_VIEW, 3, 2, new_students2.MATRIC_NO
FROM new_students2 LEFT JOIN studentdegrees ON (new_students2.MATRIC_NO = studentdegrees.studentid) 
WHERE (studentdegrees.studentid is null);

INSERT INTO studentmajors (studentdegreeid, majorid, org_id)
SELECT studentdegrees.studentdegreeid, new_students2.majorid, 2
FROM (new_students2 INNER JOIN studentdegrees ON studentdegrees.studentid = new_students2.MATRIC_NO)
	LEFT JOIN  studentmajors ON studentdegrees.studentdegreeid = studentmajors.studentdegreeid
WHERE (studentmajors.studentdegreeid is null);




