INSERT INTO sys_continents (sys_continent_id, sys_continent_name) VALUES
('AF', 'Africa'),
('AS', 'Asia'),
('EU', 'Europe'),
('NA', 'North America'),
('SA', 'South America'),
('OC', 'Oceania'),
('AN', 'Antarctica');

INSERT INTO sys_countrys (sys_continent_id, sys_country_id, sys_country_code, sys_country_number, sys_country_name, sys_phone_code, sys_currency_name, sys_currency_cents, sys_currency_code) VALUES
('AS', 'AF', 'AFG', '004', 'Afghanistan', null, null, null, null),
('EU', 'AX', 'ALA', '248', 'Aland Islands', null, null, null, null),
('EU', 'AL', 'ALB', '008', 'Albania', null, null, null, null),
('AF', 'DZ', 'DZA', '012', 'Algeria', null, null, null, null),
('OC', 'AS', 'ASM', '016', 'American Samoa', null, null, null, null),
('EU', 'AD', 'AND', '020', 'Andorra', null, null, null, null),
('AF', 'AO', 'AGO', '024', 'Angola', null, null, null, null),
('NA', 'AI', 'AIA', '660', 'Anguilla', null, null, null, null),
('AN', 'AQ', 'ATA', '010', 'Antarctica', null, null, null, null),
('NA', 'AG', 'ATG', '028', 'Antigua and Barbuda', null, null, null, null),
('SA', 'AR', 'ARG', '032', 'Argentina', null, null, null, null),
('AS', 'AM', 'ARM', '051', 'Armenia', null, null, null, null),
('NA', 'AW', 'ABW', '533', 'Aruba', null, null, null, null),
('OC', 'AU', 'AUS', '036', 'Australia', null, null, null, null),
('EU', 'AT', 'AUT', '040', 'Austria', null, null, null, null),
('AS', 'AZ', 'AZE', '031', 'Azerbaijan', null, null, null, null),
('NA', 'BS', 'BHS', '044', 'Bahamas', null, null, null, null),
('AS', 'BH', 'BHR', '048', 'Bahrain', null, null, null, null),
('AS', 'BD', 'BGD', '050', 'Bangladesh', null, null, null, null),
('NA', 'BB', 'BRB', '052', 'Barbados', null, null, null, null),
('EU', 'BY', 'BLR', '112', 'Belarus', null, null, null, null),
('EU', 'BE', 'BEL', '056', 'Belgium', null, null, null, null),
('NA', 'BZ', 'BLZ', '084', 'Belize', null, null, null, null),
('AF', 'BJ', 'BEN', '204', 'Benin', null, null, null, null),
('NA', 'BM', 'BMU', '060', 'Bermuda', null, null, null, null),
('AS', 'BT', 'BTN', '064', 'Bhutan', null, null, null, null),
('SA', 'BO', 'BOL', '068', 'Bolivia', null, null, null, null),
('EU', 'BA', 'BIH', '070', 'Bosnia and Herzegovina', null, null, null, null),
('AF', 'BW', 'BWA', '072', 'Botswana', null, null, null, null),
('AN', 'BV', 'BVT', '074', 'Bouvet Island', null, null, null, null),
('SA', 'BR', 'BRA', '076', 'Brazil', null, null, null, null),
('AS', 'IO', 'IOT', '086', 'British Indian Ocean Territory', null, null, null, null),
('NA', 'VG', 'VGB', '092', 'British Virgin Islands', null, null, null, null),
('AS', 'BN', 'BRN', '096', 'Brunei Darussalam', null, null, null, null),
('EU', 'BG', 'BGR', '100', 'Bulgaria', null, null, null, null),
('AF', 'BF', 'BFA', '854', 'Burkina Faso', null, null, null, null),
('AF', 'BI', 'BDI', '108', 'Burundi', null, null, null, null),
('AS', 'KH', 'KHM', '116', 'Cambodia', null, null, null, null),
('AF', 'CM', 'CMR', '120', 'Cameroon', null, null, null, null),
('NA', 'CA', 'CAN', '124', 'Canada', null, null, null, null),
('AF', 'CV', 'CPV', '132', 'Cape Verde', null, null, null, null),
('NA', 'KY', 'CYM', '136', 'Cayman Islands', null, null, null, null),
('AF', 'CF', 'CAF', '140', 'Central African Republic', null, null, null, null),
('AF', 'TD', 'TCD', '148', 'Chad', null, null, null, null),
('SA', 'CL', 'CHL', '152', 'Chile', null, null, null, null),
('AS', 'CN', 'CHN', '156', 'China', null, null, null, null),
('AS', 'CX', 'CXR', '162', 'Christmas Island', null, null, null, null),
('AS', 'CC', 'CCK', '166', 'Cocos Keeling Islands', null, null, null, null),
('SA', 'CO', 'COL', '170', 'Colombia', null, null, null, null),
('AF', 'KM', 'COM', '174', 'Comoros', null, null, null, null),
('AF', 'CD', 'COD', '180', 'Democratic Republic of Congo', null, null, null, null),
('AF', 'CG', 'COG', '178', 'Republic of Congo', null, null, null, null),
('OC', 'CK', 'COK', '184', 'Cook Islands', null, null, null, null),
('NA', 'CR', 'CRI', '188', 'Costa Rica', null, null, null, null),
('AF', 'CI', 'CIV', '384', 'Cote d Ivoire', null, null, null, null),
('EU', 'HR', 'HRV', '191', 'Croatia', null, null, null, null),
('NA', 'CU', 'CUB', '192', 'Cuba', null, null, null, null),
('AS', 'CY', 'CYP', '196', 'Cyprus', null, null, null, null),
('EU', 'CZ', 'CZE', '203', 'Czech Republic', null, null, null, null),
('EU', 'DK', 'DNK', '208', 'Denmark', null, null, null, null),
('AF', 'DJ', 'DJI', '262', 'Djibouti', null, null, null, null),
('NA', 'DM', 'DMA', '212', 'Dominica', null, null, null, null),
('NA', 'DO', 'DOM', '214', 'Dominican Republic', null, null, null, null),
('SA', 'EC', 'ECU', '218', 'Ecuador', null, null, null, null),
('AF', 'EG', 'EGY', '818', 'Egypt', null, null, null, null),
('NA', 'SV', 'SLV', '222', 'El Salvador', null, null, null, null),
('AF', 'GQ', 'GNQ', '226', 'Equatorial Guinea', null, null, null, null),
('AF', 'ER', 'ERI', '232', 'Eritrea', null, null, null, null),
('EU', 'EE', 'EST', '233', 'Estonia', null, null, null, null),
('AF', 'ET', 'ETH', '231', 'Ethiopia', null, null, null, null),
('EU', 'FO', 'FRO', '234', 'Faroe Islands', null, null, null, null),
('SA', 'FK', 'FLK', '238', 'Falkland Islands', null, null, null, null),
('OC', 'FJ', 'FJI', '242', 'Fiji', null, null, null, null),
('EU', 'FI', 'FIN', '246', 'Finland', null, null, null, null),
('EU', 'FR', 'FRA', '250', 'France', null, null, null, null),
('SA', 'GF', 'GUF', '254', 'French Guiana', null, null, null, null),
('OC', 'PF', 'PYF', '258', 'French Polynesia', null, null, null, null),
('AN', 'TF', 'ATF', '260', 'French Southern Territories', null, null, null, null),
('AF', 'GA', 'GAB', '266', 'Gabon', null, null, null, null),
('AF', 'GM', 'GMB', '270', 'Gambia', null, null, null, null),
('AS', 'GE', 'GEO', '268', 'Georgia', null, null, null, null),
('EU', 'DE', 'DEU', '276', 'Germany', null, null, null, null),
('AF', 'GH', 'GHA', '288', 'Ghana', null, null, null, null),
('EU', 'GI', 'GIB', '292', 'Gibraltar', null, null, null, null),
('EU', 'GR', 'GRC', '300', 'Greece', null, null, null, null),
('NA', 'GL', 'GRL', '304', 'Greenland', null, null, null, null),
('NA', 'GD', 'GRD', '308', 'Grenada', null, null, null, null),
('NA', 'GP', 'GLP', '312', 'Guadeloupe', null, null, null, null),
('OC', 'GU', 'GUM', '316', 'Guam', null, null, null, null),
('NA', 'GT', 'GTM', '320', 'Guatemala', null, null, null, null),
('EU', 'GG', 'GGY', '831', 'Guernsey', null, null, null, null),
('AF', 'GN', 'GIN', '324', 'Guinea', null, null, null, null),
('AF', 'GW', 'GNB', '624', 'Guinea-Bissau', null, null, null, null),
('SA', 'GY', 'GUY', '328', 'Guyana', null, null, null, null),
('NA', 'HT', 'HTI', '332', 'Haiti', null, null, null, null),
('AN', 'HM', 'HMD', '334', 'Heard Island and McDonald Islands', null, null, null, null),
('EU', 'VA', 'VAT', '336', 'Vatican City State', null, null, null, null),
('NA', 'HN', 'HND', '340', 'Honduras', null, null, null, null),
('AS', 'HK', 'HKG', '344', 'Hong Kong', null, null, null, null),
('EU', 'HU', 'HUN', '348', 'Hungary', null, null, null, null),
('EU', 'IS', 'ISL', '352', 'Iceland', null, null, null, null),
('AS', 'IN', 'IND', '356', 'India', null, null, null, null),
('AS', 'ID', 'IDN', '360', 'Indonesia', null, null, null, null),
('AS', 'IR', 'IRN', '364', 'Iran', null, null, null, null),
('AS', 'IQ', 'IRQ', '368', 'Iraq', null, null, null, null),
('EU', 'IE', 'IRL', '372', 'Ireland', null, null, null, null),
('EU', 'IM', 'IMN', '833', 'Isle of Man', null, null, null, null),
('AS', 'IL', 'ISR', '376', 'Israel', null, null, null, null),
('EU', 'IT', 'ITA', '380', 'Italy', null, null, null, null),
('NA', 'JM', 'JAM', '388', 'Jamaica', null, null, null, null),
('AS', 'JP', 'JPN', '392', 'Japan', null, null, null, null),
('EU', 'JE', 'JEY', '832', 'Bailiwick of Jersey', null, null, null, null),
('AS', 'JO', 'JOR', '400', 'Jordan', null, null, null, null),
('AS', 'KZ', 'KAZ', '398', 'Kazakhstan', null, null, null, null),
('AF', 'KE', 'KEN', '404', 'Kenya', null, null, null, null),
('OC', 'KI', 'KIR', '296', 'Kiribati', null, null, null, null),
('AS', 'KP', 'PRK', '408', 'North Korea', null, null, null, null),
('AS', 'KR', 'KOR', '410', 'South Korea', null, null, null, null),
('AS', 'KW', 'KWT', '414', 'Kuwait', null, null, null, null),
('AS', 'KG', 'KGZ', '417', 'Kyrgyz Republic', null, null, null, null),
('AS', 'LA', 'LAO', '418', 'Lao Peoples Democratic Republic', null, null, null, null),
('EU', 'LV', 'LVA', '428', 'Latvia', null, null, null, null),
('AS', 'LB', 'LBN', '422', 'Lebanon', null, null, null, null),
('AF', 'LS', 'LSO', '426', 'Lesotho', null, null, null, null),
('AF', 'LR', 'LBR', '430', 'Liberia', null, null, null, null),
('AF', 'LY', 'LBY', '434', 'Libyan Arab Jamahiriya', null, null, null, null),
('EU', 'LI', 'LIE', '438', 'Liechtenstein', null, null, null, null),
('EU', 'LT', 'LTU', '440', 'Lithuania', null, null, null, null),
('EU', 'LU', 'LUX', '442', 'Luxembourg', null, null, null, null),
('AS', 'MO', 'MAC', '446', 'Macao', null, null, null, null),
('EU', 'MK', 'MKD', '807', 'Macedonia', null, null, null, null),
('AF', 'MG', 'MDG', '450', 'Madagascar', null, null, null, null),
('AF', 'MW', 'MWI', '454', 'Malawi', null, null, null, null),
('AS', 'MY', 'MYS', '458', 'Malaysia', null, null, null, null),
('AS', 'MV', 'MDV', '462', 'Maldives', null, null, null, null),
('AF', 'ML', 'MLI', '466', 'Mali', null, null, null, null),
('EU', 'MT', 'MLT', '470', 'Malta', null, null, null, null),
('OC', 'MH', 'MHL', '584', 'Marshall Islands', null, null, null, null),
('NA', 'MQ', 'MTQ', '474', 'Martinique', null, null, null, null),
('AF', 'MR', 'MRT', '478', 'Mauritania', null, null, null, null),
('AF', 'MU', 'MUS', '480', 'Mauritius', null, null, null, null),
('AF', 'YT', 'MYT', '175', 'Mayotte', null, null, null, null),
('NA', 'MX', 'MEX', '484', 'Mexico', null, null, null, null),
('OC', 'FM', 'FSM', '583', 'Micronesia', null, null, null, null),
('EU', 'MD', 'MDA', '498', 'Moldova', null, null, null, null),
('EU', 'MC', 'MCO', '492', 'Monaco', null, null, null, null),
('AS', 'MN', 'MNG', '496', 'Mongolia', null, null, null, null),
('EU', 'ME', 'MNE', '499', 'Montenegro', null, null, null, null),
('NA', 'MS', 'MSR', '500', 'Montserrat', null, null, null, null),
('AF', 'MA', 'MAR', '504', 'Morocco', null, null, null, null),
('AF', 'MZ', 'MOZ', '508', 'Mozambique', null, null, null, null),
('AS', 'MM', 'MMR', '104', 'Myanmar', null, null, null, null),
('AF', 'NA', 'NAM', '516', 'Namibia', null, null, null, null),
('OC', 'NR', 'NRU', '520', 'Nauru', null, null, null, null),
('AS', 'NP', 'NPL', '524', 'Nepal', null, null, null, null),
('NA', 'AN', 'ANT', '530', 'Netherlands Antilles', null, null, null, null),
('EU', 'NL', 'NLD', '528', 'Netherlands', null, null, null, null),
('OC', 'NC', 'NCL', '540', 'New Caledonia', null, null, null, null),
('OC', 'NZ', 'NZL', '554', 'New Zealand', null, null, null, null),
('NA', 'NI', 'NIC', '558', 'Nicaragua', null, null, null, null),
('AF', 'NE', 'NER', '562', 'Niger', null, null, null, null),
('AF', 'NG', 'NGA', '566', 'Nigeria', null, null, null, null),
('OC', 'NU', 'NIU', '570', 'Niue', null, null, null, null),
('OC', 'NF', 'NFK', '574', 'Norfolk Island', null, null, null, null),
('OC', 'MP', 'MNP', '580', 'Northern Mariana Islands', null, null, null, null),
('EU', 'NO', 'NOR', '578', 'Norway', null, null, null, null),
('AS', 'OM', 'OMN', '512', 'Oman', null, null, null, null),
('AS', 'PK', 'PAK', '586', 'Pakistan', null, null, null, null),
('OC', 'PW', 'PLW', '585', 'Palau', null, null, null, null),
('AS', 'PS', 'PSE', '275', 'Palestinian Territory', null, null, null, null),
('NA', 'PA', 'PAN', '591', 'Panama', null, null, null, null),
('OC', 'PG', 'PNG', '598', 'Papua New Guinea', null, null, null, null),
('SA', 'PY', 'PRY', '600', 'Paraguay', null, null, null, null),
('SA', 'PE', 'PER', '604', 'Peru', null, null, null, null),
('AS', 'PH', 'PHL', '608', 'Philippines', null, null, null, null),
('OC', 'PN', 'PCN', '612', 'Pitcairn Islands', null, null, null, null),
('EU', 'PL', 'POL', '616', 'Poland', null, null, null, null),
('EU', 'PT', 'PRT', '620', 'Portugal', null, null, null, null),
('NA', 'PR', 'PRI', '630', 'Puerto Rico', null, null, null, null),
('AS', 'QA', 'QAT', '634', 'Qatar', null, null, null, null),
('AF', 'RE', 'REU', '638', 'Reunion', null, null, null, null),
('EU', 'RO', 'ROU', '642', 'Romania', null, null, null, null),
('EU', 'RU', 'RUS', '643', 'Russian Federation', null, null, null, null),
('AF', 'RW', 'RWA', '646', 'Rwanda', null, null, null, null),
('NA', 'BL', 'BLM', '652', 'Saint Barthelemy', null, null, null, null),
('AF', 'SH', 'SHN', '654', 'Saint Helena', null, null, null, null),
('NA', 'KN', 'KNA', '659', 'Saint Kitts and Nevis', null, null, null, null),
('NA', 'LC', 'LCA', '662', 'Saint Lucia', null, null, null, null),
('NA', 'MF', 'MAF', '663', 'Saint Martin', null, null, null, null),
('NA', 'PM', 'SPM', '666', 'Saint Pierre and Miquelon', null, null, null, null),
('NA', 'VC', 'VCT', '670', 'Saint Vincent and the Grenadines', null, null, null, null),
('OC', 'WS', 'WSM', '882', 'Samoa', null, null, null, null),
('EU', 'SM', 'SMR', '674', 'San Marino', null, null, null, null),
('AF', 'ST', 'STP', '678', 'Sao Tome and Principe', null, null, null, null),
('AS', 'SA', 'SAU', '682', 'Saudi Arabia', null, null, null, null),
('AF', 'SN', 'SEN', '686', 'Senegal', null, null, null, null),
('EU', 'RS', 'SRB', '688', 'Serbia', null, null, null, null),
('AF', 'SC', 'SYC', '690', 'Seychelles', null, null, null, null),
('AF', 'SL', 'SLE', '694', 'Sierra Leone', null, null, null, null),
('AS', 'SG', 'SGP', '702', 'Singapore', null, null, null, null),
('EU', 'SK', 'SVK', '703', 'Slovakia', null, null, null, null),
('EU', 'SI', 'SVN', '705', 'Slovenia', null, null, null, null),
('OC', 'SB', 'SLB', '090', 'Solomon Islands', null, null, null, null),
('AF', 'SO', 'SOM', '706', 'Somalia', null, null, null, null),
('AF', 'ZA', 'ZAF', '710', 'South Africa', null, null, null, null),
('AN', 'GS', 'SGS', '239', 'South Georgia and the South Sandwich Islands', null, null, null, null),
('EU', 'ES', 'ESP', '724', 'Spain', null, null, null, null),
('AS', 'LK', 'LKA', '144', 'Sri Lanka', null, null, null, null),
('AF', 'SD', 'SDN', '736', 'Sudan', null, null, null, null),
('AF', 'SS', 'SSN', '737', 'South Sudan', null, null, null, null),
('SA', 'SR', 'SUR', '740', 'Suriname', null, null, null, null),
('EU', 'SJ', 'SJM', '744', 'Svalbard & Jan Mayen Islands', null, null, null, null),
('AF', 'SZ', 'SWZ', '748', 'Swaziland', null, null, null, null),
('EU', 'SE', 'SWE', '752', 'Sweden', null, null, null, null),
('EU', 'CH', 'CHE', '756', 'Switzerland', null, null, null, null),
('AS', 'SY', 'SYR', '760', 'Syrian Arab Republic', null, null, null, null),
('AS', 'TW', 'TWN', '158', 'Taiwan', null, null, null, null),
('AS', 'TJ', 'TJK', '762', 'Tajikistan', null, null, null, null),
('AF', 'TZ', 'TZA', '834', 'Tanzania', null, null, null, null),
('AS', 'TH', 'THA', '764', 'Thailand', null, null, null, null),
('AS', 'TL', 'TLS', '626', 'Timor-Leste', null, null, null, null),
('AF', 'TG', 'TGO', '768', 'Togo', null, null, null, null),
('OC', 'TK', 'TKL', '772', 'Tokelau', null, null, null, null),
('OC', 'TO', 'TON', '776', 'Tonga', null, null, null, null),
('NA', 'TT', 'TTO', '780', 'Trinidad and Tobago', null, null, null, null),
('AF', 'TN', 'TUN', '788', 'Tunisia', null, null, null, null),
('AS', 'TR', 'TUR', '792', 'Turkey', null, null, null, null),
('AS', 'TM', 'TKM', '795', 'Turkmenistan', null, null, null, null),
('NA', 'TC', 'TCA', '796', 'Turks and Caicos Islands', null, null, null, null),
('OC', 'TV', 'TUV', '798', 'Tuvalu', null, null, null, null),
('AF', 'UG', 'UGA', '800', 'Uganda', null, null, null, null),
('EU', 'UA', 'UKR', '804', 'Ukraine', null, null, null, null),
('AS', 'AE', 'ARE', '784', 'United Arab Emirates', null, null, null, null),
('EU', 'GB', 'GBR', '826', 'United Kingdom of Great Britain & Northern Ireland', null, null, null, null),
('NA', 'US', 'USA', '840', 'United States of America', null, null, null, null),
('OC', 'UM', 'UMI', '581', 'United States Minor Outlying Islands', null, null, null, null),
('NA', 'VI', 'VIR', '850', 'United States Virgin Islands', null, null, null, null),
('SA', 'UY', 'URY', '858', 'Uruguay', null, null, null, null),
('AS', 'UZ', 'UZB', '860', 'Uzbekistan', null, null, null, null),
('OC', 'VU', 'VUT', '548', 'Vanuatu', null, null, null, null),
('SA', 'VE', 'VEN', '862', 'Venezuela', null, null, null, null),
('AS', 'VN', 'VNM', '704', 'Vietnam', null, null, null, null),
('OC', 'WF', 'WLF', '876', 'Wallis and Futuna', null, null, null, null),
('AF', 'EH', 'ESH', '732', 'Western Sahara', null, null, null, null),
('AS', 'YE', 'YEM', '887', 'Yemen', null, null, null, null),
('AF', 'ZM', 'ZMB', '894', 'Zambia', null, null, null, null),
('AF', 'ZW', 'ZWE', '716', 'Zimbabwe', null, null, null, null);

