delete from approval_checklists where checklist_id IN (SELECT checklist_id from checklists where workflow_phase_id = 255);
delete from checklists where workflow_phase_id = 255;
delete from approval_checklists where checklist_id IN (SELECT checklist_id from checklists where workflow_phase_id = 257);
delete from checklists where workflow_phase_id = 257;
delete from approval_checklists where checklist_id IN (SELECT checklist_id from checklists where workflow_phase_id = 258);
delete from checklists where workflow_phase_id = 258;
delete from approval_checklists where checklist_id IN (SELECT checklist_id from checklists where workflow_phase_id = 259); 
delete from checklists where workflow_phase_id = 259;
commit;

INSERT INTO CHECKLISTS (WORKFLOW_PHASE_ID, CLIENT_INDUSTRY_ID, CLIENT_CATEGORY_ID, CHECKLIST_NUMBER, REQUIREMENT) VALUES (255, 17, 1, 1, 'Is a covering letter on applicant letterhead included?');
INSERT INTO CHECKLISTS (WORKFLOW_PHASE_ID, CLIENT_INDUSTRY_ID, CLIENT_CATEGORY_ID, CHECKLIST_NUMBER, REQUIREMENT) VALUES (255, 17, 1, 2, 'Is the application duly completed?');
INSERT INTO CHECKLISTS (WORKFLOW_PHASE_ID, CLIENT_INDUSTRY_ID, CLIENT_CATEGORY_ID, CHECKLIST_NUMBER, REQUIREMENT) VALUES (255, 17, 1, 3, 'Is the application signed, giving applicant’s name and designation?');
INSERT INTO CHECKLISTS (WORKFLOW_PHASE_ID, CLIENT_INDUSTRY_ID, CLIENT_CATEGORY_ID, CHECKLIST_NUMBER, REQUIREMENT) VALUES (255, 17, 1, 4, 'Is a letter from a Registered Technical Personnel included?');
INSERT INTO CHECKLISTS (WORKFLOW_PHASE_ID, CLIENT_INDUSTRY_ID, CLIENT_CATEGORY_ID, CHECKLIST_NUMBER, REQUIREMENT) VALUES (255, 17, 1, 5, 'Is business plan for applied licence/s enclosed?');
INSERT INTO CHECKLISTS (WORKFLOW_PHASE_ID, CLIENT_INDUSTRY_ID, CLIENT_CATEGORY_ID, CHECKLIST_NUMBER, REQUIREMENT) VALUES (255, 17, 1, 6, 'Copy of Certificate of Incorporation/Registration Certificates or others (specify)');
INSERT INTO CHECKLISTS (WORKFLOW_PHASE_ID, CLIENT_INDUSTRY_ID, CLIENT_CATEGORY_ID, CHECKLIST_NUMBER, REQUIREMENT) VALUES (255, 17, 1, 7, 'Is/are original CR/12(s) provided with the following details; Names of shareholders, their addresses, their nationalities, shares held by each, names of directors and whether directors are nominees or not or whether non shareholder directors. ');
INSERT INTO CHECKLISTS (WORKFLOW_PHASE_ID, CLIENT_INDUSTRY_ID, CLIENT_CATEGORY_ID, CHECKLIST_NUMBER, REQUIREMENT) VALUES (255, 17, 1, 8, 'Copy of Certificate from CMA for listed companies');
INSERT INTO CHECKLISTS (WORKFLOW_PHASE_ID, CLIENT_INDUSTRY_ID, CLIENT_CATEGORY_ID, CHECKLIST_NUMBER, REQUIREMENT) VALUES (255, 17, 1, 9, 'Notarised Copy of Certificate of Incorporation for foreign company');
INSERT INTO CHECKLISTS (WORKFLOW_PHASE_ID, CLIENT_INDUSTRY_ID, CLIENT_CATEGORY_ID, CHECKLIST_NUMBER, REQUIREMENT) VALUES (255, 17, 1, 10,'Notarised Copy of Share Certificate for foreign company');
INSERT INTO CHECKLISTS (WORKFLOW_PHASE_ID, CLIENT_INDUSTRY_ID, CLIENT_CATEGORY_ID, CHECKLIST_NUMBER, REQUIREMENT) VALUES (255, 17, 1, 11, 'Copy of Personal Identification Number (PIN) card');
INSERT INTO CHECKLISTS (WORKFLOW_PHASE_ID, CLIENT_INDUSTRY_ID, CLIENT_CATEGORY_ID, CHECKLIST_NUMBER, REQUIREMENT) VALUES (255, 17, 1, 12, 'Copy of Valid Tax Compliance Certificate');
INSERT INTO CHECKLISTS (WORKFLOW_PHASE_ID, CLIENT_INDUSTRY_ID, CLIENT_CATEGORY_ID, CHECKLIST_NUMBER, REQUIREMENT) VALUES (255, 17, 1, 13, 'Copies of ID/passport for directors and shareholders');
INSERT INTO CHECKLISTS (WORKFLOW_PHASE_ID, CLIENT_INDUSTRY_ID, CLIENT_CATEGORY_ID, CHECKLIST_NUMBER, REQUIREMENT) VALUES (255, 17, 16, 14, 'Is a copy of Memorandum and Articles of Association of the Company.');
INSERT INTO CHECKLISTS (WORKFLOW_PHASE_ID, CLIENT_INDUSTRY_ID, CLIENT_CATEGORY_ID, CHECKLIST_NUMBER, REQUIREMENT) VALUES (255, 17, 17, 15, 'Is a copy of Cooperative Societys By-Laws.');
INSERT INTO CHECKLISTS (WORKFLOW_PHASE_ID, CLIENT_INDUSTRY_ID, CLIENT_CATEGORY_ID, CHECKLIST_NUMBER, REQUIREMENT) VALUES (255, 17, 13, 16, 'Is a copy of Partnership Deed.');
INSERT INTO CHECKLISTS (WORKFLOW_PHASE_ID, CLIENT_INDUSTRY_ID, CLIENT_CATEGORY_ID, CHECKLIST_NUMBER, REQUIREMENT) VALUES (255, 17, 11, 17, 'Is a copy of Constitution of the Society etc.');

INSERT INTO CHECKLISTS (WORKFLOW_PHASE_ID, CLIENT_INDUSTRY_ID, CLIENT_CATEGORY_ID, CHECKLIST_NUMBER, REQUIREMENT) VALUES (257, 17, 1, 1, 'Is a covering letter on applicant letterhead included?');
INSERT INTO CHECKLISTS (WORKFLOW_PHASE_ID, CLIENT_INDUSTRY_ID, CLIENT_CATEGORY_ID, CHECKLIST_NUMBER, REQUIREMENT) VALUES (257, 17, 1, 2, 'Is the application duly completed?');
INSERT INTO CHECKLISTS (WORKFLOW_PHASE_ID, CLIENT_INDUSTRY_ID, CLIENT_CATEGORY_ID, CHECKLIST_NUMBER, REQUIREMENT) VALUES (257, 17, 1, 3, 'Is the application signed, giving applicant’s name and designation?');
INSERT INTO CHECKLISTS (WORKFLOW_PHASE_ID, CLIENT_INDUSTRY_ID, CLIENT_CATEGORY_ID, CHECKLIST_NUMBER, REQUIREMENT) VALUES (257, 17, 1, 4, 'Is a letter from a Registered Technical Personnel included?');
INSERT INTO CHECKLISTS (WORKFLOW_PHASE_ID, CLIENT_INDUSTRY_ID, CLIENT_CATEGORY_ID, CHECKLIST_NUMBER, REQUIREMENT) VALUES (257, 17, 1, 5, 'Is business plan for applied licence/s enclosed?');
INSERT INTO CHECKLISTS (WORKFLOW_PHASE_ID, CLIENT_INDUSTRY_ID, CLIENT_CATEGORY_ID, CHECKLIST_NUMBER, REQUIREMENT) VALUES (257, 17, 1, 6, 'Copy of Certificate of Incorporation/Registration Certificates or others (specify)');
INSERT INTO CHECKLISTS (WORKFLOW_PHASE_ID, CLIENT_INDUSTRY_ID, CLIENT_CATEGORY_ID, CHECKLIST_NUMBER, REQUIREMENT) VALUES (257, 17, 1, 7, 'Is/are original CR/12(s) provided with the following details; Names of shareholders, their addresses, their nationalities, shares held by each, names of directors and whether directors are nominees or not or whether non shareholder directors. ');
INSERT INTO CHECKLISTS (WORKFLOW_PHASE_ID, CLIENT_INDUSTRY_ID, CLIENT_CATEGORY_ID, CHECKLIST_NUMBER, REQUIREMENT) VALUES (257, 17, 1, 8, 'Copy of Certificate from CMA for listed companies');
INSERT INTO CHECKLISTS (WORKFLOW_PHASE_ID, CLIENT_INDUSTRY_ID, CLIENT_CATEGORY_ID, CHECKLIST_NUMBER, REQUIREMENT) VALUES (257, 17, 1, 9, 'Notarised Copy of Certificate of Incorporation for foreign company');
INSERT INTO CHECKLISTS (WORKFLOW_PHASE_ID, CLIENT_INDUSTRY_ID, CLIENT_CATEGORY_ID, CHECKLIST_NUMBER, REQUIREMENT) VALUES (257, 17, 1, 10,'Notarised Copy of Share Certificate for foreign company');
INSERT INTO CHECKLISTS (WORKFLOW_PHASE_ID, CLIENT_INDUSTRY_ID, CLIENT_CATEGORY_ID, CHECKLIST_NUMBER, REQUIREMENT) VALUES (257, 17, 1, 11, 'Copy of Personal Identification Number (PIN) card');
INSERT INTO CHECKLISTS (WORKFLOW_PHASE_ID, CLIENT_INDUSTRY_ID, CLIENT_CATEGORY_ID, CHECKLIST_NUMBER, REQUIREMENT) VALUES (257, 17, 1, 12, 'Copy of Valid Tax Compliance Certificate');
INSERT INTO CHECKLISTS (WORKFLOW_PHASE_ID, CLIENT_INDUSTRY_ID, CLIENT_CATEGORY_ID, CHECKLIST_NUMBER, REQUIREMENT) VALUES (257, 17, 1, 13, 'Copies of ID/passport for directors and shareholders');
INSERT INTO CHECKLISTS (WORKFLOW_PHASE_ID, CLIENT_INDUSTRY_ID, CLIENT_CATEGORY_ID, CHECKLIST_NUMBER, REQUIREMENT) VALUES (257, 17, 16, 14, 'Is a copy of Memorandum and Articles of Association of the Company.');
INSERT INTO CHECKLISTS (WORKFLOW_PHASE_ID, CLIENT_INDUSTRY_ID, CLIENT_CATEGORY_ID, CHECKLIST_NUMBER, REQUIREMENT) VALUES (257, 17, 17, 15, 'Is a copy of Cooperative Societys By-Laws.');
INSERT INTO CHECKLISTS (WORKFLOW_PHASE_ID, CLIENT_INDUSTRY_ID, CLIENT_CATEGORY_ID, CHECKLIST_NUMBER, REQUIREMENT) VALUES (257, 17, 13, 16, 'Is a copy of Partnership Deed.');
INSERT INTO CHECKLISTS (WORKFLOW_PHASE_ID, CLIENT_INDUSTRY_ID, CLIENT_CATEGORY_ID, CHECKLIST_NUMBER, REQUIREMENT) VALUES (257, 17, 11, 17, 'Is a copy of Constitution of the Society etc.');

INSERT INTO CHECKLISTS (WORKFLOW_PHASE_ID, CLIENT_INDUSTRY_ID, CLIENT_CATEGORY_ID, CHECKLIST_NUMBER, REQUIREMENT) VALUES (258, 17, 1, 1, 'Is a covering letter on applicant letterhead included?');
INSERT INTO CHECKLISTS (WORKFLOW_PHASE_ID, CLIENT_INDUSTRY_ID, CLIENT_CATEGORY_ID, CHECKLIST_NUMBER, REQUIREMENT) VALUES (258, 17, 1, 2, 'Is the application duly completed?');
INSERT INTO CHECKLISTS (WORKFLOW_PHASE_ID, CLIENT_INDUSTRY_ID, CLIENT_CATEGORY_ID, CHECKLIST_NUMBER, REQUIREMENT) VALUES (258, 17, 1, 3, 'Is the application signed, giving applicant’s name and designation?');
INSERT INTO CHECKLISTS (WORKFLOW_PHASE_ID, CLIENT_INDUSTRY_ID, CLIENT_CATEGORY_ID, CHECKLIST_NUMBER, REQUIREMENT) VALUES (258, 17, 1, 4, 'Is a letter from a Registered Technical Personnel included?');
INSERT INTO CHECKLISTS (WORKFLOW_PHASE_ID, CLIENT_INDUSTRY_ID, CLIENT_CATEGORY_ID, CHECKLIST_NUMBER, REQUIREMENT) VALUES (258, 17, 1, 5, 'Is business plan for applied licence/s enclosed?');
INSERT INTO CHECKLISTS (WORKFLOW_PHASE_ID, CLIENT_INDUSTRY_ID, CLIENT_CATEGORY_ID, CHECKLIST_NUMBER, REQUIREMENT) VALUES (258, 17, 1, 6, 'Copy of Certificate of Incorporation/Registration Certificates or others (specify)');
INSERT INTO CHECKLISTS (WORKFLOW_PHASE_ID, CLIENT_INDUSTRY_ID, CLIENT_CATEGORY_ID, CHECKLIST_NUMBER, REQUIREMENT) VALUES (258, 17, 1, 7, 'Is/are original CR/12(s) provided with the following details; Names of shareholders, their addresses, their nationalities, shares held by each, names of directors and whether directors are nominees or not or whether non shareholder directors. ');
INSERT INTO CHECKLISTS (WORKFLOW_PHASE_ID, CLIENT_INDUSTRY_ID, CLIENT_CATEGORY_ID, CHECKLIST_NUMBER, REQUIREMENT) VALUES (258, 17, 1, 8, 'Copy of Certificate from CMA for listed companies');
INSERT INTO CHECKLISTS (WORKFLOW_PHASE_ID, CLIENT_INDUSTRY_ID, CLIENT_CATEGORY_ID, CHECKLIST_NUMBER, REQUIREMENT) VALUES (258, 17, 1, 9, 'Notarised Copy of Certificate of Incorporation for foreign company');
INSERT INTO CHECKLISTS (WORKFLOW_PHASE_ID, CLIENT_INDUSTRY_ID, CLIENT_CATEGORY_ID, CHECKLIST_NUMBER, REQUIREMENT) VALUES (258, 17, 1, 10,'Notarised Copy of Share Certificate for foreign company');
INSERT INTO CHECKLISTS (WORKFLOW_PHASE_ID, CLIENT_INDUSTRY_ID, CLIENT_CATEGORY_ID, CHECKLIST_NUMBER, REQUIREMENT) VALUES (258, 17, 1, 11, 'Copy of Personal Identification Number (PIN) card');
INSERT INTO CHECKLISTS (WORKFLOW_PHASE_ID, CLIENT_INDUSTRY_ID, CLIENT_CATEGORY_ID, CHECKLIST_NUMBER, REQUIREMENT) VALUES (258, 17, 1, 12, 'Copy of Valid Tax Compliance Certificate');
INSERT INTO CHECKLISTS (WORKFLOW_PHASE_ID, CLIENT_INDUSTRY_ID, CLIENT_CATEGORY_ID, CHECKLIST_NUMBER, REQUIREMENT) VALUES (258, 17, 1, 13, 'Copies of ID/passport for directors and shareholders');
INSERT INTO CHECKLISTS (WORKFLOW_PHASE_ID, CLIENT_INDUSTRY_ID, CLIENT_CATEGORY_ID, CHECKLIST_NUMBER, REQUIREMENT) VALUES (258, 17, 16, 14, 'Is a copy of Memorandum and Articles of Association of the Company.');
INSERT INTO CHECKLISTS (WORKFLOW_PHASE_ID, CLIENT_INDUSTRY_ID, CLIENT_CATEGORY_ID, CHECKLIST_NUMBER, REQUIREMENT) VALUES (258, 17, 17, 15, 'Is a copy of Cooperative Societys By-Laws.');
INSERT INTO CHECKLISTS (WORKFLOW_PHASE_ID, CLIENT_INDUSTRY_ID, CLIENT_CATEGORY_ID, CHECKLIST_NUMBER, REQUIREMENT) VALUES (258, 17, 13, 16, 'Is a copy of Partnership Deed.');
INSERT INTO CHECKLISTS (WORKFLOW_PHASE_ID, CLIENT_INDUSTRY_ID, CLIENT_CATEGORY_ID, CHECKLIST_NUMBER, REQUIREMENT) VALUES (258, 17, 11, 17, 'Is a copy of Constitution of the Society etc.');

INSERT INTO CHECKLISTS (WORKFLOW_PHASE_ID, CLIENT_INDUSTRY_ID, CLIENT_CATEGORY_ID, CHECKLIST_NUMBER, REQUIREMENT) VALUES (259, 17, 1, 1, 'The offer letter is sent to the applicant.');
INSERT INTO CHECKLISTS (WORKFLOW_PHASE_ID, CLIENT_INDUSTRY_ID, CLIENT_CATEGORY_ID, CHECKLIST_NUMBER, REQUIREMENT) VALUES (259, 17, 1, 2, 'The applicant has confirmed payment for the license.');

commit;

