delete from approval_checklists where checklist_id IN (SELECT checklist_id from checklists where workflow_phase_id = 248);
delete from checklists where workflow_phase_id = 248;
delete from approval_checklists where checklist_id IN (SELECT checklist_id from checklists where workflow_phase_id = 250);
delete from checklists where workflow_phase_id = 250;
delete from approval_checklists where checklist_id IN (SELECT checklist_id from checklists where workflow_phase_id = 251);
delete from checklists where workflow_phase_id = 251;
delete from approval_checklists where checklist_id IN (SELECT checklist_id from checklists where workflow_phase_id = 252); 
delete from checklists where workflow_phase_id = 252;
commit;

INSERT INTO CHECKLISTS (WORKFLOW_PHASE_ID, CLIENT_INDUSTRY_ID, CLIENT_CATEGORY_ID, CHECKLIST_NUMBER, REQUIREMENT) VALUES (248, 17, 1, 1, 'Is a covering letter by Applicant included?');
INSERT INTO CHECKLISTS (WORKFLOW_PHASE_ID, CLIENT_INDUSTRY_ID, CLIENT_CATEGORY_ID, CHECKLIST_NUMBER, REQUIREMENT) VALUES (248, 17, 1, 2, 'Is the application duly completed?');
INSERT INTO CHECKLISTS (WORKFLOW_PHASE_ID, CLIENT_INDUSTRY_ID, CLIENT_CATEGORY_ID, CHECKLIST_NUMBER, REQUIREMENT) VALUES (248, 17, 1, 3, 'Is the application signed, giving applicants name and date signed?');
INSERT INTO CHECKLISTS (WORKFLOW_PHASE_ID, CLIENT_INDUSTRY_ID, CLIENT_CATEGORY_ID, CHECKLIST_NUMBER, REQUIREMENT) VALUES (248, 17, 1, 4, 'Is application fee paid?');
INSERT INTO CHECKLISTS (WORKFLOW_PHASE_ID, CLIENT_INDUSTRY_ID, CLIENT_CATEGORY_ID, CHECKLIST_NUMBER, REQUIREMENT) VALUES (248, 17, 1, 5, 'Kenyan National Identity Cards (ID)');
INSERT INTO CHECKLISTS (WORKFLOW_PHASE_ID, CLIENT_INDUSTRY_ID, CLIENT_CATEGORY_ID, CHECKLIST_NUMBER, REQUIREMENT) VALUES (248, 17, 1, 6, 'PIN Card');
INSERT INTO CHECKLISTS (WORKFLOW_PHASE_ID, CLIENT_INDUSTRY_ID, CLIENT_CATEGORY_ID, CHECKLIST_NUMBER, REQUIREMENT) VALUES (248, 17, 1, 7, 'Academic Certificates (a copy of the KSCE (or its equivalent) certificate must be included)');
INSERT INTO CHECKLISTS (WORKFLOW_PHASE_ID, CLIENT_INDUSTRY_ID, CLIENT_CATEGORY_ID, CHECKLIST_NUMBER, REQUIREMENT) VALUES (248, 17, 1, 8, 'Technical Certificates and Testimonies');
INSERT INTO CHECKLISTS (WORKFLOW_PHASE_ID, CLIENT_INDUSTRY_ID, CLIENT_CATEGORY_ID, CHECKLIST_NUMBER, REQUIREMENT) VALUES (248, 17, 1, 9, 'Curriculum Vitae (CV)');


INSERT INTO CHECKLISTS (WORKFLOW_PHASE_ID, CLIENT_INDUSTRY_ID, CLIENT_CATEGORY_ID, CHECKLIST_NUMBER, REQUIREMENT) VALUES (250, 17, 1, 1, 'Is a covering letter by Applicant included?');
INSERT INTO CHECKLISTS (WORKFLOW_PHASE_ID, CLIENT_INDUSTRY_ID, CLIENT_CATEGORY_ID, CHECKLIST_NUMBER, REQUIREMENT) VALUES (250, 17, 1, 2, 'Is the application duly completed?');
INSERT INTO CHECKLISTS (WORKFLOW_PHASE_ID, CLIENT_INDUSTRY_ID, CLIENT_CATEGORY_ID, CHECKLIST_NUMBER, REQUIREMENT) VALUES (250, 17, 1, 3, 'Is the application signed, giving applicants name and date signed?');
INSERT INTO CHECKLISTS (WORKFLOW_PHASE_ID, CLIENT_INDUSTRY_ID, CLIENT_CATEGORY_ID, CHECKLIST_NUMBER, REQUIREMENT) VALUES (250, 17, 1, 4, 'Is application fee paid?');
INSERT INTO CHECKLISTS (WORKFLOW_PHASE_ID, CLIENT_INDUSTRY_ID, CLIENT_CATEGORY_ID, CHECKLIST_NUMBER, REQUIREMENT) VALUES (250, 17, 1, 5, 'Kenyan National Identity Cards (ID)');
INSERT INTO CHECKLISTS (WORKFLOW_PHASE_ID, CLIENT_INDUSTRY_ID, CLIENT_CATEGORY_ID, CHECKLIST_NUMBER, REQUIREMENT) VALUES (250, 17, 1, 6, 'PIN Card');
INSERT INTO CHECKLISTS (WORKFLOW_PHASE_ID, CLIENT_INDUSTRY_ID, CLIENT_CATEGORY_ID, CHECKLIST_NUMBER, REQUIREMENT) VALUES (250, 17, 1, 7, 'Academic Certificates (a copy of the KSCE (or its equivalent) certificate must be included)');
INSERT INTO CHECKLISTS (WORKFLOW_PHASE_ID, CLIENT_INDUSTRY_ID, CLIENT_CATEGORY_ID, CHECKLIST_NUMBER, REQUIREMENT) VALUES (250, 17, 1, 8, 'Technical Certificates and Testimonies');
INSERT INTO CHECKLISTS (WORKFLOW_PHASE_ID, CLIENT_INDUSTRY_ID, CLIENT_CATEGORY_ID, CHECKLIST_NUMBER, REQUIREMENT) VALUES (250, 17, 1, 9, 'Curriculum Vitae (CV)');


INSERT INTO CHECKLISTS (WORKFLOW_PHASE_ID, CLIENT_INDUSTRY_ID, CLIENT_CATEGORY_ID, CHECKLIST_NUMBER, REQUIREMENT) VALUES (251, 17, 1, 1, 'Is a covering letter by Applicant included?');
INSERT INTO CHECKLISTS (WORKFLOW_PHASE_ID, CLIENT_INDUSTRY_ID, CLIENT_CATEGORY_ID, CHECKLIST_NUMBER, REQUIREMENT) VALUES (251, 17, 1, 2, 'Is the application duly completed?');
INSERT INTO CHECKLISTS (WORKFLOW_PHASE_ID, CLIENT_INDUSTRY_ID, CLIENT_CATEGORY_ID, CHECKLIST_NUMBER, REQUIREMENT) VALUES (251, 17, 1, 3, 'Is the application signed, giving applicants name and date signed?');
INSERT INTO CHECKLISTS (WORKFLOW_PHASE_ID, CLIENT_INDUSTRY_ID, CLIENT_CATEGORY_ID, CHECKLIST_NUMBER, REQUIREMENT) VALUES (251, 17, 1, 4, 'Is application fee paid?');
INSERT INTO CHECKLISTS (WORKFLOW_PHASE_ID, CLIENT_INDUSTRY_ID, CLIENT_CATEGORY_ID, CHECKLIST_NUMBER, REQUIREMENT) VALUES (251, 17, 1, 5, 'Kenyan National Identity Cards (ID)');
INSERT INTO CHECKLISTS (WORKFLOW_PHASE_ID, CLIENT_INDUSTRY_ID, CLIENT_CATEGORY_ID, CHECKLIST_NUMBER, REQUIREMENT) VALUES (251, 17, 1, 6, 'PIN Card');
INSERT INTO CHECKLISTS (WORKFLOW_PHASE_ID, CLIENT_INDUSTRY_ID, CLIENT_CATEGORY_ID, CHECKLIST_NUMBER, REQUIREMENT) VALUES (251, 17, 1, 7, 'Academic Certificates (a copy of the KSCE (or its equivalent) certificate must be included)');
INSERT INTO CHECKLISTS (WORKFLOW_PHASE_ID, CLIENT_INDUSTRY_ID, CLIENT_CATEGORY_ID, CHECKLIST_NUMBER, REQUIREMENT) VALUES (251, 17, 1, 8, 'Technical Certificates and Testimonies');
INSERT INTO CHECKLISTS (WORKFLOW_PHASE_ID, CLIENT_INDUSTRY_ID, CLIENT_CATEGORY_ID, CHECKLIST_NUMBER, REQUIREMENT) VALUES (251, 17, 1, 9, 'Curriculum Vitae (CV)');


INSERT INTO CHECKLISTS (WORKFLOW_PHASE_ID, CLIENT_INDUSTRY_ID, CLIENT_CATEGORY_ID, CHECKLIST_NUMBER, REQUIREMENT) VALUES (252, 17, 1, 1, 'The offer letter is sent to the applicant.');
INSERT INTO CHECKLISTS (WORKFLOW_PHASE_ID, CLIENT_INDUSTRY_ID, CLIENT_CATEGORY_ID, CHECKLIST_NUMBER, REQUIREMENT) VALUES (252, 17, 1, 2, 'The applicant has confirmed payment for the license.');

commit;

INSERT INTO CHECKLISTS (WORKFLOW_PHASE_ID, CLIENT_INDUSTRY_ID, CLIENT_CATEGORY_ID, CHECKLIST_NUMBER, REQUIREMENT)
SELECT 624, CLIENT_INDUSTRY_ID, CLIENT_CATEGORY_ID, CHECKLIST_NUMBER, REQUIREMENT
FROM CHECKLISTS
WHERE (WORKFLOW_PHASE_ID = 621);
commit;




