
CREATE TABLE dells (
	dell_id			serial primary key,
	dell_type		integer,
	dell_location	varchar(120),
	dell_sn			varchar(50)
);

INSERT INTO dells (dell_type, dell_location, dell_sn) VALUES (1, 'ACACIA SAFARIS', 'JPHQ95J');
INSERT INTO dells (dell_type, dell_location, dell_sn) VALUES (1, 'AFRICA POINT', '4QHQ95J');
INSERT INTO dells (dell_type, dell_location, dell_sn) VALUES (1, 'AFRICAN TOUCH SAFARIS', 'C98W95J');
INSERT INTO dells (dell_type, dell_location, dell_sn) VALUES (1, 'AFRICAN TOUCH SAFARIS', '386W95J');
INSERT INTO dells (dell_type, dell_location, dell_sn) VALUES (1, 'AFRICAN TROPICAL SAFARIS', '8G8W95J');
INSERT INTO dells (dell_type, dell_location, dell_sn) VALUES (1, 'AFRICAN TROPICAL SAFARIS', '236W95J');
INSERT INTO dells (dell_type, dell_location, dell_sn) VALUES (1, 'AIR MASTERS LTD', 'J88W95J');
INSERT INTO dells (dell_type, dell_location, dell_sn) VALUES (1, 'AKARIM AGENCIES-KICC', '4B8W95J');
INSERT INTO dells (dell_type, dell_location, dell_sn) VALUES (1, 'AMAZING TOURS & TRAVEL LTD', '6MHQ95J');
INSERT INTO dells (dell_type, dell_location, dell_sn) VALUES (1, 'AMAZING TOURS & TRAVEL LTD', 'F16W95J');
INSERT INTO dells (dell_type, dell_location, dell_sn) VALUES (1, 'AMAZING TOURS & TRAVEL LTD', '6H8W95J');
INSERT INTO dells (dell_type, dell_location, dell_sn) VALUES (1, 'AMEET TRAVEL & TOURS LTD', '906W95J');
INSERT INTO dells (dell_type, dell_location, dell_sn) VALUES (1, 'AMEET TRAVEL & TOURS LTD', '9J8W95J');
INSERT INTO dells (dell_type, dell_location, dell_sn) VALUES (1, 'BARBRA TRAVEL LTD', 'D76W95J');
INSERT INTO dells (dell_type, dell_location, dell_sn) VALUES (1, 'BARBRA TRAVEL LTD', '898W95J');
INSERT INTO dells (dell_type, dell_location, dell_sn) VALUES (1, 'BARBRA TRAVEL LTD', 'GPHQ95J');
INSERT INTO dells (dell_type, dell_location, dell_sn) VALUES (1, 'BASEL TRAVELS', '7G8W95J');
INSERT INTO dells (dell_type, dell_location, dell_sn) VALUES (1, 'BESTIMES TRAVEL & TOURS CO.LTD', 'FF8W95J');
INSERT INTO dells (dell_type, dell_location, dell_sn) VALUES (1, 'BOMA HOLIDAYS', 'FH8W95J');
INSERT INTO dells (dell_type, dell_location, dell_sn) VALUES (1, 'BOMA HOLIDAYS', '4K8W95J');
INSERT INTO dells (dell_type, dell_location, dell_sn) VALUES (1, 'BOMA HOLIDAYS', 'B36W95J');
INSERT INTO dells (dell_type, dell_location, dell_sn) VALUES (1, 'BOMA TRAVEL SERVICES', 'GJHQ95J');
INSERT INTO dells (dell_type, dell_location, dell_sn) VALUES (1, 'BOMA TRAVEL SERVICES', '166W95J');
INSERT INTO dells (dell_type, dell_location, dell_sn) VALUES (1, 'BOMA TRAVEL SERVICES', 'JG8W95J');
INSERT INTO dells (dell_type, dell_location, dell_sn) VALUES (1, 'BUNSONS WORLDBANK', 'CL8W95J');
INSERT INTO dells (dell_type, dell_location, dell_sn) VALUES (1, 'BRIDGING THE WORLD TRAVEL', 'HPHQ95J');
INSERT INTO dells (dell_type, dell_location, dell_sn) VALUES (1, 'BRIGHTWAYS TRAVEL', 'F76W95J');
INSERT INTO dells (dell_type, dell_location, dell_sn) VALUES (1, 'BRIGHTWAYS TRAVEL', '7MHQ95J');
INSERT INTO dells (dell_type, dell_location, dell_sn) VALUES (1, 'BRIGHTWAYS TRAVEL', '5QHQ95J');
INSERT INTO dells (dell_type, dell_location, dell_sn) VALUES (1, 'BRIGHTWAYS TRAVEL', 'D86W95J');
INSERT INTO dells (dell_type, dell_location, dell_sn) VALUES (1, 'BUSH BLAZERS', '5PHQ95J');
INSERT INTO dells (dell_type, dell_location, dell_sn) VALUES (1, 'CATALYST TRAVEL', '436W95J');
INSERT INTO dells (dell_type, dell_location, dell_sn) VALUES (1, 'CATALYST TRAVEL', '3B8W95J');
INSERT INTO dells (dell_type, dell_location, dell_sn) VALUES (1, 'CATALYST TRAVEL', 'CF8W95J');
INSERT INTO dells (dell_type, dell_location, dell_sn) VALUES (1, 'CATALYST TRAVEL', 'B88W95J');
INSERT INTO dells (dell_type, dell_location, dell_sn) VALUES (1, 'CHALATI', 'C56W95J');
INSERT INTO dells (dell_type, dell_location, dell_sn) VALUES (1, 'CHRONICLE TRAVEL', '8M8W95J');
INSERT INTO dells (dell_type, dell_location, dell_sn) VALUES (1, 'CHRONICLE TRAVEL', 'HG8W95J');
INSERT INTO dells (dell_type, dell_location, dell_sn) VALUES (1, 'CHRONICLE TRAVEL', '6B8W95J');
INSERT INTO dells (dell_type, dell_location, dell_sn) VALUES (1, 'CITY SCAPE', 'G78W95J');
INSERT INTO dells (dell_type, dell_location, dell_sn) VALUES (1, 'CLASSICAL TRAVEL & TOURS', '5Z5W95J');
INSERT INTO dells (dell_type, dell_location, dell_sn) VALUES (1, 'COTTS TRAVEL', '826W95J');
INSERT INTO dells (dell_type, dell_location, dell_sn) VALUES (1, 'COTTS TRAVEL', 'BK8W95J');
INSERT INTO dells (dell_type, dell_location, dell_sn) VALUES (1, 'COTTS TRAVEL', '7J8W95J');
INSERT INTO dells (dell_type, dell_location, dell_sn) VALUES (1, 'CRANE TRAVEL LTD', 'H78W95J');
INSERT INTO dells (dell_type, dell_location, dell_sn) VALUES (1, 'CRANE TRAVEL LTD', 'G86W95J');
INSERT INTO dells (dell_type, dell_location, dell_sn) VALUES (1, 'CROWN TOURS', '916W95J');
INSERT INTO dells (dell_type, dell_location, dell_sn) VALUES (1, 'CROWN TOURS', 'F66W95J');
INSERT INTO dells (dell_type, dell_location, dell_sn) VALUES (1, 'CROWN TOURS', '6C8W95J');
INSERT INTO dells (dell_type, dell_location, dell_sn) VALUES (1, 'DAYMU TRAVEL', '7D8W95J');
INSERT INTO dells (dell_type, dell_location, dell_sn) VALUES (1, 'DAYMU TRAVEL', '9NHQ95J');
INSERT INTO dells (dell_type, dell_location, dell_sn) VALUES (1, 'DEBONAIR TRAVEL', '5B8W95J');
INSERT INTO dells (dell_type, dell_location, dell_sn) VALUES (1, 'DEBONAIR TRAVEL', 'DNHQ95J');
INSERT INTO dells (dell_type, dell_location, dell_sn) VALUES (1, 'DISCOUNT TOURS AND TRAVEL', '288W95J');
INSERT INTO dells (dell_type, dell_location, dell_sn) VALUES (1, 'DODOWORLD TRAVEL', '8LHQ95J');
INSERT INTO dells (dell_type, dell_location, dell_sn) VALUES (1, 'DODOWORLD TRAVEL', '398W95J');
INSERT INTO dells (dell_type, dell_location, dell_sn) VALUES (1, 'EQUITORIAL TRAVELS LTD', '4NHQ95J');
INSERT INTO dells (dell_type, dell_location, dell_sn) VALUES (1, 'EQUITORIAL TRAVELS LTD', 'DG8W95J');
INSERT INTO dells (dell_type, dell_location, dell_sn) VALUES (1, 'EXPRESS TRAVEL-KAREN MAIN OFFICE', '988W95J');
INSERT INTO dells (dell_type, dell_location, dell_sn) VALUES (1, 'EXPRESS TRAVEL-KAREN MAIN OFFICE', '6KHQ95J');
INSERT INTO dells (dell_type, dell_location, dell_sn) VALUES (1, 'EXPRESS UNHCR OFFICE', '6PHQ95J');
INSERT INTO dells (dell_type, dell_location, dell_sn) VALUES (1, 'FLY AIR LTD', '416W95J');
INSERT INTO dells (dell_type, dell_location, dell_sn) VALUES (1, 'FLY AIR LTD', 'GF8W95J');
INSERT INTO dells (dell_type, dell_location, dell_sn) VALUES (1, 'FLY AIR LTD', '286W95J');
INSERT INTO dells (dell_type, dell_location, dell_sn) VALUES (1, 'FURAHA TRAVEL', '276W95J');
INSERT INTO dells (dell_type, dell_location, dell_sn) VALUES (1, 'GALILEO KENYA', 'JF8W95J');
INSERT INTO dells (dell_type, dell_location, dell_sn) VALUES (1, 'GALILEO KENYA', 'JH8W95J');
INSERT INTO dells (dell_type, dell_location, dell_sn) VALUES (1, 'GALILEO KENYA', '5NHQ95J');
INSERT INTO dells (dell_type, dell_location, dell_sn) VALUES (1, 'GALILEO KENYA', '1KHQ95J');
INSERT INTO dells (dell_type, dell_location, dell_sn) VALUES (1, 'GALILEO KENYA', '2F8W95J');
INSERT INTO dells (dell_type, dell_location, dell_sn) VALUES (1, 'GEORGE TOWN', '896W95J');
INSERT INTO dells (dell_type, dell_location, dell_sn) VALUES (1, 'GEORGE TOWN', 'HNHQ95J');
INSERT INTO dells (dell_type, dell_location, dell_sn) VALUES (1, 'GEORGE TOWN', '8PHQ95J');
INSERT INTO dells (dell_type, dell_location, dell_sn) VALUES (1, 'GLOBUS TOURS & TRAVEL', 'DQHQ95J');
INSERT INTO dells (dell_type, dell_location, dell_sn) VALUES (1, 'GLOBUS TOURS & TRAVEL', '646W95J');
INSERT INTO dells (dell_type, dell_location, dell_sn) VALUES (1, 'GLOBUS TOURS & TRAVEL', '146W95J');
INSERT INTO dells (dell_type, dell_location, dell_sn) VALUES (1, 'GOOD HOPE TRAVEL', 'C46W95J');
INSERT INTO dells (dell_type, dell_location, dell_sn) VALUES (1, 'GOOD HOPE TRAVEL', '7KHQ95J');
INSERT INTO dells (dell_type, dell_location, dell_sn) VALUES (1, 'GOODHOPE TRAVEL(CORPORATE)', 'D26W95J');
INSERT INTO dells (dell_type, dell_location, dell_sn) VALUES (1, 'GOODHOPE TRAVEL(CORPORATE)', 'G16W95J');
INSERT INTO dells (dell_type, dell_location, dell_sn) VALUES (1, 'GOODHOPE TRAVEL(CORPORATE)', 'H16W95J');
INSERT INTO dells (dell_type, dell_location, dell_sn) VALUES (1, 'GOODHOPE TRAVEL(CORPORATE)', 'CG8W95J');
INSERT INTO dells (dell_type, dell_location, dell_sn) VALUES (1, 'GOODHOPE TRAVEL(CORPORATE)', '456W95J');
INSERT INTO dells (dell_type, dell_location, dell_sn) VALUES (1, 'GOODHOPE TRAVEL(CORPORATE)', 'CLHQ95J');
INSERT INTO dells (dell_type, dell_location, dell_sn) VALUES (1, 'GOODHOPE TRAVEL(CORPORATE)', 'G66W95J');
INSERT INTO dells (dell_type, dell_location, dell_sn) VALUES (1, 'GOODHOPE TRAVEL(CORPORATE)', '6Z5W95J');
INSERT INTO dells (dell_type, dell_location, dell_sn) VALUES (1, 'GOODHOPE TRAVEL(CORPORATE)', '596W95J');
INSERT INTO dells (dell_type, dell_location, dell_sn) VALUES (1, 'GOODHOPE TRAVEL(CORPORATE)', 'JZ5W95J');
INSERT INTO dells (dell_type, dell_location, dell_sn) VALUES (1, 'GOODHOPE TRAVEL(CORPORATE)', 'JD8W95J');
INSERT INTO dells (dell_type, dell_location, dell_sn) VALUES (1, 'GOODHOPE TRAVEL(CORPORATE) TOWN BRANCH', '7NHQ95J');
INSERT INTO dells (dell_type, dell_location, dell_sn) VALUES (1, 'GOODHOPE TRAVEL(CORPORATE) STRATHMORE', 'GD8W95J');
INSERT INTO dells (dell_type, dell_location, dell_sn) VALUES (1, 'GOING PLACES LTD', 'F06W95J');
INSERT INTO dells (dell_type, dell_location, dell_sn) VALUES (1, 'GOING PLACES LTD', 'BPHQ95J');
INSERT INTO dells (dell_type, dell_location, dell_sn) VALUES (1, 'GOING PLACES LTD', '4M8W95J');
INSERT INTO dells (dell_type, dell_location, dell_sn) VALUES (1, 'GREATTIMES TRAVEL', '966W95J');
INSERT INTO dells (dell_type, dell_location, dell_sn) VALUES (1, 'GREATTIMES TRAVEL', 'FC8W95J');
INSERT INTO dells (dell_type, dell_location, dell_sn) VALUES (1, 'HABAHABA TRAVEL', '878W95J');
INSERT INTO dells (dell_type, dell_location, dell_sn) VALUES (1, 'HIGHLIGHT UN', 'J78W95J');
INSERT INTO dells (dell_type, dell_location, dell_sn) VALUES (1, 'HIGHLIGHT UN', '9MHQ95J');
INSERT INTO dells (dell_type, dell_location, dell_sn) VALUES (1, 'IMPERIAL AIR SERVICES LTD', '4L8W95J');
INSERT INTO dells (dell_type, dell_location, dell_sn) VALUES (1, 'IMPERIAL AIR SERVICES LTD', 'HJHQ95J');
INSERT INTO dells (dell_type, dell_location, dell_sn) VALUES (1, 'INCENTIVE TRAVEL', 'CK8W95J');
INSERT INTO dells (dell_type, dell_location, dell_sn) VALUES (1, 'INCENTIVE TRAVEL', 'F56W95J');
INSERT INTO dells (dell_type, dell_location, dell_sn) VALUES (1, 'INCENTIVE TRAVEL', '9G8W95J');
INSERT INTO dells (dell_type, dell_location, dell_sn) VALUES (1, 'INTRA OCEANIC', 'G98W95J');
INSERT INTO dells (dell_type, dell_location, dell_sn) VALUES (1, 'INTRA OCEANIC', '726W95J');
INSERT INTO dells (dell_type, dell_location, dell_sn) VALUES (1, 'INTRA OCEANIC', '778W95J');
INSERT INTO dells (dell_type, dell_location, dell_sn) VALUES (1, 'JUBA/HILAL TRAVEL AGENCY', '8L8W95J');
INSERT INTO dells (dell_type, dell_location, dell_sn) VALUES (1, 'JUDETTE TRAVEL', 'D88W95J');
INSERT INTO dells (dell_type, dell_location, dell_sn) VALUES (1, 'JUDETTE TRAVEL', '406W95J');
INSERT INTO dells (dell_type, dell_location, dell_sn) VALUES (1, 'KAMBO TOURS & TRAVEL', '2B8W95J');
INSERT INTO dells (dell_type, dell_location, dell_sn) VALUES (1, 'KAMBO TOURS & TRAVEL', '1LHQ95J');
INSERT INTO dells (dell_type, dell_location, dell_sn) VALUES (1, 'KAMBO TOURS & TRAVEL', 'J66W95J');
INSERT INTO dells (dell_type, dell_location, dell_sn) VALUES (1, 'KATE FREIGHT & TRAVEL', '7C8W95J');
INSERT INTO dells (dell_type, dell_location, dell_sn) VALUES (1, 'KATE FREIGHT & TRAVEL', '936W95J');
INSERT INTO dells (dell_type, dell_location, dell_sn) VALUES (1, 'KARIBU TRAVEL', 'HK8W95J');
INSERT INTO dells (dell_type, dell_location, dell_sn) VALUES (1, 'KENYA CHINA TRAVEL & TOURS', '198W95J');
INSERT INTO dells (dell_type, dell_location, dell_sn) VALUES (1, 'KENYA CHINA TRAVEL & TOURS', 'GNHQ95J');
INSERT INTO dells (dell_type, dell_location, dell_sn) VALUES (1, 'KENT TOURS', '2QHQ95J');
INSERT INTO dells (dell_type, dell_location, dell_sn) VALUES (1, 'LONGROCK', '3NHQ95J');
INSERT INTO dells (dell_type, dell_location, dell_sn) VALUES (1, 'LOOKOUT TRAVEL', '3QHQ95J');
INSERT INTO dells (dell_type, dell_location, dell_sn) VALUES (1, 'LONG REN/BAMBOO HUT', 'DPHQ95J');
INSERT INTO dells (dell_type, dell_location, dell_sn) VALUES (1, 'MANIAGO TRAVEL & CRUISE', '8NHQ95J');
INSERT INTO dells (dell_type, dell_location, dell_sn) VALUES (1, 'MANIAGO TRAVEL & CRUISE', '206W95J');
INSERT INTO dells (dell_type, dell_location, dell_sn) VALUES (1, 'MASAABA TRAVEL', 'DMHQ95J');
INSERT INTO dells (dell_type, dell_location, dell_sn) VALUES (1, 'MASAABA TRAVEL', '3J8W95J');
INSERT INTO dells (dell_type, dell_location, dell_sn) VALUES (1, 'MASAABA TRAVEL', 'F26W95J');
INSERT INTO dells (dell_type, dell_location, dell_sn) VALUES (1, 'MIGHTY TOURS AND TRAVEL', '4KHQ95J');
INSERT INTO dells (dell_type, dell_location, dell_sn) VALUES (1, 'MIGHTY TOURS AND TRAVEL', 'H76W95J');
INSERT INTO dells (dell_type, dell_location, dell_sn) VALUES (1, 'MIGHTY TOURS AND TRAVEL', '376W95J');
INSERT INTO dells (dell_type, dell_location, dell_sn) VALUES (1, 'MIGHTY TOURS AND TRAVEL', 'CNHQ95J');
INSERT INTO dells (dell_type, dell_location, dell_sn) VALUES (1, 'MILES AND BEYOND', 'CC8W95J');
INSERT INTO dells (dell_type, dell_location, dell_sn) VALUES (1, 'MONCAL TRAVEL', '9LHQ95J');
INSERT INTO dells (dell_type, dell_location, dell_sn) VALUES (1, 'MUTHAIGA TRAVEL FVB', '296W95J');
INSERT INTO dells (dell_type, dell_location, dell_sn) VALUES (1, 'MUTHAIGA TRAVEL LTD', 'G26W95J');
INSERT INTO dells (dell_type, dell_location, dell_sn) VALUES (1, 'MUTHAIGA TRAVEL LTD', '5L8W95J');
INSERT INTO dells (dell_type, dell_location, dell_sn) VALUES (1, 'MUTHAIGA TRAVEL LTD', 'D06W95J');
INSERT INTO dells (dell_type, dell_location, dell_sn) VALUES (1, 'MUTHAIGA TRAVEL LTD', 'J26W95J');
INSERT INTO dells (dell_type, dell_location, dell_sn) VALUES (1, 'NORDIC TRAVEL/RED CARPET', '586W95J');
INSERT INTO dells (dell_type, dell_location, dell_sn) VALUES (1, 'NORDIC TRAVEL/RED CARPET', '1NHQ95J');
INSERT INTO dells (dell_type, dell_location, dell_sn) VALUES (1, 'NORTH & SOUTH TRAVEL LTD', 'BJ8W95J');
INSERT INTO dells (dell_type, dell_location, dell_sn) VALUES (1, 'NORTH & SOUTH TRAVEL LTD', 'FZ5W95J');
INSERT INTO dells (dell_type, dell_location, dell_sn) VALUES (1, 'NORTH & SOUTH TRAVEL LTD', '336W95J');
INSERT INTO dells (dell_type, dell_location, dell_sn) VALUES (1, 'NORTHLINE ICRC', '7M8W95J');
INSERT INTO dells (dell_type, dell_location, dell_sn) VALUES (1, 'NORTHLINE ICRC', '978W95J');
INSERT INTO dells (dell_type, dell_location, dell_sn) VALUES (1, 'NORTHLINE TRAVEL TOWN', '9K8W95J');
INSERT INTO dells (dell_type, dell_location, dell_sn) VALUES (1, 'PANTHER', 'HB8W95J');
INSERT INTO dells (dell_type, dell_location, dell_sn) VALUES (1, 'PARGO TOURS AND TRAVEL', 'HJ8W95J');
INSERT INTO dells (dell_type, dell_location, dell_sn) VALUES (1, 'PINACCLE', '946W95J');
INSERT INTO dells (dell_type, dell_location, dell_sn) VALUES (1, 'PINACCLE', 'GH8W95J');
INSERT INTO dells (dell_type, dell_location, dell_sn) VALUES (1, 'POPSY TOURS & TRAVEL', '786W95J');
INSERT INTO dells (dell_type, dell_location, dell_sn) VALUES (1, 'POLLMAN NBO', 'C78W95J');
INSERT INTO dells (dell_type, dell_location, dell_sn) VALUES (1, 'PREPS INTERNATIONAL', '7H8W95J');
INSERT INTO dells (dell_type, dell_location, dell_sn) VALUES (1, 'PREPS INTERNATIONAL', '6LHQ95J');
INSERT INTO dells (dell_type, dell_location, dell_sn) VALUES (1, 'RAJAIR TRAVEL LTD', 'CMHQ95J');
INSERT INTO dells (dell_type, dell_location, dell_sn) VALUES (1, 'RAYDOLL TRAVEL', '9M8W95J');
INSERT INTO dells (dell_type, dell_location, dell_sn) VALUES (1, 'RAYDOLL TRAVEL', 'BFBW95J');
INSERT INTO dells (dell_type, dell_location, dell_sn) VALUES (1, 'RICKSHAW TRAVEL', '4G8W95J');
INSERT INTO dells (dell_type, dell_location, dell_sn) VALUES (1, 'RICKSHAW TRAVEL', '9H8W95J');
INSERT INTO dells (dell_type, dell_location, dell_sn) VALUES (1, 'RICKSHAW TRAVEL', '5M8W95J');
INSERT INTO dells (dell_type, dell_location, dell_sn) VALUES (1, 'RICKSHAW TRAVEL', '3MHQ95J');
INSERT INTO dells (dell_type, dell_location, dell_sn) VALUES (1, 'RICKSHAW TRAVEL', 'CM8W95J');
INSERT INTO dells (dell_type, dell_location, dell_sn) VALUES (1, 'RICKSHAW TRAVEL', 'HH8W95J');
INSERT INTO dells (dell_type, dell_location, dell_sn) VALUES (1, 'RICKSHAW TRAVEL', 'FLHQ95J');
INSERT INTO dells (dell_type, dell_location, dell_sn) VALUES (1, 'RICKSHAW TRAVEL', 'JK8W95J');
INSERT INTO dells (dell_type, dell_location, dell_sn) VALUES (1, 'RICKSHAW TRAVEL', 'HLHQ95J');
INSERT INTO dells (dell_type, dell_location, dell_sn) VALUES (1, 'RICKSHAW TRAVEL', 'GG8W95J');
INSERT INTO dells (dell_type, dell_location, dell_sn) VALUES (1, 'RICKSHAW TRAVEL', '326W95J');
INSERT INTO dells (dell_type, dell_location, dell_sn) VALUES (1, 'ROEH TOURS', '676W95J');
INSERT INTO dells (dell_type, dell_location, dell_sn) VALUES (1, 'ROEH TOURS', 'H36W95J');
INSERT INTO dells (dell_type, dell_location, dell_sn) VALUES (1, 'ROSKAR TRAVEL LTD', '476W95J');
INSERT INTO dells (dell_type, dell_location, dell_sn) VALUES (1, 'ROSKAR TRAVEL LTD', '9F8W95J');
INSERT INTO dells (dell_type, dell_location, dell_sn) VALUES (1, 'ROSKAR TRAVEL LTD', '8Z5W95J');
INSERT INTO dells (dell_type, dell_location, dell_sn) VALUES (1, 'ROSKAR TRAVEL LTD', '6J8W95J');
INSERT INTO dells (dell_type, dell_location, dell_sn) VALUES (1, 'ROSKAR TRAVEL LTD', 'CKHQ95J');
INSERT INTO dells (dell_type, dell_location, dell_sn) VALUES (1, 'RUH TRAVEL', '346W95J');
INSERT INTO dells (dell_type, dell_location, dell_sn) VALUES (1, 'RUH TRAVEL', '716W95J');
INSERT INTO dells (dell_type, dell_location, dell_sn) VALUES (1, 'SABLE EXPRESS/SAFETY TRAVEL', '2L8W95J');
INSERT INTO dells (dell_type, dell_location, dell_sn) VALUES (1, 'SARANG TRAVEL', '1H8W95J');
INSERT INTO dells (dell_type, dell_location, dell_sn) VALUES (1, 'SARANG TRAVEL', 'BL8W95J');
INSERT INTO dells (dell_type, dell_location, dell_sn) VALUES (1, 'SATGURU UPPERHILL', '756W95J');
INSERT INTO dells (dell_type, dell_location, dell_sn) VALUES (1, 'SELAM TRAVEL', '5MHQ95J');
INSERT INTO dells (dell_type, dell_location, dell_sn) VALUES (1, 'SENATOR TRAVEL SERVICES LTD', '776W95J');
INSERT INTO dells (dell_type, dell_location, dell_sn) VALUES (1, 'SENATOR TRAVEL SERVICES LTD', '706W95J');
INSERT INTO dells (dell_type, dell_location, dell_sn) VALUES (1, 'SHAH TRAVEL', '696W95J');
INSERT INTO dells (dell_type, dell_location, dell_sn) VALUES (1, 'SHAH TRAVEL', '498W95J');
INSERT INTO dells (dell_type, dell_location, dell_sn) VALUES (1, 'SHIAN TRAVEL', '7L8W95J');
INSERT INTO dells (dell_type, dell_location, dell_sn) VALUES (1, 'SHOOR TRAVEL', '2C8W95J');
INSERT INTO dells (dell_type, dell_location, dell_sn) VALUES (1, 'SHOOR TRAVEL', 'H26W95J');
INSERT INTO dells (dell_type, dell_location, dell_sn) VALUES (1, 'SILVERBIRD JKIA', 'HMHQ95J');
INSERT INTO dells (dell_type, dell_location, dell_sn) VALUES (1, 'SILVERBIRD TRAVEL', '998W95J');
INSERT INTO dells (dell_type, dell_location, dell_sn) VALUES (1, 'SILVERBIRD TRAVEL', 'C26W95J');
INSERT INTO dells (dell_type, dell_location, dell_sn) VALUES (1, 'SIMOUN TRAVEL', '926W95J');
INSERT INTO dells (dell_type, dell_location, dell_sn) VALUES (1, 'SKYVIEW TRAVEL LTD', '106W95J');
INSERT INTO dells (dell_type, dell_location, dell_sn) VALUES (1, 'SOMAK TRAVEL', '488W95J');
INSERT INTO dells (dell_type, dell_location, dell_sn) VALUES (1, 'SOMAK TRAVEL', 'F88W95J');
INSERT INTO dells (dell_type, dell_location, dell_sn) VALUES (1, 'SOMAK TRAVEL', 'GB8W95J');
INSERT INTO dells (dell_type, dell_location, dell_sn) VALUES (1, 'SPEEDBIRD TRAVEL', '7F8W95J');
INSERT INTO dells (dell_type, dell_location, dell_sn) VALUES (1, 'STAR TRAVEL', 'DL8W95J');
INSERT INTO dells (dell_type, dell_location, dell_sn) VALUES (1, 'STAR TRAVEL', '3LHQ95J');
INSERT INTO dells (dell_type, dell_location, dell_sn) VALUES (1, 'TAIPAN VACATIONS', '506W95J');
INSERT INTO dells (dell_type, dell_location, dell_sn) VALUES (1, 'TAIPAN VACATIONS', 'GMHQ95J');
INSERT INTO dells (dell_type, dell_location, dell_sn) VALUES (1, 'TAMANA TRAVEL', 'JJ8W95J');
INSERT INTO dells (dell_type, dell_location, dell_sn) VALUES (1, 'TAMANA TRAVEL', 'FKHQ95J');
INSERT INTO dells (dell_type, dell_location, dell_sn) VALUES (1, 'TAMANA TRAVEL', 'BLHQ95J');
INSERT INTO dells (dell_type, dell_location, dell_sn) VALUES (1, 'TAMANA TRAVEL', 'FNHQ95J');
INSERT INTO dells (dell_type, dell_location, dell_sn) VALUES (1, 'TAMU SAFARIS', '196W95J');
INSERT INTO dells (dell_type, dell_location, dell_sn) VALUES (1, 'THE TICKET COMPANY', 'BM8W95J');
INSERT INTO dells (dell_type, dell_location, dell_sn) VALUES (1, 'THE TICKET COMPANY', 'JMHQ95J');
INSERT INTO dells (dell_type, dell_location, dell_sn) VALUES (1, 'THE TRAVEL HOUSE', 'G56W95J');
INSERT INTO dells (dell_type, dell_location, dell_sn) VALUES (1, 'THE TRAVEL MART LTD', 'DJHQ95J');
INSERT INTO dells (dell_type, dell_location, dell_sn) VALUES (1, 'THE TRAVEL MART LTD', '3PHQ95J');
INSERT INTO dells (dell_type, dell_location, dell_sn) VALUES (1, 'THE TRAVEL MART LTD', 'CPHQ95J');
INSERT INTO dells (dell_type, dell_location, dell_sn) VALUES (1, 'THE TRAVEL MART LTD', '2K8W95J');
INSERT INTO dells (dell_type, dell_location, dell_sn) VALUES (1, 'TOPDECK TRAVEL & TOURS', 'BH8W95J');
INSERT INTO dells (dell_type, dell_location, dell_sn) VALUES (1, 'TOPDECK TRAVEL & TOURS', 'DH8W95J');
INSERT INTO dells (dell_type, dell_location, dell_sn) VALUES (1, 'TOUR AFRICA SAFARIS', '1J8W95J');
INSERT INTO dells (dell_type, dell_location, dell_sn) VALUES (1, 'TOUR AFRICA SAFARIS', '656W95J');
INSERT INTO dells (dell_type, dell_location, dell_sn) VALUES (1, 'TRAVEL AFFAIRS LTD', 'FD8W95J');
INSERT INTO dells (dell_type, dell_location, dell_sn) VALUES (1, 'TRAVEL AFFAIRS LTD', 'DB8W95J');
INSERT INTO dells (dell_type, dell_location, dell_sn) VALUES (1, 'TRAVEL ASSOCIATES', 'JB8W95J');
INSERT INTO dells (dell_type, dell_location, dell_sn) VALUES (1, 'TRAVEL ASSOCIATES', 'BQHQ95J');
INSERT INTO dells (dell_type, dell_location, dell_sn) VALUES (1, 'TRAVEL ASSOCIATES', '746W95J');
INSERT INTO dells (dell_type, dell_location, dell_sn) VALUES (1, 'TRAVEL ASSOCIATES', '1PHQ95J');
INSERT INTO dells (dell_type, dell_location, dell_sn) VALUES (1, 'TRAVEL ASSOCIATES', 'J56W95J');
INSERT INTO dells (dell_type, dell_location, dell_sn) VALUES (1, 'TRAVEL CARE LTD', '796W95J');
INSERT INTO dells (dell_type, dell_location, dell_sn) VALUES (1, 'TRAVEL CARE LTD', '8F8W95J');
INSERT INTO dells (dell_type, dell_location, dell_sn) VALUES (1, 'TRAVEL CARE LTD', '6D8W95J');
INSERT INTO dells (dell_type, dell_location, dell_sn) VALUES (1, 'TRAVEL HIVE', '7K8W95J');
INSERT INTO dells (dell_type, dell_location, dell_sn) VALUES (1, 'TRAVEL PLAZA LTD', 'B76W95J');
INSERT INTO dells (dell_type, dell_location, dell_sn) VALUES (1, 'TRAVEL PLAZA LTD', '7Z5W95J');
INSERT INTO dells (dell_type, dell_location, dell_sn) VALUES (1, 'TRAVEL PLAZA LTD', '6QHQ95J');
INSERT INTO dells (dell_type, dell_location, dell_sn) VALUES (1, 'TRAVEL N STYLE PARLANDS', '2NHQ95J');
INSERT INTO dells (dell_type, dell_location, dell_sn) VALUES (1, 'TRAVEL N STYLE PARLANDS', 'DLHQ95J');
INSERT INTO dells (dell_type, dell_location, dell_sn) VALUES (1, 'TRAVEL N STYLE PARLANDS', '7LHQW95J');
INSERT INTO dells (dell_type, dell_location, dell_sn) VALUES (1, 'TRAVEL N STYLE PARLANDS', 'DJ8W95J');
INSERT INTO dells (dell_type, dell_location, dell_sn) VALUES (1, 'TRAVEL N STYLE PARLANDS', 'J76W95J');
INSERT INTO dells (dell_type, dell_location, dell_sn) VALUES (1, 'TRAVEL N STYLE PARLANDS', '396W95J');
INSERT INTO dells (dell_type, dell_location, dell_sn) VALUES (1, 'TRAVEL N STYLE PARLANDS', '888W95J');
INSERT INTO dells (dell_type, dell_location, dell_sn) VALUES (1, 'TRAVEL N STYLE PARLANDS', '9PHQ95J');
INSERT INTO dells (dell_type, dell_location, dell_sn) VALUES (1, 'TRAVEL N STYLE  SOUTH C', '176W95J');
INSERT INTO dells (dell_type, dell_location, dell_sn) VALUES (1, 'TRAVEL N STYLE  SOUTH C', '7QHQ95J');
INSERT INTO dells (dell_type, dell_location, dell_sn) VALUES (1, 'TRAVEL N STYLE  SOUTH C', '4MHQ95J');
INSERT INTO dells (dell_type, dell_location, dell_sn) VALUES (1, 'TRAVEL N STYLE  SOUTH C', '836W95J');
INSERT INTO dells (dell_type, dell_location, dell_sn) VALUES (1, 'TRAVEL N STYLE  SOUTH C', '2PHQ95J');
INSERT INTO dells (dell_type, dell_location, dell_sn) VALUES (1, 'TRAVEL N STYLE  SOUTH C', 'H06W95J');
INSERT INTO dells (dell_type, dell_location, dell_sn) VALUES (1, 'TRAVELLERS DEN', '4F8W95J');
INSERT INTO dells (dell_type, dell_location, dell_sn) VALUES (1, 'TRAVELLERS DEN', 'HZ5W95J');
INSERT INTO dells (dell_type, dell_location, dell_sn) VALUES (1, 'TRAVELLERS DEN', '886W95J');
INSERT INTO dells (dell_type, dell_location, dell_sn) VALUES (1, 'TRIPPLE TOURS TRAVEL', '188W95J');
INSERT INTO dells (dell_type, dell_location, dell_sn) VALUES (1, 'TRIPPLE TOURS TRAVEL', '2Z5W95J');
INSERT INTO dells (dell_type, dell_location, dell_sn) VALUES (1, 'TRIPPLE TOURS TRAVEL', 'C36W95J');
INSERT INTO dells (dell_type, dell_location, dell_sn) VALUES (1, 'TULIP TRAVEL', '366W95J');
INSERT INTO dells (dell_type, dell_location, dell_sn) VALUES (1, 'TULIP TRAVEL', '126W95J');
INSERT INTO dells (dell_type, dell_location, dell_sn) VALUES (1, 'TWIGA CAR HIRE & TOURS LTD', '2KHQ95J');
INSERT INTO dells (dell_type, dell_location, dell_sn) VALUES (1, 'TWIGA CAR HIRE & TOURS LTD', 'DM8W95J');
INSERT INTO dells (dell_type, dell_location, dell_sn) VALUES (1, 'TWIGA CAR HIRE & TOURS LTD', '4LHQ95J');
INSERT INTO dells (dell_type, dell_location, dell_sn) VALUES (1, 'TWIGA CAR HIRE & TOURS LTD', '8MHQ95J');
INSERT INTO dells (dell_type, dell_location, dell_sn) VALUES (1, 'TWIGA CAR HIRE & TOURS LTD', 'DK8W95J');
INSERT INTO dells (dell_type, dell_location, dell_sn) VALUES (1, 'TWIGA CAR HIRE & TOURS LTD', '3F8W95J');
INSERT INTO dells (dell_type, dell_location, dell_sn) VALUES (1, 'TWIGA CAR HIRE & TOURS LTD', 'BG8W95J');
INSERT INTO dells (dell_type, dell_location, dell_sn) VALUES (1, 'TWIGA GALLERIA ', 'DF8W95J');
INSERT INTO dells (dell_type, dell_location, dell_sn) VALUES (1, 'TWIGA GALLERIA', 'JNHQ95J');
INSERT INTO dells (dell_type, dell_location, dell_sn) VALUES (1, 'TWIN BUFFALOS SAFARIS & TRAVEL', '588W95J');
INSERT INTO dells (dell_type, dell_location, dell_sn) VALUES (1, 'VENTURE AFRICA', '5D8W95J');
INSERT INTO dells (dell_type, dell_location, dell_sn) VALUES (1, 'VENTURE AFRICA', '3L8W95J');
INSERT INTO dells (dell_type, dell_location, dell_sn) VALUES (1, 'VENTURE AFRICA', '4Z5W95J');
INSERT INTO dells (dell_type, dell_location, dell_sn) VALUES (1, 'AKARIM', 'DKHQ95J');
INSERT INTO dells (dell_type, dell_location, dell_sn) VALUES (1, 'AKARIM', '736W95J');
INSERT INTO dells (dell_type, dell_location, dell_sn) VALUES (1, 'AKARIM', '626W95J');
INSERT INTO dells (dell_type, dell_location, dell_sn) VALUES (1, 'AKARIM', 'CB8W95J');
INSERT INTO dells (dell_type, dell_location, dell_sn) VALUES (1, 'AKARIM', '616W95J');
INSERT INTO dells (dell_type, dell_location, dell_sn) VALUES (1, 'AKARIM KPA', '5J8W95J');
INSERT INTO dells (dell_type, dell_location, dell_sn) VALUES (1, 'AKARIM KPA', '116W95J');
INSERT INTO dells (dell_type, dell_location, dell_sn) VALUES (1, 'AKARIM KPA', '6L8W95J');
INSERT INTO dells (dell_type, dell_location, dell_sn) VALUES (1, 'BUNSON', '2G8W95J');
INSERT INTO dells (dell_type, dell_location, dell_sn) VALUES (1, 'BUNSON', '3G8W95J');
INSERT INTO dells (dell_type, dell_location, dell_sn) VALUES (1, 'BUNSON', '5C8W95J');
INSERT INTO dells (dell_type, dell_location, dell_sn) VALUES (1, 'BUNSON', 'HF8W95J');
INSERT INTO dells (dell_type, dell_location, dell_sn) VALUES (1, 'BOMA TRAVEL SERVICES', '4C8W95J');
INSERT INTO dells (dell_type, dell_location, dell_sn) VALUES (1, 'CHARLESTONE', '316W95J');
INSERT INTO dells (dell_type, dell_location, dell_sn) VALUES (1, 'CHARLESTONE(KPA)', 'DZ5W95J');
INSERT INTO dells (dell_type, dell_location, dell_sn) VALUES (1, 'EAGLE', '7PHQ95J');
INSERT INTO dells (dell_type, dell_location, dell_sn) VALUES (1, 'EAGLE', '5K8W95J');
INSERT INTO dells (dell_type, dell_location, dell_sn) VALUES (1, 'EAGLE', '788W95J');
INSERT INTO dells (dell_type, dell_location, dell_sn) VALUES (1, 'EAGLE', '8B8W95J');
INSERT INTO dells (dell_type, dell_location, dell_sn) VALUES (1, 'EXPRESS', '816W95J');
INSERT INTO dells (dell_type, dell_location, dell_sn) VALUES (1, 'EXPRESS', 'FG8W95J');
INSERT INTO dells (dell_type, dell_location, dell_sn) VALUES (1, 'EXPRESS', 'B98W95J');
INSERT INTO dells (dell_type, dell_location, dell_sn) VALUES (1, 'EXPRESS', '1F8W95J');
INSERT INTO dells (dell_type, dell_location, dell_sn) VALUES (1, 'EXPRESS', '3K8W95J');
INSERT INTO dells (dell_type, dell_location, dell_sn) VALUES (1, 'FOURWAYS', '226W95J');
INSERT INTO dells (dell_type, dell_location, dell_sn) VALUES (1, 'GOLDEN MBA', '576W95J');
INSERT INTO dells (dell_type, dell_location, dell_sn) VALUES (1, 'GOLDEN MBA', 'BJHQ95J');
INSERT INTO dells (dell_type, dell_location, dell_sn) VALUES (1, 'INTRA', '678W95J');
INSERT INTO dells (dell_type, dell_location, dell_sn) VALUES (1, 'IZZAT TRAVEL', 'JLHQW95J');
INSERT INTO dells (dell_type, dell_location, dell_sn) VALUES (1, 'KILINDINI TRAVEL KPA', '1G8W95J');
INSERT INTO dells (dell_type, dell_location, dell_sn) VALUES (1, 'KILINDINI TRAVEL KPA', 'CZ5W95J');
INSERT INTO dells (dell_type, dell_location, dell_sn) VALUES (1, 'MANTRA', '388W95J');
INSERT INTO dells (dell_type, dell_location, dell_sn) VALUES (1, 'MANTRA', 'J06W95J');
INSERT INTO dells (dell_type, dell_location, dell_sn) VALUES (1, 'NOOR', 'GJ8W95J');
INSERT INTO dells (dell_type, dell_location, dell_sn) VALUES (1, 'NOOR', '2MHQ95J');
INSERT INTO dells (dell_type, dell_location, dell_sn) VALUES (1, 'NOOR', '526W95J');
INSERT INTO dells (dell_type, dell_location, dell_sn) VALUES (1, 'NOOR', 'GKHQ95J');
INSERT INTO dells (dell_type, dell_location, dell_sn) VALUES (1, 'NORTHCOAST MYD', '5H8W95J');
INSERT INTO dells (dell_type, dell_location, dell_sn) VALUES (1, 'ORYX TRAVEL', 'G88W95J');
INSERT INTO dells (dell_type, dell_location, dell_sn) VALUES (1, 'POLLMANS', '9QHQ95J');
INSERT INTO dells (dell_type, dell_location, dell_sn) VALUES (1, 'POLLMANS', '2LHQ95J');
INSERT INTO dells (dell_type, dell_location, dell_sn) VALUES (1, 'POLLMANS', 'FPHQ95J');
INSERT INTO dells (dell_type, dell_location, dell_sn) VALUES (1, 'PRIME TIME', '8K8W95J');
INSERT INTO dells (dell_type, dell_location, dell_sn) VALUES (1, 'PRIME TIME', '1M8W95J');
INSERT INTO dells (dell_type, dell_location, dell_sn) VALUES (1, 'SHIMASY', '426W95J');
INSERT INTO dells (dell_type, dell_location, dell_sn) VALUES (1, 'SHIMASY', '9Z5W95J');
INSERT INTO dells (dell_type, dell_location, dell_sn) VALUES (1, 'SOMAK', 'B78W95J');
INSERT INTO dells (dell_type, dell_location, dell_sn) VALUES (1, 'UNIFORM', 'JL8W95J');
INSERT INTO dells (dell_type, dell_location, dell_sn) VALUES (1, 'UNIFORM', 'GC8W95J');
INSERT INTO dells (dell_type, dell_location, dell_sn) VALUES (1, 'UNIFORM', '766W95J');
INSERT INTO dells (dell_type, dell_location, dell_sn) VALUES (1, 'CHRONICLES KISUMU', 'JKHQW95J');
INSERT INTO dells (dell_type, dell_location, dell_sn) VALUES (1, 'PEL TRAVEL ', '1MHQ95J');
INSERT INTO dells (dell_type, dell_location, dell_sn) VALUES (1, 'PEL TRAVEL ', '9L8W95J');
INSERT INTO dells (dell_type, dell_location, dell_sn) VALUES (1, 'LAKE TRAVEL', 'D56W95J');
INSERT INTO dells (dell_type, dell_location, dell_sn) VALUES (1, 'LAKE TRAVEL', '8QHQ95J');
INSERT INTO dells (dell_type, dell_location, dell_sn) VALUES (1, 'SHIVA TRAVEL', '536W95J');
INSERT INTO dells (dell_type, dell_location, dell_sn) VALUES (1, 'SHIVA TRAVEL', 'GLHQ95J');
INSERT INTO dells (dell_type, dell_location, dell_sn) VALUES (1, 'TAMANA TRAVEL KISUMU', 'BNHQ95J');
INSERT INTO dells (dell_type, dell_location, dell_sn) VALUES (1, 'AFRICAN TOUCH SAFARIS KSM', '2J8W95J');
INSERT INTO dells (dell_type, dell_location, dell_sn) VALUES (1, 'AFRICAN TOUCH SAFARIS KSM', '8KHQ95J');
INSERT INTO dells (dell_type, dell_location, dell_sn) VALUES (1, 'AFRICAN TOUCH SAFARIS KSM', 'F28W95J');
INSERT INTO dells (dell_type, dell_location, dell_sn) VALUES (1, 'TAYLER TRAVEL', 'C76W95J');
INSERT INTO dells (dell_type, dell_location, dell_sn) VALUES (1, 'TAYLER TRAVEL', '4H8W95J');
INSERT INTO dells (dell_type, dell_location, dell_sn) VALUES (1, 'SELECT TRAVEL', '856W95J');
INSERT INTO dells (dell_type, dell_location, dell_sn) VALUES (1, 'CRATER TRAVEL', 'FJ8W95J');
INSERT INTO dells (dell_type, dell_location, dell_sn) VALUES (1, 'FAMOUS TRAVEL', '2H8W95J');
INSERT INTO dells (dell_type, dell_location, dell_sn) VALUES (1, 'SCOTT', '9C8W95J');
INSERT INTO dells (dell_type, dell_location, dell_sn) VALUES (1, 'SCOTT', 'JJHQ95J');
INSERT INTO dells (dell_type, dell_location, dell_sn) VALUES (1, 'HIGHLIGHT BCD', '3H8W95J');
INSERT INTO dells (dell_type, dell_location, dell_sn) VALUES (1, 'HIGHLIGHT BCD', '516W95J');
INSERT INTO dells (dell_type, dell_location, dell_sn) VALUES (1, 'SHIAN THIKA', 'FJHQ95J');
INSERT INTO dells (dell_type, dell_location, dell_sn) VALUES (1, 'SHIAN THIKA', 'GL8W95J');
INSERT INTO dells (dell_type, dell_location, dell_sn) VALUES (1, 'DewCIS Store', '8J8W95J');
INSERT INTO dells (dell_type, dell_location, dell_sn) VALUES (1, 'Warranty', 'JC8W95J');
INSERT INTO dells (dell_type, dell_location, dell_sn) VALUES (1, 'Warranty', '1QHQ95J');
INSERT INTO dells (dell_type, dell_location, dell_sn) VALUES (1, 'Warranty', '216W95J');
INSERT INTO dells (dell_type, dell_location, dell_sn) VALUES (1, 'Warranty', 'B26W95J');
INSERT INTO dells (dell_type, dell_location, dell_sn) VALUES (1, 'DewCIS Store', '986W95J');
INSERT INTO dells (dell_type, dell_location, dell_sn) VALUES (1, 'DewCIS Store', '636W95J');
INSERT INTO dells (dell_type, dell_location, dell_sn) VALUES (1, 'DewCIS Store', 'G76W95J');

INSERT INTO dells (dell_type, dell_location, dell_sn) VALUES (2, 'ACACIA SAFARIS', '4WQ56S1');
INSERT INTO dells (dell_type, dell_location, dell_sn) VALUES (2, 'AFRICAN TOUCH SAFARIS', '4WQ06S1');
INSERT INTO dells (dell_type, dell_location, dell_sn) VALUES (2, 'BOMA TRAVEL SERVICES', '4WP46S1');
INSERT INTO dells (dell_type, dell_location, dell_sn) VALUES (2, 'BUNSON CFC STANBIC', '4WM06S1');
INSERT INTO dells (dell_type, dell_location, dell_sn) VALUES (2, 'BUNSON TRAVEL PARKPLACE', '4WPV5S1');
INSERT INTO dells (dell_type, dell_location, dell_sn) VALUES (2, 'BUNSON TRAVEL PARKPLACE', '2DFV5S1');
INSERT INTO dells (dell_type, dell_location, dell_sn) VALUES (2, 'BUNSON TRAVEL PARKPLACE', '4WQC6S1');
INSERT INTO dells (dell_type, dell_location, dell_sn) VALUES (2, 'BUNSON TRAVEL PARKPLACE', '4WN66S1');
INSERT INTO dells (dell_type, dell_location, dell_sn) VALUES (2, 'BUNSON TRAVEL PARKPLACE', '2J7TMBX');
INSERT INTO dells (dell_type, dell_location, dell_sn) VALUES (2, 'BUNSON TRAVEL PARKPLACE', '4WMV5S1');
INSERT INTO dells (dell_type, dell_location, dell_sn) VALUES (2, 'BUNSON TRAVEL PARKPLACE', '4WQS5S1');
INSERT INTO dells (dell_type, dell_location, dell_sn) VALUES (2, 'BUNSON TRAVEL PARKPLACE', '4WMW5S1');
INSERT INTO dells (dell_type, dell_location, dell_sn) VALUES (2, 'BUNSON TRAVEL PARKPLACE', '4WQ46S1');
INSERT INTO dells (dell_type, dell_location, dell_sn) VALUES (2, 'BUNSON TRAVEL PARKPLACE', '4WM46S1');
INSERT INTO dells (dell_type, dell_location, dell_sn) VALUES (2, 'BUNSON TRAVEL PARKPLACE', '4WPT5S1');
INSERT INTO dells (dell_type, dell_location, dell_sn) VALUES (2, 'BUNSON VILLAGE MARKET', '4WNB6S1');
INSERT INTO dells (dell_type, dell_location, dell_sn) VALUES (2, 'BRIGHTWAYS TRAVEL', '2DDZ5S1');
INSERT INTO dells (dell_type, dell_location, dell_sn) VALUES (2, 'BRIGHTWAYS TRAVEL', '2DD36S1');
INSERT INTO dells (dell_type, dell_location, dell_sn) VALUES (2, 'CATALYST TRAVEL', '2DJ76S1');
INSERT INTO dells (dell_type, dell_location, dell_sn) VALUES (2, 'CHARLESTON TOWN', '4WPC6S1');
INSERT INTO dells (dell_type, dell_location, dell_sn) VALUES (2, 'CHARLESTON TRAVEL JKIA', '2DH06S1');
INSERT INTO dells (dell_type, dell_location, dell_sn) VALUES (2, 'CHRONICLE TRAVEL', '4WPW5S1');
INSERT INTO dells (dell_type, dell_location, dell_sn) VALUES (2, 'CHRONICLE TRAVEL', '4WQ76S1');
INSERT INTO dells (dell_type, dell_location, dell_sn) VALUES (2, 'DEBONAIR TRAVEL', '4WNC6S1');
INSERT INTO dells (dell_type, dell_location, dell_sn) VALUES (2, 'DISCOUNT TOURS AND TRAVEL', '4WNX5S1');
INSERT INTO dells (dell_type, dell_location, dell_sn) VALUES (2, 'EXPRESS TRAVEL-KAREN MAIN OFFICE', '4WM36S1');
INSERT INTO dells (dell_type, dell_location, dell_sn) VALUES (2, 'GALILEO KENYA', '4WNT5S1');
INSERT INTO dells (dell_type, dell_location, dell_sn) VALUES (2, 'GALILEO KENYA', '4WP76S1');
INSERT INTO dells (dell_type, dell_location, dell_sn) VALUES (2, 'GALILEO KENYA', '4WQ26S1');
INSERT INTO dells (dell_type, dell_location, dell_sn) VALUES (2, 'GALILEO KENYA', '2DCS5S1');
INSERT INTO dells (dell_type, dell_location, dell_sn) VALUES (2, 'GALILEO KENYA', '4WM96S1');
INSERT INTO dells (dell_type, dell_location, dell_sn) VALUES (2, 'GALILEO KENYA', '4WN16S1');
INSERT INTO dells (dell_type, dell_location, dell_sn) VALUES (2, 'GALILEO KENYA', '4WQR5S1');
INSERT INTO dells (dell_type, dell_location, dell_sn) VALUES (2, 'GALILEO KENYA', '4WQ86S1');
INSERT INTO dells (dell_type, dell_location, dell_sn) VALUES (2, 'GEORGE TOWN', '4WMX5S1');
INSERT INTO dells (dell_type, dell_location, dell_sn) VALUES (2, 'GEORGE TOWN', '4WNZ5S1');
INSERT INTO dells (dell_type, dell_location, dell_sn) VALUES (2, 'GOOD HOPE TRAVEL', '4WLY5S1');
INSERT INTO dells (dell_type, dell_location, dell_sn) VALUES (2, 'GOODHOPE TRAVEL(CORPORATE)', '4WP16S1');
INSERT INTO dells (dell_type, dell_location, dell_sn) VALUES (2, 'GOODHOPE TRAVEL(CORPORATE)', '4WMY5S1');
INSERT INTO dells (dell_type, dell_location, dell_sn) VALUES (2, 'GOODHOPE TRAVEL(CORPORATE)', '2DFS5S1');
INSERT INTO dells (dell_type, dell_location, dell_sn) VALUES (2, 'HANIF', '4WN96S1');
INSERT INTO dells (dell_type, dell_location, dell_sn) VALUES (2, 'INCENTIVE TRAVEL', '2DF46S1');
INSERT INTO dells (dell_type, dell_location, dell_sn) VALUES (2, 'LOOKOUT TRAVEL', '2DFC6S1');
INSERT INTO dells (dell_type, dell_location, dell_sn) VALUES (2, 'MONCAL TRAVEL', '4WM26S1');
INSERT INTO dells (dell_type, dell_location, dell_sn) VALUES (2, 'MUTHAIGA TRAVEL FVB', '4WP56S1');
INSERT INTO dells (dell_type, dell_location, dell_sn) VALUES (2, 'PANTHER', '2DJ56S1');
INSERT INTO dells (dell_type, dell_location, dell_sn) VALUES (2, 'PARGO TOURS AND TRAVEL', '2DGT5S1');
INSERT INTO dells (dell_type, dell_location, dell_sn) VALUES (2, 'RICKSHAW TRAVEL', '4WPR5S1');
INSERT INTO dells (dell_type, dell_location, dell_sn) VALUES (2, 'RICKSHAW TRAVEL', '4WM16S1');
INSERT INTO dells (dell_type, dell_location, dell_sn) VALUES (2, 'RICKSHAW TRAVEL', '4WPZ5S1');
INSERT INTO dells (dell_type, dell_location, dell_sn) VALUES (2, 'ROSKAR TRAVEL LTD', '2DDY5S1');
INSERT INTO dells (dell_type, dell_location, dell_sn) VALUES (2, 'ROSKAR TRAVEL LTD', '4WQ66S1');
INSERT INTO dells (dell_type, dell_location, dell_sn) VALUES (2, 'SENATOR TRAVEL SERVICES LTD', '4WP96S1');
INSERT INTO dells (dell_type, dell_location, dell_sn) VALUES (2, 'SHIAN TRAVEL UPPERHILL', '4WN46S1');
INSERT INTO dells (dell_type, dell_location, dell_sn) VALUES (2, 'SHIMASY NBO', '4WLZ5S1');
INSERT INTO dells (dell_type, dell_location, dell_sn) VALUES (2, 'SOMAK TRAVEL', '2DJV5S1');
INSERT INTO dells (dell_type, dell_location, dell_sn) VALUES (2, 'STAR TRAVEL', '2DDB6S1');
INSERT INTO dells (dell_type, dell_location, dell_sn) VALUES (2, 'TAIPAN VACATIONS', '2DDS5S1');
INSERT INTO dells (dell_type, dell_location, dell_sn) VALUES (2, 'TRAVEL ASSOCIATES', '4WM86S1');
INSERT INTO dells (dell_type, dell_location, dell_sn) VALUES (2, 'TRAVEL HIVE', '4WPS5S1');
INSERT INTO dells (dell_type, dell_location, dell_sn) VALUES (2, 'TRAVEL PLAZA LTD', '4WMC6S1');
INSERT INTO dells (dell_type, dell_location, dell_sn) VALUES (2, 'TRIPPLE TOURS TRAVEL', '2DJS5S1');
INSERT INTO dells (dell_type, dell_location, dell_sn) VALUES (2, 'BUNSON', '4WQ96S1');
INSERT INTO dells (dell_type, dell_location, dell_sn) VALUES (2, 'EAGLE', '4WMT5SI');
INSERT INTO dells (dell_type, dell_location, dell_sn) VALUES (2, 'EXPRESS', '4WP86S1');
INSERT INTO dells (dell_type, dell_location, dell_sn) VALUES (2, 'GALILEO MBA', '2DHX5S1');
INSERT INTO dells (dell_type, dell_location, dell_sn) VALUES (2, 'NOOR', '4WP06S1');
INSERT INTO dells (dell_type, dell_location, dell_sn) VALUES (2, 'REGAL TRAVEL', '4WNY5S1');
INSERT INTO dells (dell_type, dell_location, dell_sn) VALUES (2, 'ELGEYO TRAVEL', '4WQ16S1');
INSERT INTO dells (dell_type, dell_location, dell_sn) VALUES (2, 'AFRICAN TOUCH SAFARIS', '4WMB6S1');
INSERT INTO dells (dell_type, dell_location, dell_sn) VALUES (2, 'AFRICAN TOUCH SAFARIS KSM', '2DFZ5S1');
INSERT INTO dells (dell_type, dell_location, dell_sn) VALUES (2, 'BUNSON PARKPLACE', '4WNS5S1');
INSERT INTO dells (dell_type, dell_location, dell_sn) VALUES (2, 'KATA LAPTOP', '4WN56S1');
INSERT INTO dells (dell_type, dell_location, dell_sn) VALUES (2, 'WAS TO GO TO PALBINA BUT PUT ON HOLD', '4WQ36S1');
INSERT INTO dells (dell_type, dell_location, dell_sn) VALUES (2, 'New Laptop', '4WP26S1');
INSERT INTO dells (dell_type, dell_location, dell_sn) VALUES (2, 'Retreived from Bunson', '4WN76S1');
INSERT INTO dells (dell_type, dell_location, dell_sn) VALUES (2, 'GALILEO KYALO', '4WPB6S1');
INSERT INTO dells (dell_type, dell_location, dell_sn) VALUES (2, 'COMTEC STORE', '2DH56S1');
INSERT INTO dells (dell_type, dell_location, dell_sn) VALUES (2, 'COMTEC STORE', '4WMS5S1');
INSERT INTO dells (dell_type, dell_location, dell_sn) VALUES (2, 'COMTEC STORE', '4WPX5S1');
INSERT INTO dells (dell_type, dell_location, dell_sn) VALUES (2, 'COMTEC STORE', '2DG96S1');
INSERT INTO dells (dell_type, dell_location, dell_sn) VALUES (2, 'COMTEC STORE', '4WN26S1');
INSERT INTO dells (dell_type, dell_location, dell_sn) VALUES (2, 'COMTEC STORE', '2DF76S1');
INSERT INTO dells (dell_type, dell_location, dell_sn) VALUES (2, 'COMTEC STORE', '4WM66S1');
INSERT INTO dells (dell_type, dell_location, dell_sn) VALUES (2, 'COMTEC STORE', '4WN86S1');
INSERT INTO dells (dell_type, dell_location, dell_sn) VALUES (2, 'COMTEC STORE', '4WP66S1');
INSERT INTO dells (dell_type, dell_location, dell_sn) VALUES (2, 'COMTEC STORE', '4WN06S1');
INSERT INTO dells (dell_type, dell_location, dell_sn) VALUES (2, 'COMTEC STORE', '4WPY5S1');
INSERT INTO dells (dell_type, dell_location, dell_sn) VALUES (2, 'COMTEC STORE', '2DFY5S1');
INSERT INTO dells (dell_type, dell_location, dell_sn) VALUES (2, 'COMTEC STORE', '4WLX5S1');
INSERT INTO dells (dell_type, dell_location, dell_sn) VALUES (2, 'COMTEC STORE', '4WQB6S1');
INSERT INTO dells (dell_type, dell_location, dell_sn) VALUES (2, 'COMTEC STORE', '4WM56S1');
INSERT INTO dells (dell_type, dell_location, dell_sn) VALUES (2, 'COMTEC STORE', '4WP36S1');
INSERT INTO dells (dell_type, dell_location, dell_sn) VALUES (2, 'COMTEC STORE', '4WNW5S1');
INSERT INTO dells (dell_type, dell_location, dell_sn) VALUES (2, 'COMTEC STORE', '2DD76S1');

UPDATE dells SET dell_sn = trim(upper(dell_sn));


