
INSERT INTO headers (type, code, status, format, description) VALUES ('H', 'BFH01', 'M', 'S', 'File Header');
INSERT INTO headers (type, code, status, format, description) VALUES ('H', 'BCH02', 'M', 'S', 'Billing Analysis (Cycle) Header');
INSERT INTO headers (type, code, status, format, description) VALUES ('H', 'BOH03', 'M', 'S', 'Office Header (Reporting Agent)');
INSERT INTO headers (type, code, status, format, description) VALUES ('T', 'BKT06', 'M', 'S,X', 'Transaction Header');
INSERT INTO headers (type, code, status, format, description) VALUES ('T', 'BKS24', 'M', 'S,L,X', 'Ticket/Document Identification');
INSERT INTO headers (type, code, status, format, description) VALUES ('T', 'BKS30', 'M', 'S,L,X', 'STD/Document Amounts');
INSERT INTO headers (type, code, status, format, description) VALUES ('T', 'BKS39', 'M', 'S,L,X', 'Commission');
INSERT INTO headers (type, code, status, format, description) VALUES ('T', 'BKS42', 'C', 'S,X', 'Tax on Commission');
INSERT INTO headers (type, code, status, format, description) VALUES ('T', 'BKS45', 'C', 'S,X', 'Related Ticket/Document Information');
INSERT INTO headers (type, code, status, format, description) VALUES ('T', 'BKS46', 'C', 'X', 'Qualifying Issue Information for Sales Transactions');
INSERT INTO headers (type, code, status, format, description) VALUES ('T', 'BKI63', 'M', 'L,X', 'Itinerary Data Segment');
INSERT INTO headers (type, code, status, format, description) VALUES ('T', 'BAR64', 'M', 'X', 'Document Amounts');
INSERT INTO headers (type, code, status, format, description) VALUES ('T', 'BAR65', 'M', 'X', 'Additional Information - Passenger');
INSERT INTO headers (type, code, status, format, description) VALUES ('T', 'BAR66', 'M', 'X', 'Additional Information Form of Payment');
INSERT INTO headers (type, code, status, format, description) VALUES ('T', 'BMP70', 'C', 'X', 'Miscellaneous Document Information - Reason for Issuance');
INSERT INTO headers (type, code, status, format, description) VALUES ('T', 'BMP71', 'C', 'X', 'Miscellaneous Document - Additional Information');
INSERT INTO headers (type, code, status, format, description) VALUES ('T', 'BMP72', 'C', 'X', 'Miscellaneous Document Information - Amount in Letters');
INSERT INTO headers (type, code, status, format, description) VALUES ('T', 'BMP73', 'C', 'X', 'Optional Agency/Airline Information');
INSERT INTO headers (type, code, status, format, description) VALUES ('T', 'BMP74', 'C', 'X', 'Miscellaneous Document Information - Additional Print Lines');
INSERT INTO headers (type, code, status, format, description) VALUES ('T', 'BMD75', 'C', 'X', 'Electronic Miscellaneous Document Coupon Detail Record');
INSERT INTO headers (type, code, status, format, description) VALUES ('T', 'BMD76', 'C', 'X', 'Electronic Miscellaneous Document Remarks Record');
INSERT INTO headers (type, code, status, format, description) VALUES ('T', 'BMP77', 'C', 'X', 'Miscellaneous Coupon Information  Additional Print Lines');
INSERT INTO headers (type, code, status, format, description) VALUES ('T', 'BMP78', 'C', 'X', 'Automated Prepaid Ticket Advice Sponsor Information');
INSERT INTO headers (type, code, status, format, description) VALUES ('T', 'BKF81', 'C', 'X', 'Fare Calculation');
INSERT INTO headers (type, code, status, format, description) VALUES ('T', 'BKP83', 'C', 'S,L,X', 'Electronic Transaction');
INSERT INTO headers (type, code, status, format, description) VALUES ('T', 'BKP84', 'M', 'S,L,X', 'Form of Payment');
INSERT INTO headers (type, code, status, format, description) VALUES ('S', 'BOT93', 'M', 'S', 'Office Subtotals per Transaction Code and Currency Type');
INSERT INTO headers (type, code, status, format, description) VALUES ('S', 'BOT94', 'M', 'S', 'Office Totals per Currency Type');
INSERT INTO headers (type, code, status, format, description) VALUES ('S', 'BCT95', 'M', 'S', 'Billing Analysis (Cycle) Totals per Currency Type');
INSERT INTO headers (type, code, status, format, description) VALUES ('S', 'BFT99', 'M', 'S', 'File Totals per Currency Type');


INSERT INTO elements (el, format, description, glossary, status, element, pos) VALUES ('1', 'S', 'Standard Message Identifier', 'SMSG', 'M', '3 A', '1');
INSERT INTO elements (el, format, description, glossary, status, element, pos) VALUES ('2', 'S', 'Sequence Number', 'SQNR', 'M', '8 N', '4');
INSERT INTO elements (el, format, description, glossary, status, element, pos) VALUES ('3', 'S', 'Standard Numeric Qualifier', 'STNQ', 'M', '2 N', '12');
INSERT INTO elements (el, format, description, glossary, status, element, pos) VALUES ('4', 'S', 'BSP Identifier', 'BSPI', 'M', '3 AN', '14');
INSERT INTO elements (el, format, description, glossary, status, element, pos) VALUES ('5', 'S', 'Ticketing Airline Code Number', 'TACN', 'M', '5 AN', '17');
INSERT INTO elements (el, format, description, glossary, status, element, pos) VALUES ('6', 'S', 'Handbook Revision Number', 'REVN', 'M', '3 N', '22');
INSERT INTO elements (el, format, description, glossary, status, element, pos) VALUES ('7', 'S', 'Test/Production Status', 'TPST', 'M', '4 AN', '25');
INSERT INTO elements (el, format, description, glossary, status, element, pos) VALUES ('8', 'S', 'Processing Date', 'PRDA', 'M', '6 N', '29');
INSERT INTO elements (el, format, description, glossary, status, element, pos) VALUES ('9', 'S', 'Processing time', 'TIME', 'M', '4 N', '35');
INSERT INTO elements (el, format, description, glossary, status, element, pos) VALUES ('10', 'S', 'ISO Country Code', 'ISOC', 'M', '2 A', '39');
INSERT INTO elements (el, format, description, glossary, status, element, pos) VALUES ('11', 'S', 'File Sequence Number', 'FSQN', 'M', '6 N', '41');
INSERT INTO elements (el, format, description, glossary, status, element, pos) VALUES ('12', 'N', 'Reserved Space', 'RESD', 'M', '90 AN', '47');
UPDATE elements SET code = 'BFH01' WHERE code is null;

INSERT INTO elements (el, format, description, glossary, status, element, pos) VALUES ('1', 'S', 'Standard Message Identifier', 'SMSG', 'M', '  3 A', '1');
INSERT INTO elements (el, format, description, glossary, status, element, pos) VALUES ('2', 'S', 'Sequence Number', 'SQNR', 'M', '  8 N', '4');
INSERT INTO elements (el, format, description, glossary, status, element, pos) VALUES ('3', 'S', 'Standard Numeric Qualifier', 'STNQ', 'M', '  2 N', '12');
INSERT INTO elements (el, format, description, glossary, status, element, pos) VALUES ('4', 'S', 'Processing Date Identifier', 'PDAI', 'M', '  3 AN', '14');
INSERT INTO elements (el, format, description, glossary, status, element, pos) VALUES ('5', 'S', 'Processing Cycle Identifier', 'PCYC', 'M', '  1 N', '17');
INSERT INTO elements (el, format, description, glossary, status, element, pos) VALUES ('6', 'S', 'Billing Analysis Ending Date', 'BAED', 'M', '  6 N', '18');
INSERT INTO elements (el, format, description, glossary, status, element, pos) VALUES ('7', 'S', 'Dynamic Run Identifier', 'DYRI', 'M', '  1 AN', '24');
INSERT INTO elements (el, format, description, glossary, status, element, pos) VALUES ('8', 'S', 'HOT Reporting End Date', 'HRED', 'M', '  6 N', '25');
INSERT INTO elements (el, format, description, glossary, status, element, pos) VALUES ('9', 'N', 'Reserved Space', 'RESD', 'M', '106 AN', '31');
UPDATE elements SET code = 'BCH02' WHERE code is null;

INSERT INTO elements (el, format, description, glossary, status, element, pos) VALUES ('1', 'S', 'Standard Message Identifier', 'SMSG', 'M', ' 3 A', '1');
INSERT INTO elements (el, format, description, glossary, status, element, pos) VALUES ('2', 'S', 'Sequence Number', 'SQNR', 'M', ' 8 N', '4');
INSERT INTO elements (el, format, description, glossary, status, element, pos) VALUES ('3', 'S', 'Standard Numeric Qualifier', 'STNQ', 'M', ' 2 N', '12');
INSERT INTO elements (el, format, description, glossary, status, element, pos) VALUES ('4', 'S', 'Agent Numeric Code', 'AGTN', 'M', ' 8 N', '14');
INSERT INTO elements (el, format, description, glossary, status, element, pos) VALUES ('5', 'S', 'Remittance Period Ending Date', 'RMED', 'M', ' 6 N', '22');
INSERT INTO elements (el, format, description, glossary, status, element, pos) VALUES ('6', 'N', 'Reserved Space', 'RESD', 'M', '23 AN', '28');
INSERT INTO elements (el, format, description, glossary, status, element, pos) VALUES ('7', 'S', 'Currency Type', 'CUTP', 'M', ' 4 AN', '51');
INSERT INTO elements (el, format, description, glossary, status, element, pos) VALUES ('8', 'S', 'Multi-Location Identifier', 'MLOC', 'M', ' 3 AN', '55');
INSERT INTO elements (el, format, description, glossary, status, element, pos) VALUES ('9', 'S', 'Reserved Space', 'RESD', 'M', '79 AN', '58');
UPDATE elements SET code = 'BOH03' WHERE code is null;

INSERT INTO elements (el, format, description, glossary, status, element, pos) VALUES ('1', 'S', 'Standard Message Identifier', 'SMSG', 'M', ' 3 A', '1');
INSERT INTO elements (el, format, description, glossary, status, element, pos) VALUES ('2', 'S', 'Sequence Number', 'SQNR', 'M', ' 8 N', '4');
INSERT INTO elements (el, format, description, glossary, status, element, pos) VALUES ('3', 'S', 'Standard Numeric Qualifier', 'STNQ', 'M', ' 2 N', '12');
INSERT INTO elements (el, format, description, glossary, status, element, pos) VALUES ('4', 'S', 'Vendor ISO Country Code', 'VISO', 'C', ' 2 A', '14');
INSERT INTO elements (el, format, description, glossary, status, element, pos) VALUES ('5', 'S', 'Vendor Identification', 'VNID', 'C', ' 4 AN', '16');
INSERT INTO elements (el, format, description, glossary, status, element, pos) VALUES ('6', 'S', 'Transaction Number', 'TRNN', 'M', ' 6 N', '20');
INSERT INTO elements (el, format, description, glossary, status, element, pos) VALUES ('7', 'S', 'Transaction Reference Number', 'TREF', 'C', '18 AN', '26');
INSERT INTO elements (el, format, description, glossary, status, element, pos) VALUES ('8', 'S', 'Net Reporting Indicator', 'NRID', 'C', ' 2 AN', '44');
INSERT INTO elements (el, format, description, glossary, status, element, pos) VALUES ('9', 'S', 'Transaction Record Counter', 'TREC', 'M', ' 3 N', '46');
INSERT INTO elements (el, format, description, glossary, status, element, pos) VALUES ('10', 'S', 'Format Identifier', 'FORM', 'C', ' 1 AN', '49');
INSERT INTO elements (el, format, description, glossary, status, element, pos) VALUES ('11', 'S', 'Audit Status Indicator', 'AUDI', 'C', ' 1 AN', '50');
INSERT INTO elements (el, format, description, glossary, status, element, pos) VALUES ('12', 'S', 'Ticketing Airline Code Number', 'TACN', 'M', ' 5 AN', '51');
INSERT INTO elements (el, format, description, glossary, status, element, pos) VALUES ('13', 'S', 'Commercial Agreement Reference', 'CARF', 'C', '10 AN', '56');
INSERT INTO elements (el, format, description, glossary, status, element, pos) VALUES ('14', 'X', 'Customer File Reference', 'CSTF', 'C', '27 AN', '66');
INSERT INTO elements (el, format, description, glossary, status, element, pos) VALUES ('15', 'S', 'Client Identification', 'CLID', 'C', ' 8 AN', '93');
INSERT INTO elements (el, format, description, glossary, status, element, pos) VALUES ('16', 'S', 'Reporting System Identifier', 'RPSI', 'M', ' 4 AN', '101');
INSERT INTO elements (el, format, description, glossary, status, element, pos) VALUES ('17', 'S', 'Approved Location Numeric Code', 'ALNC', 'C', ' 8 N', '105');
INSERT INTO elements (el, format, description, glossary, status, element, pos) VALUES ('18', 'S', 'Approved Location Type', 'ALTP', 'C', ' 1 AN', '113');
INSERT INTO elements (el, format, description, glossary, status, element, pos) VALUES ('19', 'S', 'Approved Location Numeric Code', 'ALNC', 'C', ' 8 N', '114');
INSERT INTO elements (el, format, description, glossary, status, element, pos) VALUES ('20', 'S', 'Approved Location Type', 'ALTP', 'C', ' 1 AN', '122');
INSERT INTO elements (el, format, description, glossary, status, element, pos) VALUES ('21', 'S', 'Approved Location Numeric Code', 'ALNC', 'C', ' 8 N', '123');
INSERT INTO elements (el, format, description, glossary, status, element, pos) VALUES ('22', 'S', 'Approved Location Type', 'ALTP', 'C', ' 1 AN', '131');
INSERT INTO elements (el, format, description, glossary, status, element, pos) VALUES ('23', 'N', 'Data Input Status Indicator', 'DISI', 'C', ' 1 AN', '132');
INSERT INTO elements (el, format, description, glossary, status, element, pos) VALUES ('24', 'N', 'Reserved Space', 'RESD', 'M', ' 4 AN', '133');
UPDATE elements SET code = 'BKT06' WHERE code is null;

INSERT INTO elements (el, format, description, glossary, status, element, pos) VALUES ('1', 's', 'Standard Message Identifier   ', 'SMSG', 'M', '3 A', '1');
INSERT INTO elements (el, format, description, glossary, status, element, pos) VALUES ('2', 's', 'Sequence Number           ', 'SQNR', 'M', '8 N', '4');
INSERT INTO elements (el, format, description, glossary, status, element, pos) VALUES ('3', 's', 'Standard Numeric Qualifier     ', 'STNQ', 'M', '2 N', '12');
INSERT INTO elements (el, format, description, glossary, status, element, pos) VALUES ('4', 's', 'Date of Issue ', 'DAIS ', 'M', '6 N', '14');
INSERT INTO elements (el, format, description, glossary, status, element, pos) VALUES ('5', 's', 'Transaction Number      ', 'TRNN', 'M', '6 N', '20');
INSERT INTO elements (el, format, description, glossary, status, element, pos) VALUES ('6', 's', 'Ticket/Document Number             ', 'TDNR', 'M', '15 AN', '26');
INSERT INTO elements (el, format, description, glossary, status, element, pos) VALUES ('7', 's', 'Check Digit            ', 'CDGT', 'M', '1 N', '41');
INSERT INTO elements (el, format, description, glossary, status, element, pos) VALUES ('8', 'x', 'Transmission Control Number      ', 'TCNR', 'C', '15 AN', '42');
INSERT INTO elements (el, format, description, glossary, status, element, pos) VALUES ('9', 'x', 'Check-Digit                  ', 'TCND', 'C', '1 N', '57');
INSERT INTO elements (el, format, description, glossary, status, element, pos) VALUES ('10', 's', 'Coupon Use Indicator       ', 'CPUI', 'C', '4 AN', '58');
INSERT INTO elements (el, format, description, glossary, status, element, pos) VALUES ('11', 's', 'Conjunction Ticket Indicator    ', 'CJCP', 'C', '3 AN', '62');
INSERT INTO elements (el, format, description, glossary, status, element, pos) VALUES ('12', 's', 'Agent Numeric Code              ', 'AGTN', 'M', '8 N', '65');
INSERT INTO elements (el, format, description, glossary, status, element, pos) VALUES ('13', 'n', 'Reserved Space                 ', 'RESD', 'M', '5 AN', '73');
INSERT INTO elements (el, format, description, glossary, status, element, pos) VALUES ('14', 's', 'Tour Code                   ', 'TOUR', 'C', '15 AN', '78');
INSERT INTO elements (el, format, description, glossary, status, element, pos) VALUES ('15', 's', 'Transaction Code              ', 'TRNC', 'M', '4 AN', '93');
INSERT INTO elements (el, format, description, glossary, status, element, pos) VALUES ('16', 'x', 'True Origin/Destination City Codes', 'TODC', 'C', '14 AN', '97');
INSERT INTO elements (el, format, description, glossary, status, element, pos) VALUES ('17', 'n', 'Reserved Space                 ', 'RESD', 'M', '4 AN', '111');
INSERT INTO elements (el, format, description, glossary, status, element, pos) VALUES ('18', 'x', 'PNR Reference and/or Airline Data  ', 'PNRR', 'C', '13 AN', '115');
INSERT INTO elements (el, format, description, glossary, status, element, pos) VALUES ('19', 'n', 'Reserved Space                 ', 'RESD', 'M', '9 AN', '128');
UPDATE elements SET code = 'BKS24' WHERE code is null;

INSERT INTO elements (el, format, description, glossary, status, element, pos) VALUES ('1', 's', 'Standard Message Identifier', 'SMSG', 'M', '3A', '1');
INSERT INTO elements (el, format, description, glossary, status, element, pos) VALUES ('2', 's', 'Sequence Number', 'SQNR', 'M', '8N', '4');
INSERT INTO elements (el, format, description, glossary, status, element, pos) VALUES ('3', 's', 'Standard Numeric Qualifier', 'STNQ', 'M', '2N', '12');
INSERT INTO elements (el, format, description, glossary, status, element, pos) VALUES ('4', 's', 'Date of Issue        ', 'DAIS', 'M', '6N', '14');
INSERT INTO elements (el, format, description, glossary, status, element, pos) VALUES ('5', 's', 'Transaction Number', 'TRNN', 'M', '6N', '20');
INSERT INTO elements (el, format, description, glossary, status, element, pos) VALUES ('6', 's', 'Ticket/Document Number', 'TDNR', 'M', '15AN', '26');
INSERT INTO elements (el, format, description, glossary, status, element, pos) VALUES ('7', 's', 'Check-Digit', 'CDGT', 'M', '1N', '41');
INSERT INTO elements (el, format, description, glossary, status, element, pos) VALUES ('8', 's', 'Commissionable Amount ', 'COBL', 'M', '11N', '42');
INSERT INTO elements (el, format, description, glossary, status, element, pos) VALUES ('9', 's', ' Net Fare Amount ', 'NTFA', 'C', '11N', '53');
INSERT INTO elements (el, format, description, glossary, status, element, pos) VALUES ('10', 'N', 'Reserved Space ', 'RESD', 'M', '1AN', '64');
INSERT INTO elements (el, format, description, glossary, status, element, pos) VALUES ('11', 's', 'Tax/Miscellaneous Fee Type', 'TMFT', 'C', '8AN', '65');
INSERT INTO elements (el, format, description, glossary, status, element, pos) VALUES ('12', 's', 'Tax/Miscellaneous Fee Amount', 'TMFA', 'C', '11N', '73');
INSERT INTO elements (el, format, description, glossary, status, element, pos) VALUES ('13', 's', 'Tax/Miscellaneous Fee Type', 'TMFT', 'C', '8AN', '84');
INSERT INTO elements (el, format, description, glossary, status, element, pos) VALUES ('14', 's', 'Tax/Miscellaneous Fee Amount', 'TMFA', 'C', '11N', '92');
INSERT INTO elements (el, format, description, glossary, status, element, pos) VALUES ('15', 's', 'Ticket/Document Amount   ', 'TDAM', 'M', '11N', '103');
INSERT INTO elements (el, format, description, glossary, status, element, pos) VALUES ('16', 's', 'Late Reporting Penalty', 'LREP', 'C', '11N', '114');
INSERT INTO elements (el, format, description, glossary, status, element, pos) VALUES ('17', 'N', ' Reserved Space', 'RESD', 'M', '5AN', '125');
INSERT INTO elements (el, format, description, glossary, status, element, pos) VALUES ('18', 's', 'Currency Type ', 'CUTP', 'M', '41N', '130');
INSERT INTO elements (el, format, description, glossary, status, element, pos) VALUES ('19', 'N', 'Reserved Space', 'RESD', 'M', '3AN', '134');
UPDATE elements SET code = 'BKS30' WHERE code is null;

INSERT INTO elements (el, format, description, glossary, status, element, pos) VALUES ('1', 's', 'Standard Message Identifier', 'SMSG', 'M', ' 3 A', '1');
INSERT INTO elements (el, format, description, glossary, status, element, pos) VALUES ('2', 's', 'Sequence Number', 'SQNR', 'M', ' 8 N', '4');
INSERT INTO elements (el, format, description, glossary, status, element, pos) VALUES ('3', 's', 'Standard Numeric Qualifier', 'STNQ', 'M', ' 2 N', '12');
INSERT INTO elements (el, format, description, glossary, status, element, pos) VALUES ('4', 's', 'Date of Issue', 'DAIS', 'M', ' 6 N', '14');
INSERT INTO elements (el, format, description, glossary, status, element, pos) VALUES ('5', 's', 'Transaction Number', 'TRNN', 'M', ' 6 N', '20');
INSERT INTO elements (el, format, description, glossary, status, element, pos) VALUES ('6', 's', 'Ticket/Document Number', 'TDNR', 'M', '15 AN', '26');
INSERT INTO elements (el, format, description, glossary, status, element, pos) VALUES ('7', 's', 'Check-Digit', 'CDGT', 'M', ' 1 N', '41');
INSERT INTO elements (el, format, description, glossary, status, element, pos) VALUES ('8', 's', 'Statistical Code', 'STAT', 'C', ' 3 AN', '42');
INSERT INTO elements (el, format, description, glossary, status, element, pos) VALUES ('9', 's', 'Commission Type', 'COTP', 'C', ' 6 AN', '45');
INSERT INTO elements (el, format, description, glossary, status, element, pos) VALUES ('10', 's', 'Commission Rate', 'CORT', 'M', ' 5 N', '51');
INSERT INTO elements (el, format, description, glossary, status, element, pos) VALUES ('11', 's', 'Commission Amount', 'COAM', 'M', '11 N', '56');
INSERT INTO elements (el, format, description, glossary, status, element, pos) VALUES ('12', 's', 'Supplementary Type', 'SPTP', 'C', ' 6 AN', '67');
INSERT INTO elements (el, format, description, glossary, status, element, pos) VALUES ('13', 's', 'Supplementary Rate', 'SPRT', 'C', ' 5 N', '73');
INSERT INTO elements (el, format, description, glossary, status, element, pos) VALUES ('14', 's', 'Supplementary Amount', 'SPAM', 'C', '11 N', '78');
INSERT INTO elements (el, format, description, glossary, status, element, pos) VALUES ('15', 's', 'Effective Commission Rate', 'EFRT', 'M', ' 5 N', '89');
INSERT INTO elements (el, format, description, glossary, status, element, pos) VALUES ('16', 's', 'Effective Commission Amount', 'EFCO', 'M', '11 N', '94');
INSERT INTO elements (el, format, description, glossary, status, element, pos) VALUES ('17', 's', 'Amount Paid by Customer', 'APBC', 'C', '11 N', '105');
INSERT INTO elements (el, format, description, glossary, status, element, pos) VALUES ('18', 'n', 'Reserved Space', 'RESD', 'M', '14 AN', '116');
INSERT INTO elements (el, format, description, glossary, status, element, pos) VALUES ('19', 's', 'Currency Type', 'CUTP', 'M', ' 4 AN', '130');
INSERT INTO elements (el, format, description, glossary, status, element, pos) VALUES ('20', 'n', 'Reserved Space', 'RESD', 'M', ' 3 AN', '134');
UPDATE elements SET code = 'BKS39' WHERE code is null;

INSERT INTO elements (el, format, description, glossary, status, element, pos) VALUES ('1', 'S', 'Standard Message Identifier', 'SMSG', 'M', ' 3A', '1');
INSERT INTO elements (el, format, description, glossary, status, element, pos) VALUES ('2', 'S', 'Sequence Number', 'SQNR', 'M', ' 8N', '4');
INSERT INTO elements (el, format, description, glossary, status, element, pos) VALUES ('3', 'S', 'Standard Numeric Qualifier', 'STNQ', 'M', ' 2N', '12');
INSERT INTO elements (el, format, description, glossary, status, element, pos) VALUES ('4', 'S', 'Remittance Period Ending Date', 'RMED', 'M', ' 6N', '14');
INSERT INTO elements (el, format, description, glossary, status, element, pos) VALUES ('5', 'S', 'Transaction Number', 'TRNN', 'M', ' 6N', '20');
INSERT INTO elements (el, format, description, glossary, status, element, pos) VALUES ('6', 'S', 'Related Ticket/ Document Number', 'RTDN', 'M', '15 AN', '26');
INSERT INTO elements (el, format, description, glossary, status, element, pos) VALUES ('7', 'S', 'Check-Digit', 'CDGT', 'M', ' 1N', '41');
INSERT INTO elements (el, format, description, glossary, status, element, pos) VALUES ('8', 'S', 'Waiver Code', 'WAVR', 'C', '14 AN', '42');
INSERT INTO elements (el, format, description, glossary, status, element, pos) VALUES ('9', 'S', 'Reason for Memo Issuance Code', 'RMIC', 'C', '5 AN', '56');
INSERT INTO elements (el, format, description, glossary, status, element, pos) VALUES ('10', 'n', 'Reserved Space', 'RESD', 'M', '47 AN', '61');
INSERT INTO elements (el, format, description, glossary, status, element, pos) VALUES ('11', 'S', 'Related Ticket/Document Coupon Number Identifier', 'RCPN', 'C', '4N', '108');
INSERT INTO elements (el, format, description, glossary, status, element, pos) VALUES ('12', 'n', 'Reserved Space', 'RESD', 'M', '16 AN', '112');
INSERT INTO elements (el, format, description, glossary, status, element, pos) VALUES ('13', 'S', 'Date of Issue Related Document', 'DIRD', 'C', '6 N', '128');
INSERT INTO elements (el, format, description, glossary, status, element, pos) VALUES ('14', 'n', 'Reserved Space', 'RESD', 'M', '3 AN', '134');
UPDATE elements SET code = 'BKS45' WHERE code is null;

INSERT INTO elements (el, format, description, glossary, status, element, pos) VALUES ('1', 'X', 'Standard Message Identifier', 'SMSG', 'M', '3 A', '1');
INSERT INTO elements (el, format, description, glossary, status, element, pos) VALUES ('2', 'X', 'Sequence Number', 'SQNR', 'M', '8 N', '4');
INSERT INTO elements (el, format, description, glossary, status, element, pos) VALUES ('3', 'X', 'Standard Numeric Qualifier', 'STNQ', 'M', '2 N', '12');
INSERT INTO elements (el, format, description, glossary, status, element, pos) VALUES ('4', 'X', 'Date of Issue ', 'DAIS', 'M', '6 N', '14');
INSERT INTO elements (el, format, description, glossary, status, element, pos) VALUES ('5', 'X', 'Transaction Number', 'TRNN', 'M', '6 N', '20');
INSERT INTO elements (el, format, description, glossary, status, element, pos) VALUES ('6', 'X', 'Ticket/Document Number', 'TDNR', 'M', '15 AN', '26');
INSERT INTO elements (el, format, description, glossary, status, element, pos) VALUES ('7', 'X', 'Check-Digit', 'CDGT', 'C', '1 N', '41');
INSERT INTO elements (el, format, description, glossary, status, element, pos) VALUES ('8', 'X', 'Original Issue Information ', 'ORIN', 'C', '32 AN', '42');
INSERT INTO elements (el, format, description, glossary, status, element, pos) VALUES ('9', 'X', 'Endorsements/Restrictions', 'ENRS', 'M', '58 AN', '74');
INSERT INTO elements (el, format, description, glossary, status, element, pos) VALUES ('10', 'N', 'Reserved Space', 'RESD', 'N', '5 AN', '132');
UPDATE elements SET code = 'BKS46' WHERE code is null;


INSERT INTO elements (el, format, description, glossary, status, element, pos) VALUES ('1', 'X', ' Standard Message Identifier', 'SMSG', 'M', ' 3 A', '1');
INSERT INTO elements (el, format, description, glossary, status, element, pos) VALUES ('2', 'X', 'Sequence Number', 'SQNR', 'M', ' 8 N', '4');
INSERT INTO elements (el, format, description, glossary, status, element, pos) VALUES ('3', 'X', 'Standard Numeric Qualifier', 'STNQ', 'M', ' 2 N', '12');
INSERT INTO elements (el, format, description, glossary, status, element, pos) VALUES ('4', 'X', 'Date of Issue', 'DAIS', 'M', ' 6 N', '14');
INSERT INTO elements (el, format, description, glossary, status, element, pos) VALUES ('5', 'X', 'Transaction Number', 'TRNN', 'M', ' 6 N', '20');
INSERT INTO elements (el, format, description, glossary, status, element, pos) VALUES ('6', 'X', 'Ticket/Document Number', 'TDNR', 'M', '15 AN', '26');
INSERT INTO elements (el, format, description, glossary, status, element, pos) VALUES ('7', 'X', 'Check-Digit', 'CDGT', 'M', ' 1 N', '41');
INSERT INTO elements (el, format, description, glossary, status, element, pos) VALUES ('8', 'X', 'Fare', 'FARE', 'M', '11 AN', '42');
INSERT INTO elements (el, format, description, glossary, status, element, pos) VALUES ('9', 'X', 'Ticketing Mode Indicator', 'TKMI', 'M', ' 1 AN', '53');
INSERT INTO elements (el, format, description, glossary, status, element, pos) VALUES ('10', 'X', 'Equivalent Fare Paid', 'EQFR', 'C', '11 AN', '54');
INSERT INTO elements (el, format, description, glossary, status, element, pos) VALUES ('11', 'X', 'Tax', 'TAXA', 'C', '11 AN', '65');
INSERT INTO elements (el, format, description, glossary, status, element, pos) VALUES ('12', 'X', 'Tax', 'TAXA', 'C', '11 AN', '76');
INSERT INTO elements (el, format, description, glossary, status, element, pos) VALUES ('13', 'X', 'Tax', 'TAXA', 'C', '11 AN', '87');
INSERT INTO elements (el, format, description, glossary, status, element, pos) VALUES ('14', 'X', 'Total', 'TOTL', 'M', '11 AN', '98');
INSERT INTO elements (el, format, description, glossary, status, element, pos) VALUES ('15', 'X', 'Neutral Ticketing System Identifier', 'NTSI', 'C', ' 4 AN', '109');
INSERT INTO elements (el, format, description, glossary, status, element, pos) VALUES ('16', 'X', 'Servicing Airline/System Provider Identifier', 'SASI', 'C', ' 4 AN', '113');
INSERT INTO elements (el, format, description, glossary, status, element, pos) VALUES ('17', 'X', 'Fare Calculation Mode Indicator', 'FCMI', 'M', ' 1 AN', '117');
INSERT INTO elements (el, format, description, glossary, status, element, pos) VALUES ('18', 'X', 'Booking Agent Identification', 'BAID', 'C', ' 6 AN', '118');
INSERT INTO elements (el, format, description, glossary, status, element, pos) VALUES ('19', 'X', 'Booking Agency/ Location Number', 'BOON', 'C', '10 AN', '124');
INSERT INTO elements (el, format, description, glossary, status, element, pos) VALUES ('20', 'X', 'Booking Entity Outlet Type', 'BEOT', 'C', ' 1 AN', '134');
INSERT INTO elements (el, format, description, glossary, status, element, pos) VALUES ('21', 'X', 'Fare Calculation Pricing Indicator', 'FCPI', 'M', ' 1 AN', '135');
INSERT INTO elements (el, format, description, glossary, status, element, pos) VALUES ('22', 'N', 'Reserved Space', 'RESD', 'M', ' 1 AN', '136');
UPDATE elements SET code = 'BAR64' WHERE code is null;

INSERT INTO elements (el, format, description, glossary, status, element, pos) VALUES ('1', 'X', 'Standard Message Identifier', 'SMSG', 'M', ' 3 A', '1');
INSERT INTO elements (el, format, description, glossary, status, element, pos) VALUES ('2', 'X', 'Sequence Number', 'SQNR', 'M', ' 8 N', '4');
INSERT INTO elements (el, format, description, glossary, status, element, pos) VALUES ('3', 'X', 'Standard Numeric Qualifier', 'STNQ', 'M', ' 2 N', '12');
INSERT INTO elements (el, format, description, glossary, status, element, pos) VALUES ('4', 'X', 'Date of Issue', 'DAIS', 'M', ' 6 N', '14');
INSERT INTO elements (el, format, description, glossary, status, element, pos) VALUES ('5', 'X', 'Transaction Number', 'TRNN', 'M', ' 6 N', '20');
INSERT INTO elements (el, format, description, glossary, status, element, pos) VALUES ('6', 'X', 'Ticket/Document Number', 'TDNR', 'M', '15 AN', '26');
INSERT INTO elements (el, format, description, glossary, status, element, pos) VALUES ('7', 'X', 'Check-Digit', 'CDGT', 'M', ' 1 N', '41');
INSERT INTO elements (el, format, description, glossary, status, element, pos) VALUES ('8', 'X', 'Passenger Name', 'PXNM', 'M', '49 AN', '42');
INSERT INTO elements (el, format, description, glossary, status, element, pos) VALUES ('9', 'X', 'Passenger Specific Data', 'PXDA', 'C', '46 AN', '91');
UPDATE elements SET code = 'BAR65' WHERE code is null;

INSERT INTO elements (el, format, description, glossary, status, element, pos) VALUES ('1', 'X', 'Standard Message Identifier', 'SMSG', 'M', '3 A', '1');
INSERT INTO elements (el, format, description, glossary, status, element, pos) VALUES ('2', 'X', 'Sequence Number', 'SQNR', 'M', '8 N', '4');
INSERT INTO elements (el, format, description, glossary, status, element, pos) VALUES ('3', 'X', 'Standard Numeric Number', 'STNQ', 'M', '2 N', '12');
INSERT INTO elements (el, format, description, glossary, status, element, pos) VALUES ('4', 'X', 'Date of Issue', 'DAIS', 'M', '6 N', '14');
INSERT INTO elements (el, format, description, glossary, status, element, pos) VALUES ('5', 'X', 'Transaction Number', 'TRNN', 'M', '6 N', '20');
INSERT INTO elements (el, format, description, glossary, status, element, pos) VALUES ('6', 'X', 'Ticket/Document Number', 'TDNR', 'M', '15 AN', '26');
INSERT INTO elements (el, format, description, glossary, status, element, pos) VALUES ('7', 'X', 'Check Digit', 'CDGT', 'M', '1 N', '41');
INSERT INTO elements (el, format, description, glossary, status, element, pos) VALUES ('8', 'X', 'Form Of Payment Sequence Number', 'FPSN', 'M', '1 N', '42');
INSERT INTO elements (el, format, description, glossary, status, element, pos) VALUES ('9', 'X', 'Form Of Payment Information', 'FPIN', 'M', '50 AN', '43');
INSERT INTO elements (el, format, description, glossary, status, element, pos) VALUES ('10', 'N', 'Reserved Space', 'RESD', 'M', '44 AN', '93');
UPDATE elements SET code = 'BAR66' WHERE code is null;

INSERT INTO elements (el, format, description, glossary, status, element, pos) VALUES ('1', 'X', 'Standard Message Identifier', 'SMSG', 'M', ' 3 A', '1');
INSERT INTO elements (el, format, description, glossary, status, element, pos) VALUES ('2', 'X', 'Sequence Number', 'SQNR', 'M', ' 8 N', '4');
INSERT INTO elements (el, format, description, glossary, status, element, pos) VALUES ('3', 'X', 'Standard Numeric Qualifier', 'STNQ', 'M', ' 2 N', '12');
INSERT INTO elements (el, format, description, glossary, status, element, pos) VALUES ('4', 'X', 'Date of Issue', 'DAIS', 'M', ' 6 N', '14');
INSERT INTO elements (el, format, description, glossary, status, element, pos) VALUES ('5', 'X', 'Transaction Number', 'TRNN', 'M', ' 6 N', '20');
INSERT INTO elements (el, format, description, glossary, status, element, pos) VALUES ('6', 'X', 'Ticket/Document Number', 'TDNR', 'M', '15 AN', '26');
INSERT INTO elements (el, format, description, glossary, status, element, pos) VALUES ('7', 'X', 'Check-Digit', 'CDGT', 'M', ' 1 N', '41');
INSERT INTO elements (el, format, description, glossary, status, element, pos) VALUES ('8', 'X', 'Reason for Issuance Description', 'RFID', 'C', '86 AN', '42');
INSERT INTO elements (el, format, description, glossary, status, element, pos) VALUES ('9', 'X', 'Reason for Issuance Code', 'RFIC', 'C', ' 1 AN', '128');
INSERT INTO elements (el, format, description, glossary, status, element, pos) VALUES ('10', 'N', 'Reserved Space', 'RESD', 'M', ' 8 AN', '129');
UPDATE elements SET code = 'BMP70' WHERE code is null;

INSERT INTO elements (el, format, description, glossary, status, element, pos) VALUES ('1', 'X', 'Standard Message Identifier', 'SMSG', 'M', ' 3 A', '1');
INSERT INTO elements (el, format, description, glossary, status, element, pos) VALUES ('2', 'X', 'Sequence Number', 'SQNR', 'M', ' 8 N', '4');
INSERT INTO elements (el, format, description, glossary, status, element, pos) VALUES ('3', 'X', 'Standard Numeric Qualifier', 'STNQ', 'M', ' 2 N', '12');
INSERT INTO elements (el, format, description, glossary, status, element, pos) VALUES ('4', 'X', 'Date of Issue', 'DAIS', 'M', ' 6 N', '14');
INSERT INTO elements (el, format, description, glossary, status, element, pos) VALUES ('5', 'X', 'Transaction Number', 'TRNN', 'M', ' 6 N', '20');
INSERT INTO elements (el, format, description, glossary, status, element, pos) VALUES ('6', 'X', 'Ticket/Document Number', 'TDNR', 'M', '15 AN', '26');
INSERT INTO elements (el, format, description, glossary, status, element, pos) VALUES ('7', 'X', 'Check-Digit', 'CDGT', 'M', ' 1 N', '41');
INSERT INTO elements (el, format, description, glossary, status, element, pos) VALUES ('8', 'X', 'Amount in Letters', 'AMIL', 'C', '72 AN', '42');
INSERT INTO elements (el, format, description, glossary, status, element, pos) VALUES ('9', 'N', 'Reserved Space', 'RESD', 'M', '23 AN', '114');
UPDATE elements SET code = 'BMP72' WHERE code is null;

INSERT INTO elements (el, format, description, glossary, status, element, pos) VALUES ('1', 'X', 'Standard Message Identifier', 'SMSG', 'M', '3 A', '1');
INSERT INTO elements (el, format, description, glossary, status, element, pos) VALUES ('2', 'X', 'Sequence Number', 'SQNR', 'M', '8 N', '4');
INSERT INTO elements (el, format, description, glossary, status, element, pos) VALUES ('3', 'X', 'Standard Numeric Qualifier', 'STNQ', 'M', '2 N', '12');
INSERT INTO elements (el, format, description, glossary, status, element, pos) VALUES ('4', 'X', 'Date of Issue', 'DAIS', 'M', '6 N', '14');
INSERT INTO elements (el, format, description, glossary, status, element, pos) VALUES ('5', 'X', 'Transaction Number', 'TRNN', 'M', '6 N', '20');
INSERT INTO elements (el, format, description, glossary, status, element, pos) VALUES ('6', 'X', 'Ticket/Document Number', 'TDNR', 'M', '15 AN', '26');
INSERT INTO elements (el, format, description, glossary, status, element, pos) VALUES ('7', 'X', 'Check-Digit', 'CDGT', 'M', '1 N', '41');
INSERT INTO elements (el, format, description, glossary, status, element, pos) VALUES ('8', 'X', 'Optional Agency/Airline information', 'OAAI', 'C', '88 AN', '42');
INSERT INTO elements (el, format, description, glossary, status, element, pos) VALUES ('9', 'N', 'Reserved Space', 'RESD', 'M', '7 AN', '130');
UPDATE elements SET code = 'BMP73' WHERE code is null;

INSERT INTO elements (el, format, description, glossary, status, element, pos) VALUES ('1', 'X', 'Standard Message Identifier', 'SMSG', 'M', '  3A', '1');
INSERT INTO elements (el, format, description, glossary, status, element, pos) VALUES ('2', 'X', 'Sequence Number', 'SQNR', 'M', '  8N', '4');
INSERT INTO elements (el, format, description, glossary, status, element, pos) VALUES ('3', 'X', 'Standard Numeric Qualifier', 'STNQ', 'M', '  2N', '12');
INSERT INTO elements (el, format, description, glossary, status, element, pos) VALUES ('4', 'X', 'Date of Issue', 'DAIS', 'M', '  6N', '14');
INSERT INTO elements (el, format, description, glossary, status, element, pos) VALUES ('5', 'X', 'Transaction Number', 'TRNN', 'M', '  6N', '20');
INSERT INTO elements (el, format, description, glossary, status, element, pos) VALUES ('6', 'X', 'Ticket/Document Number', 'TDNR', 'M', '15 AN', '26');
INSERT INTO elements (el, format, description, glossary, status, element, pos) VALUES ('7', 'X', 'Check-Digit', 'CDGT', 'M', '  1N', '41');
INSERT INTO elements (el, format, description, glossary, status, element, pos) VALUES ('8', 'X', 'EMD Coupon Number', 'EMCP', 'M', '  1N', '42');
INSERT INTO elements (el, format, description, glossary, status, element, pos) VALUES ('9', 'X', 'EMD Coupon Value', 'EMCV', 'C', ' 11 N', '43');
INSERT INTO elements (el, format, description, glossary, status, element, pos) VALUES ('10', 'X', 'EMD Coupon Currency', 'CUTP', 'M', '4 AN', '54');
INSERT INTO elements (el, format, description, glossary, status, element, pos) VALUES ('11', 'X', 'EMD Related Ticket Number', 'EMRT', 'C', '15 AN', '58');
INSERT INTO elements (el, format, description, glossary, status, element, pos) VALUES ('12', 'X', 'EMD Related Coupon Number', 'EMRC', 'C', '  1N', '73');
INSERT INTO elements (el, format, description, glossary, status, element, pos) VALUES ('13', 'X', 'EMD Reason for Issuance Sub Code', 'EMSC', 'C', ' 3 AN', '74');
INSERT INTO elements (el, format, description, glossary, status, element, pos) VALUES ('14', 'X', 'EMD Fee Owner Airline Designator', 'EMOC', 'C', '2 AN', '77');
INSERT INTO elements (el, format, description, glossary, status, element, pos) VALUES ('15', 'X', 'EMD Excess Baggage Over Allowance Qualifier', 'XBOA', 'C', ' 1 AN', '79');
INSERT INTO elements (el, format, description, glossary, status, element, pos) VALUES ('16', 'X', 'EMD Excess Baggage Rate Per Unit', 'XBRU', 'C', '12 AN', '80');
INSERT INTO elements (el, format, description, glossary, status, element, pos) VALUES ('17', 'X', 'EMD Excess Baggage Total Number In Excess', 'XBNE', 'C', '12 AN', '92');
INSERT INTO elements (el, format, description, glossary, status, element, pos) VALUES ('18', 'X', 'EMD Consumed at Issuance Indicator', 'EMCI', 'M', '1 AN', '104');
INSERT INTO elements (el, format, description, glossary, status, element, pos) VALUES ('19', 'X', 'EMD Excess Baggage Currency Type', 'XBCT', 'C', '3 A', '105');
INSERT INTO elements (el, format, description, glossary, status, element, pos) VALUES ('20', 'N', 'Reserved Space', 'RESD', 'M', '29 AN', '108');
UPDATE elements SET code = 'BMD75' WHERE code is null;

INSERT INTO elements (el, format, description, glossary, status, element, pos) VALUES ('1', 'X', 'Standard Message Identifier', 'SMSG', 'M', ' 3A', '1');
INSERT INTO elements (el, format, description, glossary, status, element, pos) VALUES ('2', 'X', 'Sequence Number', 'SQNR', 'M', ' 8N', '4');
INSERT INTO elements (el, format, description, glossary, status, element, pos) VALUES ('3', 'X', 'Standard Numeric Qualifier', 'STNQ', 'M', ' 2N', '12');
INSERT INTO elements (el, format, description, glossary, status, element, pos) VALUES ('4', 'X', 'Date of Issue', 'DAIS', 'M', ' 6N', '14');
INSERT INTO elements (el, format, description, glossary, status, element, pos) VALUES ('5', 'X', 'Transaction Number', 'TRNN', 'M', ' 6N', '20');
INSERT INTO elements (el, format, description, glossary, status, element, pos) VALUES ('6', 'X', 'Ticket/Document Number', 'TDNR', 'M', '15 AN', '26');
INSERT INTO elements (el, format, description, glossary, status, element, pos) VALUES ('7', 'X', 'Check-Digit', 'CDGT', 'M', ' 1N', '41');
INSERT INTO elements (el, format, description, glossary, status, element, pos) VALUES ('8', 'X', 'Coupon Number', 'EMCP', 'M', ' 1N', '42');
INSERT INTO elements (el, format, description, glossary, status, element, pos) VALUES ('9', 'X', 'EMD Remarks', 'EMRM', 'M', '70 AN', '43');
INSERT INTO elements (el, format, description, glossary, status, element, pos) VALUES ('10', 'X', 'Reserved Space', 'RESD', 'M', '24 AN', '113');
UPDATE elements SET code = 'BMD76' WHERE code is null;

INSERT INTO elements (el, format, description, glossary, status, element, pos) VALUES ('1', 'X', ' tandard Message Identifier', 'SMSG', 'M', ' 3 A', '1');
INSERT INTO elements (el, format, description, glossary, status, element, pos) VALUES ('2', 'X', 'Sequence Number', 'SQNR', 'M', ' 8 N', '4');
INSERT INTO elements (el, format, description, glossary, status, element, pos) VALUES ('3', 'X', 'Standard Numeric Qualifier', 'STNQ', 'M', ' 2 N', '12');
INSERT INTO elements (el, format, description, glossary, status, element, pos) VALUES ('4', 'X', 'Date of Issue', 'DAIS', 'M', ' 6 N', '14');
INSERT INTO elements (el, format, description, glossary, status, element, pos) VALUES ('5', 'X', 'Transaction Number', 'TRNN', 'M', ' 6 N', '20');
INSERT INTO elements (el, format, description, glossary, status, element, pos) VALUES ('6', 'X', 'Ticket/Document Number', 'TDNR', 'M', '15 AN', '26');
INSERT INTO elements (el, format, description, glossary, status, element, pos) VALUES ('7', 'X', 'Check-Digit', 'CDGT', 'M', ' 1 N', '41');
INSERT INTO elements (el, format, description, glossary, status, element, pos) VALUES ('8', 'N', 'Reserved Space', 'RESD', 'M', ' 1 AN', '42');
INSERT INTO elements (el, format, description, glossary, status, element, pos) VALUES ('9', 'N', 'Coupon Number', 'CPNR', 'M', ' 1 N', '43');
INSERT INTO elements (el, format, description, glossary, status, element, pos) VALUES ('10', 'N', 'Print Line Identifier', 'PLID', 'C', ' 1 AN', '44');
INSERT INTO elements (el, format, description, glossary, status, element, pos) VALUES ('11', 'N', 'Print Line Text', 'PLTX', 'C', '86 AN', '45');
INSERT INTO elements (el, format, description, glossary, status, element, pos) VALUES ('12', 'N', 'Reserved Space', 'RESD', 'M', ' 6 AN', '131');
UPDATE elements SET code = 'BMP77' WHERE code is null;

INSERT INTO elements (el, format, description, glossary, status, element, pos) VALUES ('1', 'X', 'Standard Message Identifier', 'SMSG', 'M', '3 A', '1');
INSERT INTO elements (el, format, description, glossary, status, element, pos) VALUES ('2', 'X', 'Sequence Number', 'SQNR', 'M', '8 N', '4');
INSERT INTO elements (el, format, description, glossary, status, element, pos) VALUES ('3', 'X', 'Standard Numeric Qualifier', 'STNQ', 'M', '2 N', '12');
INSERT INTO elements (el, format, description, glossary, status, element, pos) VALUES ('4', 'X', 'Date of Issue', 'DAIS', 'M', '6 N', '14');
INSERT INTO elements (el, format, description, glossary, status, element, pos) VALUES ('5', 'X', 'Transaction Number', 'TRNN', 'M', '6 N', '20');
INSERT INTO elements (el, format, description, glossary, status, element, pos) VALUES ('6', 'X', 'Ticket/Document Number', 'TDNR', 'M', '15 AN', '26');
INSERT INTO elements (el, format, description, glossary, status, element, pos) VALUES ('7', 'X', 'Check-Digit', 'CDGT', 'M', '1 N', '41');
INSERT INTO elements (el, format, description, glossary, status, element, pos) VALUES ('8', 'X', 'Reserved Space', 'RESD', 'M', '2 AN', '42');
INSERT INTO elements (el, format, description, glossary, status, element, pos) VALUES ('9', 'X', 'Fare Calculation Sequence Number', 'FRCS', 'C', '1 N', '44');
INSERT INTO elements (el, format, description, glossary, status, element, pos) VALUES ('10', 'X', 'Fare Calculation Area', 'FRCA', 'C', '87 AN', '45');
INSERT INTO elements (el, format, description, glossary, status, element, pos) VALUES ('11', 'N', 'Reserved Space', 'RESD', 'M', '5 AN', '132');
UPDATE elements SET code = 'BKF81' WHERE code is null;

INSERT INTO elements (el, format, description, glossary, status, element, pos) VALUES ('1', 'S', 'Standard Message Identifier', 'SMSG', 'M', ' 3 A', '1');
INSERT INTO elements (el, format, description, glossary, status, element, pos) VALUES ('2', 'S', 'Sequence Number', 'SQNR', 'M', ' 8 N', '4');
INSERT INTO elements (el, format, description, glossary, status, element, pos) VALUES ('3', 'S', 'Standard Numeric Qualifier', 'STNQ', 'M', ' 2 N', '12');
INSERT INTO elements (el, format, description, glossary, status, element, pos) VALUES ('4', 'S', 'Date of Issue', 'DAIS', 'M', ' 6 N', '14');
INSERT INTO elements (el, format, description, glossary, status, element, pos) VALUES ('5', 'S', 'Transaction Number', 'TRNN', 'M', ' 6 N', '20');
INSERT INTO elements (el, format, description, glossary, status, element, pos) VALUES ('6', 'S', 'Settlement Authorisation Code', 'ESAC', 'C', '14 AN', '26');
INSERT INTO elements (el, format, description, glossary, status, element, pos) VALUES ('7', 'N', 'Reserved Space', 'RESD', 'M', '97 AN', '40');
UPDATE elements SET code = 'BKP83' WHERE code is null;

INSERT INTO elements (el, format, description, glossary, status, element, pos) VALUES ('1', 's', ' Standard Message Identifier      ', 'SMSG', 'M', '3A', '1');
INSERT INTO elements (el, format, description, glossary, status, element, pos) VALUES ('2', 's', 'Sequence Number', 'SQNR', 'M', '8 N', '4');
INSERT INTO elements (el, format, description, glossary, status, element, pos) VALUES ('3', 's', 'Standard Numeric Qualifier', 'STNQ', 'M', '2 N', '12');
INSERT INTO elements (el, format, description, glossary, status, element, pos) VALUES ('4', 's', 'Date of Issue', 'DAIS', 'M', ' 6 N', '14');
INSERT INTO elements (el, format, description, glossary, status, element, pos) VALUES ('5', 's', 'Transaction Number', 'TRNN', 'M', ' 6 N', '20');
INSERT INTO elements (el, format, description, glossary, status, element, pos) VALUES ('6', 's', 'Ticket/Document Number', 'TDNR', 'M', '15 AN', '26');
INSERT INTO elements (el, format, description, glossary, status, element, pos) VALUES ('7', 's', 'Check-Digit', 'CDGT', 'M', ' 1 N', '41');
INSERT INTO elements (el, format, description, glossary, status, element, pos) VALUES ('8', 's', 'Tax on Commission Type', 'TCTP', 'M', ' 6 AN', '42');
INSERT INTO elements (el, format, description, glossary, status, element, pos) VALUES ('9', 'n', 'Reserved Space', 'RESD', 'M', ' 2 AN', '48');
INSERT INTO elements (el, format, description, glossary, status, element, pos) VALUES ('10', 's', 'Tax on Commission Amount', 'TOCA', 'M', '11 N', '50');
INSERT INTO elements (el, format, description, glossary, status, element, pos) VALUES ('11', 's', ' Tax on Commission Type', 'TCTP', 'C', '6 AN', '61');
INSERT INTO elements (el, format, description, glossary, status, element, pos) VALUES ('12', 'n', 'Reserved Space', 'RESD', 'M', '2 AN', '67');
INSERT INTO elements (el, format, description, glossary, status, element, pos) VALUES ('13', 's', 'Tax on Commission  Amount', 'TOCA', 'C', '11N', '69');
INSERT INTO elements (el, format, description, glossary, status, element, pos) VALUES ('14', 's', 'Tax on Commission Type', 'TCTP', 'C', '6 AN', '80');
INSERT INTO elements (el, format, description, glossary, status, element, pos) VALUES ('15', 'n', 'Reserved Space', 'RESD', 'M', '2 AN', '86');
INSERT INTO elements (el, format, description, glossary, status, element, pos) VALUES ('16', 's', 'Tax on Commission  Amount', 'TOCA', 'C', '11N', '88');
INSERT INTO elements (el, format, description, glossary, status, element, pos) VALUES ('17', 's', 'Tax on Commission Type', 'TCTP', 'C', '6 AN', '99');
INSERT INTO elements (el, format, description, glossary, status, element, pos) VALUES ('18', 'n', 'Reserved Space', 'RESD', 'M', '2 AN', '105');
INSERT INTO elements (el, format, description, glossary, status, element, pos) VALUES ('19', 's', 'Tax on Commission  Amount', 'TOCA', 'C', '11N', '107');
INSERT INTO elements (el, format, description, glossary, status, element, pos) VALUES ('20', 'n', 'Reserved Space', 'RESD', 'M', '12AN', '118');
INSERT INTO elements (el, format, description, glossary, status, element, pos) VALUES ('21', 's', 'Currency Type', 'CUTP', 'M', '4 AN', '130');
INSERT INTO elements (el, format, description, glossary, status, element, pos) VALUES ('22', 'n', 'Reserved Space', 'RESD', 'M', '3 AN', '134');
UPDATE elements SET code = 'BKS42' WHERE code is null;

INSERT INTO elements (el, format, description, glossary, status, element, pos) VALUES ('1', 'S', 'Standard Message Identifier', 'SMSG', 'M', '3A', '1');
INSERT INTO elements (el, format, description, glossary, status, element, pos) VALUES ('2', 'L', 'Sequence Number', 'SQNR', 'M', '8N', '4');
INSERT INTO elements (el, format, description, glossary, status, element, pos) VALUES ('3', 'L', 'Standard Numeric Qualifier     ', 'STNQ', 'M', '2N', '12');
INSERT INTO elements (el, format, description, glossary, status, element, pos) VALUES ('4', 'L', 'Date of Issue ', 'DAIS', 'M', '6N', '14');
INSERT INTO elements (el, format, description, glossary, status, element, pos) VALUES ('5', 'L', 'Transaction Number  ', 'TRNN', 'M', '6N', '20');
INSERT INTO elements (el, format, description, glossary, status, element, pos) VALUES ('6', 'L', 'Ticket/Document Number', 'TDNR', 'M', '15AN', '26');
INSERT INTO elements (el, format, description, glossary, status, element, pos) VALUES ('7', 'L', 'Check-Digit', 'CDGT', 'M', '1N', '41');
INSERT INTO elements (el, format, description, glossary, status, element, pos) VALUES ('8', 'L', 'Segment Identifier', 'SEGI', 'M', '1N', '42');
INSERT INTO elements (el, format, description, glossary, status, element, pos) VALUES ('9', 'L', 'Stopover Code  ', 'STPO', 'M', '1A', '43');
INSERT INTO elements (el, format, description, glossary, status, element, pos) VALUES ('10', 'X', '"Not Valid Before" Date    ', 'NBDA', 'C', '5AN', '44');
INSERT INTO elements (el, format, description, glossary, status, element, pos) VALUES ('11', 'X', '"Not Valid After" Date  ', 'NADA', 'C', '5AN', '49');
INSERT INTO elements (el, format, description, glossary, status, element, pos) VALUES ('12', 'n', 'Reserved Space    ', 'SESD', 'M', '7AN', '54');
INSERT INTO elements (el, format, description, glossary, status, element, pos) VALUES ('13', 'L', 'Origin Airport/ City Code', 'ORAC', 'M', '5A', '61');
INSERT INTO elements (el, format, description, glossary, status, element, pos) VALUES ('14', 'L', ' Destination Airport/ City Code', 'DSTC', 'M', '5A', '66');
INSERT INTO elements (el, format, description, glossary, status, element, pos) VALUES ('15', 'n', 'Carrier', 'CARR', 'C', '4AN', '71');
INSERT INTO elements (el, format, description, glossary, status, element, pos) VALUES ('16', 'n', 'Reserved Space', 'RESD', 'M', '1AN', '75');
INSERT INTO elements (el, format, description, glossary, status, element, pos) VALUES ('17', 'L', 'Flight Number  ', 'FTNR', 'C', '5AN', '76');
INSERT INTO elements (el, format, description, glossary, status, element, pos) VALUES ('18', 'L', 'Reservation Booking Designator ', 'RBKD', 'M', '2AN', '81');
INSERT INTO elements (el, format, description, glossary, status, element, pos) VALUES ('19', 'L', ' Flight Date', 'FTDA', 'C', '5AN', '83');
INSERT INTO elements (el, format, description, glossary, status, element, pos) VALUES ('20', 'n', 'Reserved Space', 'RESD', 'M', '1AN', '88');
INSERT INTO elements (el, format, description, glossary, status, element, pos) VALUES ('21', 'X', 'Flight Departure Time', 'FTDT', 'C', '5AN', '89');
INSERT INTO elements (el, format, description, glossary, status, element, pos) VALUES ('22', 'n', 'Reserved Space', 'RESD', 'M', '3AN', '94');
INSERT INTO elements (el, format, description, glossary, status, element, pos) VALUES ('23', 'X', ' Flight Booking Status', 'FBST', 'C', '2A', '97');
INSERT INTO elements (el, format, description, glossary, status, element, pos) VALUES ('24', 'X', 'Free Baggage Allowance', 'FBAL', 'C', '3AN', '99');
INSERT INTO elements (el, format, description, glossary, status, element, pos) VALUES ('25', 'n', 'Reserved Space', 'RESD', 'M', '1AN', '102');
INSERT INTO elements (el, format, description, glossary, status, element, pos) VALUES ('26', 'L', 'Fare Basis/Ticket Designator', 'FBTD', 'M', '15AN', '103');
INSERT INTO elements (el, format, description, glossary, status, element, pos) VALUES ('27', 'X', ' Frequent Flyer Reference ', 'FFRF', 'C', '16AN', '118');
INSERT INTO elements (el, format, description, glossary, status, element, pos) VALUES ('28', 'n', 'Reserved Space', 'RESD', 'M', '3AN', '134');
UPDATE elements SET code = 'BKI63' WHERE code is null;

INSERT INTO elements (el, format, description, glossary, status, element, pos) VALUES ('1', 'X', 'Standard Message Identifier', 'SMSG', 'M', '3A', '1');
INSERT INTO elements (el, format, description, glossary, status, element, pos) VALUES ('2', 'X', 'Sequence Number', 'SQNR', 'M', '8N', '4');
INSERT INTO elements (el, format, description, glossary, status, element, pos) VALUES ('3', 'X', 'Standard Numeric Qualifier', 'STNQ', 'M', '2N', '12');
INSERT INTO elements (el, format, description, glossary, status, element, pos) VALUES ('4', 'X', 'Date of Issue   ', 'DAIS', 'M', '6N', '14');
INSERT INTO elements (el, format, description, glossary, status, element, pos) VALUES ('5', 'X', 'Transaction Number', 'TRNN', 'M', '6N', '20');
INSERT INTO elements (el, format, description, glossary, status, element, pos) VALUES ('6', 'X', 'Ticket/Document Number ', 'TDNR', 'M', '15AN', '26');
INSERT INTO elements (el, format, description, glossary, status, element, pos) VALUES ('7', 'X', 'Check-Digit  ', 'CDGT', 'M', '1N', '41');
INSERT INTO elements (el, format, description, glossary, status, element, pos) VALUES ('8', 'X', 'Print Line Identifier', 'PLID', 'C', '1N', '42');
INSERT INTO elements (el, format, description, glossary, status, element, pos) VALUES ('9', 'X', 'Print Line Text  ', 'PLTX', 'C', '86AN', '43');
INSERT INTO elements (el, format, description, glossary, status, element, pos) VALUES ('10', 'n', 'Reserved Space ', 'RESD', 'M', '8AN', '129');
UPDATE elements SET code = 'BMP74' WHERE code is null;

INSERT INTO elements (el, format, description, glossary, status, element, pos) VALUES ('1', 'X', 'Standard Message Identifier', 'SMSG', 'M', '3A', '1');
INSERT INTO elements (el, format, description, glossary, status, element, pos) VALUES ('2', 'X', 'Sequence Number', 'SQNR', 'M', '8N', '4');
INSERT INTO elements (el, format, description, glossary, status, element, pos) VALUES ('3', 'X', 'Standard Numeric Qualifier', 'STNQ', 'M', '2N', '12');
INSERT INTO elements (el, format, description, glossary, status, element, pos) VALUES ('4', 'X', 'Date of Issue ', 'DAIS', 'M', '6N', '14');
INSERT INTO elements (el, format, description, glossary, status, element, pos) VALUES ('5', 'X', 'Transaction Number ', 'TRNN', 'M', '6N', '20');
INSERT INTO elements (el, format, description, glossary, status, element, pos) VALUES ('6', 'X', 'Ticket/Document Number ', 'TDNR', 'M', '15AN', '26');
INSERT INTO elements (el, format, description, glossary, status, element, pos) VALUES ('7', 'X', 'Check-Digit  ', 'CDGT', 'M', '1N', '41');
INSERT INTO elements (el, format, description, glossary, status, element, pos) VALUES ('8', 'X', ' Print Line Identifier', 'PLID', 'M', '1AN', '42');
INSERT INTO elements (el, format, description, glossary, status, element, pos) VALUES ('9', 'X', 'Sponsor Information', 'SPIN', 'C', '34AN', '43');
INSERT INTO elements (el, format, description, glossary, status, element, pos) VALUES ('10', 'X', 'Print Line Identifier', 'PLID', 'C', '1AN', '77');
INSERT INTO elements (el, format, description, glossary, status, element, pos) VALUES ('11', 'X', 'Sponsor Information', 'SPIN', 'C', '34AN', '78');
INSERT INTO elements (el, format, description, glossary, status, element, pos) VALUES ('12', 'n', 'Reserved Space         ', 'RESD', 'M', '25AN', '112');
UPDATE elements SET code = 'BMP78' WHERE code is null;

INSERT INTO elements (el, format, description, glossary, status, element, pos) VALUES ('1', 'S', 'Standard Message Identifier', 'SMSG', 'M', ' 3 A', '1');
INSERT INTO elements (el, format, description, glossary, status, element, pos) VALUES ('2', 'S', 'Sequence Number', 'SQNR', 'M', ' 8 N', '4');
INSERT INTO elements (el, format, description, glossary, status, element, pos) VALUES ('3', 'S', 'Standard Numeric Qualifier', 'STNQ', 'M', ' 2 N', '12');
INSERT INTO elements (el, format, description, glossary, status, element, pos) VALUES ('4', 'S', 'Date of Issue', 'DAIS', 'M', ' 6 N', '14');
INSERT INTO elements (el, format, description, glossary, status, element, pos) VALUES ('5', 'S', 'Transaction Number', 'TRNN', 'M', ' 6 N', '20');
INSERT INTO elements (el, format, description, glossary, status, element, pos) VALUES ('6', 'S', 'Form of Payment Type', 'FPTP', 'M', '10 AN', '26');
INSERT INTO elements (el, format, description, glossary, status, element, pos) VALUES ('7', 'S', 'Form of Payment Amount', 'FPAM', 'M', '11 N', '36');
INSERT INTO elements (el, format, description, glossary, status, element, pos) VALUES ('8', 'S', 'Form of Payment Account Number', 'FPAC', 'C', '19 AN', '47');
INSERT INTO elements (el, format, description, glossary, status, element, pos) VALUES ('9', 'S', 'Expiry Date', 'EXDA', 'C', ' 4 AN', '66');
INSERT INTO elements (el, format, description, glossary, status, element, pos) VALUES ('10', 'n', 'Reserved Space', 'RESD', 'M', ' 5 AN', '70');
INSERT INTO elements (el, format, description, glossary, status, element, pos) VALUES ('11', 'S', 'Approval Code', 'APLC', 'C', ' 6 AN', '75');
INSERT INTO elements (el, format, description, glossary, status, element, pos) VALUES ('12', 'S', 'Invoice Number', 'INVN', 'C', '14 AN', '81');
INSERT INTO elements (el, format, description, glossary, status, element, pos) VALUES ('13', 'S', 'Invoice Date', 'INVD', 'C', ' 6 N', '95');
INSERT INTO elements (el, format, description, glossary, status, element, pos) VALUES ('14', 'S', 'Signed for Amount', 'SFAM', 'C', '11 N', '101');
INSERT INTO elements (el, format, description, glossary, status, element, pos) VALUES ('15', 'S', 'Remittance Amount', 'REMT', 'M', '11 N', '112');
INSERT INTO elements (el, format, description, glossary, status, element, pos) VALUES ('16', 'S', 'Currency Type', 'CUTP', 'C', ' 4 AN', '123');
INSERT INTO elements (el, format, description, glossary, status, element, pos) VALUES ('17', 'S', 'Card Verification Value Result', 'CVVR', 'C', ' 1 AN', '127');
INSERT INTO elements (el, format, description, glossary, status, element, pos) VALUES ('18', 'n', 'Reserved Space', 'RESD', 'M', ' 2 AN', '128');
INSERT INTO elements (el, format, description, glossary, status, element, pos) VALUES ('19', 'S', 'Currency Type', 'CUTP', 'M', ' 4 AN', '130');
INSERT INTO elements (el, format, description, glossary, status, element, pos) VALUES ('20', 'n', 'Reserved Space', 'RESD', 'M', ' 3 AN', '134');
UPDATE elements SET code = 'BKP84' WHERE code is null;

INSERT INTO elements (el, format, description, glossary, status, element, pos) VALUES ('1', 'S', 'Standard Message Identifier', 'SMSG', 'M', ' 3 A', '1');
INSERT INTO elements (el, format, description, glossary, status, element, pos) VALUES ('2', 'S', 'Sequence Number', 'SQNR', 'M', ' 8 N', '4');
INSERT INTO elements (el, format, description, glossary, status, element, pos) VALUES ('3', 'S', 'Standard Numeric Qualifier', 'STNQ', 'M', ' 2 N', '12');
INSERT INTO elements (el, format, description, glossary, status, element, pos) VALUES ('4', 'S', 'Agent Numeric Code', 'AGTN', 'M', ' 8 N', '14');
INSERT INTO elements (el, format, description, glossary, status, element, pos) VALUES ('5', 'S', 'Remittance Period Ending Date', 'RMED', 'M', ' 6 N', '22');
INSERT INTO elements (el, format, description, glossary, status, element, pos) VALUES ('6', 'S', 'Reserved Space', 'RESD', 'M', ' 7 AN', '28');
INSERT INTO elements (el, format, description, glossary, status, element, pos) VALUES ('7', 'S', 'Gross Value Amount', 'GROS', 'M', '15 N', '35');
INSERT INTO elements (el, format, description, glossary, status, element, pos) VALUES ('8', 'S', 'Total Remittance Amount', 'TREM', 'M', '15 N', '50');
INSERT INTO elements (el, format, description, glossary, status, element, pos) VALUES ('9', 'S', 'Total Commission Value Amount', 'TCOM', 'M', '15 N', '65');
INSERT INTO elements (el, format, description, glossary, status, element, pos) VALUES ('10', 'S', 'Total Tax/Miscellaneous Fee Amount', 'TTMF', 'M', '15 N', '80');
INSERT INTO elements (el, format, description, glossary, status, element, pos) VALUES ('11', 'S', 'Total Late Reporting Penalty', 'TLRP', 'M', '15 N', '95');
INSERT INTO elements (el, format, description, glossary, status, element, pos) VALUES ('12', 'S', 'Transaction Code', 'TRNC', 'M', ' 4 AN', '110');
INSERT INTO elements (el, format, description, glossary, status, element, pos) VALUES ('13', 'S', 'Reserved Space', 'RESD', 'M', ' 1 AN', '114');
INSERT INTO elements (el, format, description, glossary, status, element, pos) VALUES ('14', 'S', 'Total Tax on Commission Amount', 'TTCA', 'M', '15 N', '115');
INSERT INTO elements (el, format, description, glossary, status, element, pos) VALUES ('15', 'S', 'Currency Type', 'CUTP', 'M', ' 4 AN', '130');
INSERT INTO elements (el, format, description, glossary, status, element, pos) VALUES ('16', 'S', 'Reserved Space', 'RESD', 'M', ' 3 AN', '134');
UPDATE elements SET code = 'BOT93' WHERE code is null;

INSERT INTO elements (el, format, description, glossary, status, element, pos) VALUES ('1', 'S', 'Standard Message Identifier', 'SMSG', 'M', ' 3 A', '1');
INSERT INTO elements (el, format, description, glossary, status, element, pos) VALUES ('2', 'S', 'Sequence Number', 'SQNR', 'M', ' 8 N', '4');
INSERT INTO elements (el, format, description, glossary, status, element, pos) VALUES ('3', 'S', 'Standard Numeric Qualifier', 'STNQ', 'M', ' 2 N', '12');
INSERT INTO elements (el, format, description, glossary, status, element, pos) VALUES ('4', 'S', 'BSP Identifier', 'BSPI', 'M', ' 3 AN', '14');
INSERT INTO elements (el, format, description, glossary, status, element, pos) VALUES ('5', 'S', 'Reserved Space', 'RESD', 'M', ' 7 AN', '17');
INSERT INTO elements (el, format, description, glossary, status, element, pos) VALUES ('6', 'S', 'Office Count', 'OFCC', 'M', ' 5 N', '24');
INSERT INTO elements (el, format, description, glossary, status, element, pos) VALUES ('7', 'S', 'Gross Value Amount', 'GROS', 'M', '15 N', '29');
INSERT INTO elements (el, format, description, glossary, status, element, pos) VALUES ('8', 'S', 'Total Remittance Amount', 'TREM', 'M', '15 N', '44');
INSERT INTO elements (el, format, description, glossary, status, element, pos) VALUES ('9', 'S', 'Total Commission Value Amount', 'TCOM', 'M', '15 N', '59');
INSERT INTO elements (el, format, description, glossary, status, element, pos) VALUES ('10', 'S', 'Total Tax/Miscellaneous Fee Amount', 'TTMF', 'M', '15 N', '74');
INSERT INTO elements (el, format, description, glossary, status, element, pos) VALUES ('11', 'S', 'Total Late Reporting Penalty', 'TLRP', 'M', '15 N', '89');
INSERT INTO elements (el, format, description, glossary, status, element, pos) VALUES ('12', 'S', 'Reserved Space', 'RESD', 'M', '11 AN', '104');
INSERT INTO elements (el, format, description, glossary, status, element, pos) VALUES ('13', 'S', 'Total Tax on Commission Amount', 'TTCA', 'M', '15 N', '115');
INSERT INTO elements (el, format, description, glossary, status, element, pos) VALUES ('14', 'S', 'Currency Type', 'CUTP', 'M', ' 4 AN', '130');
INSERT INTO elements (el, format, description, glossary, status, element, pos) VALUES ('15', 'S', 'Reserved Space', 'RESD', 'M', ' 3 AN', '134');
UPDATE elements SET code = 'BFT99' WHERE code is null;

INSERT INTO elements (el, format, description, glossary, status, element, pos) VALUES ('1', 'S', 'Standard Message Identifier', 'SMSG', 'M', ' 3 A', '1');
INSERT INTO elements (el, format, description, glossary, status, element, pos) VALUES ('2', 'S', 'Sequence Number', 'SQNR', 'M', ' 8 N', '4');
INSERT INTO elements (el, format, description, glossary, status, element, pos) VALUES ('3', 'S', 'Standard Numeric Qualifier', 'STNQ', 'M', ' 2 N', '12');
INSERT INTO elements (el, format, description, glossary, status, element, pos) VALUES ('4', 'S', 'Agent Numeric Code', 'AGTN', 'M', ' 8 N', '14');
INSERT INTO elements (el, format, description, glossary, status, element, pos) VALUES ('5', 'S', 'Remittance Period Ending Date', 'RMED', 'M', ' 6 N', '22');
INSERT INTO elements (el, format, description, glossary, status, element, pos) VALUES ('6', 'S', 'Reserved Space', 'RESD', 'M', ' 7 AN', '28');
INSERT INTO elements (el, format, description, glossary, status, element, pos) VALUES ('7', 'S', 'Gross Value Amount', 'GROS', 'M', '15 N', '35');
INSERT INTO elements (el, format, description, glossary, status, element, pos) VALUES ('8', 'S', 'Total Remittance Amount', 'TREM', 'M', '15 N', '50');
INSERT INTO elements (el, format, description, glossary, status, element, pos) VALUES ('9', 'S', 'Total Commission Value Amount', 'TCOM', 'M', '15 N', '65');
INSERT INTO elements (el, format, description, glossary, status, element, pos) VALUES ('10', 'S', 'Total Tax/Miscellaneous Fee Amount', 'TTMF', 'M', '15 N', '80');
INSERT INTO elements (el, format, description, glossary, status, element, pos) VALUES ('11', 'S', 'Total Late Reporting Penalty', 'TLRP', 'M', '15 N', '95');
INSERT INTO elements (el, format, description, glossary, status, element, pos) VALUES ('12', 'S', 'Reserved Space', 'RESD', 'M', ' 5 AN', '110');
INSERT INTO elements (el, format, description, glossary, status, element, pos) VALUES ('13', 'S', 'Total Tax on Commission Amount', 'TTCA', 'M', '15 N', '115');
INSERT INTO elements (el, format, description, glossary, status, element, pos) VALUES ('14', 'S', 'Currency Type', 'CUTP', 'M', ' 4 AN', '130');
INSERT INTO elements (el, format, description, glossary, status, element, pos) VALUES ('15', 'S', 'Reserved Space', 'RESD', 'M', ' 3 AN', '134');
UPDATE elements SET code = 'BOT94' WHERE code is null;

INSERT INTO elements (el, format, description, glossary, status, element, pos) VALUES ('1', 'S', 'Standard Message Identifier', 'SMSG', 'M', ' 3 A', '1');
INSERT INTO elements (el, format, description, glossary, status, element, pos) VALUES ('2', 'S', 'Sequence Number', 'SQNR', 'M', ' 8 N', '4');
INSERT INTO elements (el, format, description, glossary, status, element, pos) VALUES ('3', 'S', 'Standard Numeric Qualifier', 'STNQ', 'M', ' 2 N', '12');
INSERT INTO elements (el, format, description, glossary, status, element, pos) VALUES ('4', 'S', 'Processing Date Identifier', 'PDAI', 'M', ' 3 AN', '14');
INSERT INTO elements (el, format, description, glossary, status, element, pos) VALUES ('5', 'S', 'Processing Cycle Identifier', 'PCYC', 'M', ' 1 N', '17');
INSERT INTO elements (el, format, description, glossary, status, element, pos) VALUES ('6', 'S', 'Reserved Space', 'RESD', 'M', ' 7 AN', '18');
INSERT INTO elements (el, format, description, glossary, status, element, pos) VALUES ('7', 'S', 'Office Count', 'OFCC', 'M', ' 5 N', '25');
INSERT INTO elements (el, format, description, glossary, status, element, pos) VALUES ('8', 'S', 'Gross Value Amount', 'GROS', 'M', '15 N', '30');
INSERT INTO elements (el, format, description, glossary, status, element, pos) VALUES ('9', 'S', 'Total Remittance Amount', 'TREM', 'M', '15 N', '45');
INSERT INTO elements (el, format, description, glossary, status, element, pos) VALUES ('10', 'S', 'Total Commission Value Amount', 'TCOM', 'M', '15 N', '60');
INSERT INTO elements (el, format, description, glossary, status, element, pos) VALUES ('11', 'S', 'Total Tax/Miscellaneous Fee Amount', 'TTMF', 'M', '15 N', '75');
INSERT INTO elements (el, format, description, glossary, status, element, pos) VALUES ('12', 'S', 'Total Late Reporting Penalty', 'TLRP', 'M', '15 N', '90');
INSERT INTO elements (el, format, description, glossary, status, element, pos) VALUES ('13', 'S', 'Reserved Space', 'RESD', 'M', '10 AN', '105');
INSERT INTO elements (el, format, description, glossary, status, element, pos) VALUES ('14', 'S', 'Total Tax on Commission Amount', 'TTCA', 'M', '15 N', '115');
INSERT INTO elements (el, format, description, glossary, status, element, pos) VALUES ('15', 'S', 'Currency Type', 'CUTP', 'M', ' 4 AN', '130');
INSERT INTO elements (el, format, description, glossary, status, element, pos) VALUES ('16', 'S', 'Reserved Space', 'RESD', 'M', ' 3 AN', '134');
UPDATE elements SET code = 'BCT95' WHERE code is null;

INSERT INTO elements (el, format, description, glossary, status, element, pos) VALUES ('1', 'S', 'Standard Message Identifier', 'SMSG', 'M', ' 3 A', '1');
INSERT INTO elements (el, format, description, glossary, status, element, pos) VALUES ('2', 'S', 'Sequence Number', 'SQNR', 'M', ' 8 N', '4');
INSERT INTO elements (el, format, description, glossary, status, element, pos) VALUES ('3', 'S', 'Standard Numeric Qualifier', 'STNQ', 'M', ' 2 N', '12');
INSERT INTO elements (el, format, description, glossary, status, element, pos) VALUES ('4', 'S', 'Processing Date Identifier', 'PDAI', 'M', ' 3 AN', '14');
INSERT INTO elements (el, format, description, glossary, status, element, pos) VALUES ('5', 'S', 'Processing Cycle Identifier', 'PCYC', 'M', ' 1 N', '17');
INSERT INTO elements (el, format, description, glossary, status, element, pos) VALUES ('6', 'S', 'Reserved Space', 'RESD', 'M', ' 7 AN', '18');
INSERT INTO elements (el, format, description, glossary, status, element, pos) VALUES ('7', 'S', 'Office Count', 'OFCC', 'M', ' 5 N', '25');
INSERT INTO elements (el, format, description, glossary, status, element, pos) VALUES ('8', 'S', 'Gross Value Amount', 'GROS', 'M', '15 N', '30');
INSERT INTO elements (el, format, description, glossary, status, element, pos) VALUES ('9', 'S', 'Total Remittance Amount', 'TREM', 'M', '15 N', '45');
INSERT INTO elements (el, format, description, glossary, status, element, pos) VALUES ('10', 'S', 'Total Commission Value Amount', 'TCOM', 'M', '15 N', '60');
INSERT INTO elements (el, format, description, glossary, status, element, pos) VALUES ('11', 'S', 'Total Tax/Miscellaneous Fee Amount', 'TTMF', 'M', '15 N', '75');
INSERT INTO elements (el, format, description, glossary, status, element, pos) VALUES ('12', 'S', 'Total Late Reporting Penalty', 'TLRP', 'M', '15 N', '90');
INSERT INTO elements (el, format, description, glossary, status, element, pos) VALUES ('13', 'S', 'Reserved Space', 'RESD', 'M', '10 AN', '105');
INSERT INTO elements (el, format, description, glossary, status, element, pos) VALUES ('14', 'S', 'Total Tax on Commission Amount', 'TTCA', 'M', '15 N', '115');
INSERT INTO elements (el, format, description, glossary, status, element, pos) VALUES ('15', 'S', 'Currency Type', 'CUTP', 'M', ' 4 AN', '130');
INSERT INTO elements (el, format, description, glossary, status, element, pos) VALUES ('16', 'S', 'Reserved Space', 'RESD', 'M', ' 3 AN', '134');
UPDATE elements SET code = 'BMP71' WHERE code is null;

UPDATE elements set description = trim(description);


INSERT INTO periods (period_id, start_date, end_date, is_active, details) VALUES (1, '2010-11-01', '2010-12-31', true, NULL);
SELECT pg_catalog.setval('periods_period_id_seq', 1, true);


INSERT INTO rates (rate_id, period_id, rate_name, currency, fare, yr, yq, ke, tu, sd, cd, class, class_code, fare_basis, free_baggage, hand_laguage, excess_baggage, cancellation, one_way, one_way_rate, child_fare, infant_fare, origin, destination, details) VALUES (1, 1, 'KISUMU 1', 'KES', 4500, 3990, 400, 600, 0, 0, 0, 'Economy', 'R', 'RE1M', 20, 5, 50, 1000, false, 0.5, 0.5, 0.1, 'NBO', 'KIS', NULL);
INSERT INTO rates (rate_id, period_id, rate_name, currency, fare, yr, yq, ke, tu, sd, cd, class, class_code, fare_basis, free_baggage, hand_laguage, excess_baggage, cancellation, one_way, one_way_rate, child_fare, infant_fare, origin, destination, details) VALUES (2, 1, 'KISUMU 2', 'KES', 5500, 3990, 400, 600, 0, 0, 0, 'Economy', 'T', 'TE1M', 20, 5, 50, 1000, false, 0.5, 0.5, 0.1, 'NBO', 'KIS', NULL);
INSERT INTO rates (rate_id, period_id, rate_name, currency, fare, yr, yq, ke, tu, sd, cd, class, class_code, fare_basis, free_baggage, hand_laguage, excess_baggage, cancellation, one_way, one_way_rate, child_fare, infant_fare, origin, destination, details) VALUES (3, 1, 'KISUMU 3', 'KES', 6500, 3990, 400, 600, 0, 0, 0, 'Economy', 'V', 'VE1M', 20, 5, 50, 1000, false, 0.5, 0.5, 0.1, 'NBO', 'KIS', NULL);
INSERT INTO rates (rate_id, period_id, rate_name, currency, fare, yr, yq, ke, tu, sd, cd, class, class_code, fare_basis, free_baggage, hand_laguage, excess_baggage, cancellation, one_way, one_way_rate, child_fare, infant_fare, origin, destination, details) VALUES (4, 1, 'KISUMU 4', 'KES', 7000, 3990, 400, 600, 0, 0, 0, 'Economy', 'L', 'LE1M', 20, 5, 50, 1000, false, 0.5, 0.5, 0.1, 'NBO', 'KIS', NULL);
INSERT INTO rates (rate_id, period_id, rate_name, currency, fare, yr, yq, ke, tu, sd, cd, class, class_code, fare_basis, free_baggage, hand_laguage, excess_baggage, cancellation, one_way, one_way_rate, child_fare, infant_fare, origin, destination, details) VALUES (5, 1, 'KISUMU 5', 'KES', 8300, 3990, 400, 600, 0, 0, 0, 'Economy', 'M', 'ME1M', 20, 5, 50, NULL, false, 0.5, 0.5, 0.1, 'NBO', 'KIS', NULL);
INSERT INTO rates (rate_id, period_id, rate_name, currency, fare, yr, yq, ke, tu, sd, cd, class, class_code, fare_basis, free_baggage, hand_laguage, excess_baggage, cancellation, one_way, one_way_rate, child_fare, infant_fare, origin, destination, details) VALUES (6, 1, 'KISUMU 6', 'KES', 10400, 3990, 400, 600, 0, 0, 0, 'Economy', 'S', 'SES2M', 20, 5, 50, 1000, false, 0.5, 0.5, 0.1, 'NBO', 'KIS', NULL);
INSERT INTO rates (rate_id, period_id, rate_name, currency, fare, yr, yq, ke, tu, sd, cd, class, class_code, fare_basis, free_baggage, hand_laguage, excess_baggage, cancellation, one_way, one_way_rate, child_fare, infant_fare, origin, destination, details) VALUES (7, 1, 'KISUMU 7', 'KES', 12500, 3990, 400, 600, 0, 0, 0, 'Economy', 'Y', 'YRT1Y', 20, 5, 50, 1000, false, 0.5, 0.5, 0.1, 'NBO', 'KIS', NULL);
INSERT INTO rates (rate_id, period_id, rate_name, currency, fare, yr, yq, ke, tu, sd, cd, class, class_code, fare_basis, free_baggage, hand_laguage, excess_baggage, cancellation, one_way, one_way_rate, child_fare, infant_fare, origin, destination, details) VALUES (8, 1, 'ELDORET 1', 'KES', 5000, 3990, 400, 600, 0, 0, 0, 'Economy', 'T', 'TE1M', 20, 5, 50, 1000, false, 0.5, 0.5, 0.1, 'NBO', 'EDL', NULL);
INSERT INTO rates (rate_id, period_id, rate_name, currency, fare, yr, yq, ke, tu, sd, cd, class, class_code, fare_basis, free_baggage, hand_laguage, excess_baggage, cancellation, one_way, one_way_rate, child_fare, infant_fare, origin, destination, details) VALUES (9, 1, 'ELDORET 2', 'KES', 6500, 3990, 400, 600, 0, 0, 0, 'Economy', 'L', 'LE1M', 20, 5, 50, 1000, false, 0.5, 0.5, 0.1, 'NBO', 'EDL', NULL);
INSERT INTO rates (rate_id, period_id, rate_name, currency, fare, yr, yq, ke, tu, sd, cd, class, class_code, fare_basis, free_baggage, hand_laguage, excess_baggage, cancellation, one_way, one_way_rate, child_fare, infant_fare, origin, destination, details) VALUES (10, 1, 'ELDORET 3', 'KES', 7500, 3990, 400, 600, 0, 0, 0, 'Economy', 'V', 'VRT1M', 20, 5, 50, 1000, false, 0.5, 0.5, 0.1, 'NBO', 'EDL', NULL);
INSERT INTO rates (rate_id, period_id, rate_name, currency, fare, yr, yq, ke, tu, sd, cd, class, class_code, fare_basis, free_baggage, hand_laguage, excess_baggage, cancellation, one_way, one_way_rate, child_fare, infant_fare, origin, destination, details) VALUES (11, 1, 'ELDORET 4', 'KES', 8500, 3990, 400, 600, 0, 0, 0, 'Economy', 'M', 'ME1M', 20, 5, 50, 1000, false, 0.5, 0.5, 0.1, 'NBO', 'EDL', NULL);
INSERT INTO rates (rate_id, period_id, rate_name, currency, fare, yr, yq, ke, tu, sd, cd, class, class_code, fare_basis, free_baggage, hand_laguage, excess_baggage, cancellation, one_way, one_way_rate, child_fare, infant_fare, origin, destination, details) VALUES (12, 1, 'ELDORET 5', 'KES', 9500, 3990, 400, 600, 0, 0, 0, 'Economy', 'S', 'SEE3M', 20, 5, 50, 1000, false, 0.5, 0.5, 0.1, 'NBO', 'EDL', NULL);
INSERT INTO rates (rate_id, period_id, rate_name, currency, fare, yr, yq, ke, tu, sd, cd, class, class_code, fare_basis, free_baggage, hand_laguage, excess_baggage, cancellation, one_way, one_way_rate, child_fare, infant_fare, origin, destination, details) VALUES (13, 1, 'ELDORET 6', 'KES', 10500, 3990, 400, 600, 0, 0, 0, 'Economy', 'Y', 'YRT1Y', 20, 5, 50, 1000, false, 0.5, 0.5, 0.1, 'NBO', 'EDL', NULL);
INSERT INTO rates (rate_id, period_id, rate_name, currency, fare, yr, yq, ke, tu, sd, cd, class, class_code, fare_basis, free_baggage, hand_laguage, excess_baggage, cancellation, one_way, one_way_rate, child_fare, infant_fare, origin, destination, details) VALUES (15, 1, 'MOMBASA 2', 'KES', 7500, 3990, 400, 600, 0, 0, 0, 'Economy', 'L', 'LE1M', 20, 5, 50, 1000, false, 0.5, 0.5, 0.1, 'NBO', 'MBA', NULL);
INSERT INTO rates (rate_id, period_id, rate_name, currency, fare, yr, yq, ke, tu, sd, cd, class, class_code, fare_basis, free_baggage, hand_laguage, excess_baggage, cancellation, one_way, one_way_rate, child_fare, infant_fare, origin, destination, details) VALUES (29, 1, 'MWANZA 3', 'USD', 280, 50, 20, 20, 30, 0, 0, 'Economy', 'V', 'VE2M', 20, 5, 5, 100, false, 0.5, 0.5, 0.1, 'NBO', 'MWZ', NULL);
INSERT INTO rates (rate_id, period_id, rate_name, currency, fare, yr, yq, ke, tu, sd, cd, class, class_code, fare_basis, free_baggage, hand_laguage, excess_baggage, cancellation, one_way, one_way_rate, child_fare, infant_fare, origin, destination, details) VALUES (14, 1, 'MOMBASA 1', 'KES', 5500, 3990, 400, 600, 0, 0, 0, 'Economy', 'R', 'RE1M', 20, 5, 50, 1000, false, 0.5, 0.5, 0.1, 'NBO', 'MBA', NULL);
INSERT INTO rates (rate_id, period_id, rate_name, currency, fare, yr, yq, ke, tu, sd, cd, class, class_code, fare_basis, free_baggage, hand_laguage, excess_baggage, cancellation, one_way, one_way_rate, child_fare, infant_fare, origin, destination, details) VALUES (16, 1, 'MOMBASA 3', 'KES', 8500, 3990, 400, 600, 0, 0, 0, 'Economy', 'T', 'TE1M', 20, 5, 50, 1000, false, 0.5, 0.5, 0.1, 'NBO', 'MBA', NULL);
INSERT INTO rates (rate_id, period_id, rate_name, currency, fare, yr, yq, ke, tu, sd, cd, class, class_code, fare_basis, free_baggage, hand_laguage, excess_baggage, cancellation, one_way, one_way_rate, child_fare, infant_fare, origin, destination, details) VALUES (17, 1, 'MOMBASA 4', 'KES', 9500, 3990, 400, 600, 0, 0, 0, 'Economy', 'V', 'VE2M', 20, 5, 50, 1000, false, 0.5, 0.5, 0.1, 'NBO', 'MBA', NULL);
INSERT INTO rates (rate_id, period_id, rate_name, currency, fare, yr, yq, ke, tu, sd, cd, class, class_code, fare_basis, free_baggage, hand_laguage, excess_baggage, cancellation, one_way, one_way_rate, child_fare, infant_fare, origin, destination, details) VALUES (18, 1, 'MOMBASA 5', 'KES', 10500, 3990, 400, 600, 0, 0, 0, 'Economy', 'M', 'ME3M', 20, 5, 50, 1000, false, 0.5, 0.5, 0.1, 'NBO', 'MBA', NULL);
INSERT INTO rates (rate_id, period_id, rate_name, currency, fare, yr, yq, ke, tu, sd, cd, class, class_code, fare_basis, free_baggage, hand_laguage, excess_baggage, cancellation, one_way, one_way_rate, child_fare, infant_fare, origin, destination, details) VALUES (19, 1, 'MOMBASA 6', 'KES', 12000, 3990, 400, 600, 0, 0, 0, 'Economy', 'S', 'SES2M', 20, 5, 50, 1000, false, 0.5, 0.5, 0.1, 'NBO', 'MBA', NULL);
INSERT INTO rates (rate_id, period_id, rate_name, currency, fare, yr, yq, ke, tu, sd, cd, class, class_code, fare_basis, free_baggage, hand_laguage, excess_baggage, cancellation, one_way, one_way_rate, child_fare, infant_fare, origin, destination, details) VALUES (20, 1, 'MOMBASA 7', 'KES', 12500, 3990, 400, 600, 0, 0, 0, 'Economy', 'Y', 'YRT1Y', 20, 5, 50, 1000, false, 0.5, 0.5, 0.1, 'NBO', 'MBA', NULL);
INSERT INTO rates (rate_id, period_id, rate_name, currency, fare, yr, yq, ke, tu, sd, cd, class, class_code, fare_basis, free_baggage, hand_laguage, excess_baggage, cancellation, one_way, one_way_rate, child_fare, infant_fare, origin, destination, details) VALUES (30, 1, 'MWANZA 4', 'USD', 330, 50, 20, 20, 30, 0, 0, 'Economy', 'L', 'LE3M', 20, 5, 5, 100, false, 0.5, 0.5, 0.1, 'NBO', 'MWZ', NULL);
INSERT INTO rates (rate_id, period_id, rate_name, currency, fare, yr, yq, ke, tu, sd, cd, class, class_code, fare_basis, free_baggage, hand_laguage, excess_baggage, cancellation, one_way, one_way_rate, child_fare, infant_fare, origin, destination, details) VALUES (31, 1, 'MWANZA 5', 'USD', 380, 50, 20, 20, 30, 0, 0, 'Economy', 'M', 'ME4M', 20, 5, 5, 100, false, 0.5, 0.5, 0.1, 'NBO', 'MWZ', NULL);
INSERT INTO rates (rate_id, period_id, rate_name, currency, fare, yr, yq, ke, tu, sd, cd, class, class_code, fare_basis, free_baggage, hand_laguage, excess_baggage, cancellation, one_way, one_way_rate, child_fare, infant_fare, origin, destination, details) VALUES (33, 1, 'MWANZA 7', 'USD', 480, 50, 20, 20, 30, 0, 0, 'Economy', 'Y', 'YRT1Y', 20, 5, 5, 100, false, 0.5, 0.5, 0.1, 'NBO', 'MWZ', NULL);
INSERT INTO rates (rate_id, period_id, rate_name, currency, fare, yr, yq, ke, tu, sd, cd, class, class_code, fare_basis, free_baggage, hand_laguage, excess_baggage, cancellation, one_way, one_way_rate, child_fare, infant_fare, origin, destination, details) VALUES (27, 1, 'MWANZA 1', 'USD', 200, 50, 20, 20, 30, 0, 0, 'Economy', 'R', 'RE1M', 20, 5, 5, 1000, false, 0.5, 0.5, 0.1, 'NBO', 'MWZ', NULL);
INSERT INTO rates (rate_id, period_id, rate_name, currency, fare, yr, yq, ke, tu, sd, cd, class, class_code, fare_basis, free_baggage, hand_laguage, excess_baggage, cancellation, one_way, one_way_rate, child_fare, infant_fare, origin, destination, details) VALUES (32, 1, 'MWANZA 6', 'USD', 430, 50, 20, 20, 30, 0, 0, 'Economy', 'S', 'SE9M', 20, 5, 5, 100, false, 0.5, 0.5, 0.1, 'NBO', 'MWZ', NULL);
INSERT INTO rates (rate_id, period_id, rate_name, currency, fare, yr, yq, ke, tu, sd, cd, class, class_code, fare_basis, free_baggage, hand_laguage, excess_baggage, cancellation, one_way, one_way_rate, child_fare, infant_fare, origin, destination, details) VALUES (34, 1, 'MWANZA 1', 'USD', 140, 25, 10, 20, 30, 0, 0, 'Economy', 'R', 'RE1M', 20, 5, 5, 100, false, 0.5, 0.5, 0.1, 'KIS', 'MWZ', NULL);
INSERT INTO rates (rate_id, period_id, rate_name, currency, fare, yr, yq, ke, tu, sd, cd, class, class_code, fare_basis, free_baggage, hand_laguage, excess_baggage, cancellation, one_way, one_way_rate, child_fare, infant_fare, origin, destination, details) VALUES (35, 1, 'MWANZA 2', 'USD', 170, 25, 10, 20, 30, 0, 0, 'Economy', 'T', 'TE1M', 20, 5, 5, 100, false, 0.5, 0.5, 0.1, 'KIS', 'MWZ', NULL);
INSERT INTO rates (rate_id, period_id, rate_name, currency, fare, yr, yq, ke, tu, sd, cd, class, class_code, fare_basis, free_baggage, hand_laguage, excess_baggage, cancellation, one_way, one_way_rate, child_fare, infant_fare, origin, destination, details) VALUES (36, 1, 'MWANZA 3', 'USD', 200, 25, 10, 20, 30, 0, 0, 'Economy', 'V', 'VE2M', 20, 5, 5, 100, false, 0.5, 0.5, 0.1, 'KIS', 'MWZ', NULL);
INSERT INTO rates (rate_id, period_id, rate_name, currency, fare, yr, yq, ke, tu, sd, cd, class, class_code, fare_basis, free_baggage, hand_laguage, excess_baggage, cancellation, one_way, one_way_rate, child_fare, infant_fare, origin, destination, details) VALUES (37, 1, 'MWANZA 4', 'USD', 220, 25, 10, 20, 30, 0, 0, 'Economy', 'L', 'LE3M', 20, 5, 5, 100, false, 0.5, 0.5, 0.1, 'KIS', 'MWZ', NULL);
INSERT INTO rates (rate_id, period_id, rate_name, currency, fare, yr, yq, ke, tu, sd, cd, class, class_code, fare_basis, free_baggage, hand_laguage, excess_baggage, cancellation, one_way, one_way_rate, child_fare, infant_fare, origin, destination, details) VALUES (38, 1, 'MWANZA 5', 'USD', 230, 25, 10, 20, 30, 0, 0, 'Economy', 'M', 'ME4M', 20, 5, 5, 100, false, 0.5, 0.5, 0.1, 'KIS', 'MWZ', NULL);
INSERT INTO rates (rate_id, period_id, rate_name, currency, fare, yr, yq, ke, tu, sd, cd, class, class_code, fare_basis, free_baggage, hand_laguage, excess_baggage, cancellation, one_way, one_way_rate, child_fare, infant_fare, origin, destination, details) VALUES (39, 1, 'MWANZA 6', 'USD', 240, 25, 10, 20, 30, 0, 0, 'Economy', 'S', 'SE9M', 20, 5, 5, 100, false, 0.5, 0.5, 0.1, 'KIS', 'MWZ', NULL);
INSERT INTO rates (rate_id, period_id, rate_name, currency, fare, yr, yq, ke, tu, sd, cd, class, class_code, fare_basis, free_baggage, hand_laguage, excess_baggage, cancellation, one_way, one_way_rate, child_fare, infant_fare, origin, destination, details) VALUES (40, 1, 'MWANZA 7', 'USD', 250, 25, 10, 20, 30, 0, 0, 'Y', 'Y', 'YRT1Y', 20, 5, 5, 100, false, 0.5, 0.5, 0.1, 'KIS', 'MWZ', NULL);
INSERT INTO rates (rate_id, period_id, rate_name, currency, fare, yr, yq, ke, tu, sd, cd, class, class_code, fare_basis, free_baggage, hand_laguage, excess_baggage, cancellation, one_way, one_way_rate, child_fare, infant_fare, origin, destination, details) VALUES (21, 1, 'JUBA 1', 'USD', 330, 140, 20, 0, 20, 20, 0, 'Economy', 'R', 'RE1M', 20, 5, 5, 100, false, 0.5, 0.5, 0.1, 'NBO', 'JUB', NULL);
INSERT INTO rates (rate_id, period_id, rate_name, currency, fare, yr, yq, ke, tu, sd, cd, class, class_code, fare_basis, free_baggage, hand_laguage, excess_baggage, cancellation, one_way, one_way_rate, child_fare, infant_fare, origin, destination, details) VALUES (22, 1, 'JUBA 2', 'USD', 200, 70, 10, 0, 20, 20, 0, 'Economy', 'T', 'TEOW1M', 20, 5, 5, 100, true, 0.5, 0.5, 0.1, 'NBO', 'JUB', NULL);
INSERT INTO rates (rate_id, period_id, rate_name, currency, fare, yr, yq, ke, tu, sd, cd, class, class_code, fare_basis, free_baggage, hand_laguage, excess_baggage, cancellation, one_way, one_way_rate, child_fare, infant_fare, origin, destination, details) VALUES (23, 1, 'JUBA 3', 'USD', 490, 140, 20, 0, 20, 20, 0, 'Economy', 'V', 'V1M', 20, 5, 5, 100, false, 0.5, 0.5, 0.1, 'NBO', 'JUB', NULL);
INSERT INTO rates (rate_id, period_id, rate_name, currency, fare, yr, yq, ke, tu, sd, cd, class, class_code, fare_basis, free_baggage, hand_laguage, excess_baggage, cancellation, one_way, one_way_rate, child_fare, infant_fare, origin, destination, details) VALUES (24, 1, 'JUBA 4', 'USD', 575, 140, 20, 0, 20, 20, 0, 'Economy', 'M', 'ME2M', 20, 5, 5, 100, false, 0.5, 0.5, 0.1, 'NBO', 'JUB', NULL);
INSERT INTO rates (rate_id, period_id, rate_name, currency, fare, yr, yq, ke, tu, sd, cd, class, class_code, fare_basis, free_baggage, hand_laguage, excess_baggage, cancellation, one_way, one_way_rate, child_fare, infant_fare, origin, destination, details) VALUES (25, 1, 'JUBA 5', 'USD', 700, 140, 20, 0, 20, 20, 0, 'Economy', 'S', 'SEE3M', 20, 5, 5, 100, false, 0.5, 0.5, 0.1, 'NBO', 'JUB', NULL);
INSERT INTO rates (rate_id, period_id, rate_name, currency, fare, yr, yq, ke, tu, sd, cd, class, class_code, fare_basis, free_baggage, hand_laguage, excess_baggage, cancellation, one_way, one_way_rate, child_fare, infant_fare, origin, destination, details) VALUES (26, 1, 'JUBA 6', 'USD', 900, 140, 20, 0, 20, 20, 0, 'Economy', 'Y', 'YRT1Y', 20, 5, 5, 100, false, 0.5, 0.5, 0.1, 'NBO', 'JUB', NULL);
INSERT INTO rates (rate_id, period_id, rate_name, currency, fare, yr, yq, ke, tu, sd, cd, class, class_code, fare_basis, free_baggage, hand_laguage, excess_baggage, cancellation, one_way, one_way_rate, child_fare, infant_fare, origin, destination, details) VALUES (28, 1, 'MWANZA 2', 'USD', 260, 50, 20, 20, 30, 0, 0, 'Economy', 'T', 'TE1M', 20, 5, 5, 100, false, 0.5, 0.5, 0.1, 'NBO', 'MWZ', NULL);

SELECT pg_catalog.setval('rates_rate_id_seq', 40, true);

