62;"Sayari Afrika ltd "
35;"IMPERIAL AIR SERVICES LTD"
37;"African Tropical Safaris Ltd "
39;"Winglink Travel Limited "
43;"Boma Holidays limited "
24;"BUSHBLAZERS TOURS TRAVEL & SAFARIS LTD "
3;"Bunson Travel Services Limited - CWT"
19;"CATALYST TRAVELS LIMITED"
26;"FLYAIR (INACTIVE -SEE DIRECT SALES)"
21;"Moncal Travel and Tours Ltd "
4;"Travelshoppe Limited"
50;"Debonair Travel"
51;"Didi travel - NBO"
45;"Going Places Limited  "
47;"Gynn International Tours and Travel "
20;"Galileo Kenya Direct Sales"
66;"Longren/Bamboo Hut Safaris "
68;"SUNKIST TRAVEL"
59;"Roeh Tours & Travel Ltd"
70;"Sunkist Travel"
71;"Continental Travel Group"
72;"North and South Travel Ltd"
11;"Antelope Tours & Travel Services Ltd-old"
65;"ANTELOPE TOURS & TRAVEL SERVICES LTD-Old"
77;"The Travel Mart Ltd"
60;"Travel Plaza Ltd"
9;"HRG BON VOYAGE TRAVEL -TANZANIA"
34;"Muthaiga Travel Ltd - ACK  old"
31;"Muthaiga Travel Ltd - Fairview"
58;"Shian Tours & Travel Ltd"
83;"Quest Kenya Agencies"
85;"Travelport Services (Kenya) Ltd "
5;"Uniglobe Fleet Travel (K) Ltd"
94;"Muthaiga Travel Ltd Headoffice "
100;"Charity Gichira"
102;"EXPRESS TRAVEL KOP"
106;"TICKET TO FLY TOURS AND TRAVEL LIMITED"
52;"TRAVEL PLAZA LTD"
108;"Shian Travel - Direct "
6;"Lets Go Travel Limited"
96;"Halifax Tours and Travel"
54;"Roskar Travel Ltd"
81;"Good Hope Travel and Tours Ltd"
101;"Global Business Travel Management "
93;"Georgetown Travel and Tours"
105;"FCM Globe Connect"
104;"FCM Globe Connect"
32;"TRAVELLERS DEN LIMITED"
57;"Travelcare Ltd "
10;"Travel Affairs Limited"
25;"TRAVEL N STYLE LTD"
79;"The Scott Travel Group Ltd."
12;"Silverbird Travel Plus Ltd"
90;"Prima Vera Tours and Safaris"
69;"PALBINA TRAVEL AND TOURS LTD"
15;"NOOR TRAVELS LTD"
18;"MUTHAIGA TRAVEL LIMITED"
78;"MOYO SERENGETI HOLDINGS"
76;"Mighty Tours and Travel"
95;"Experia Travel - Direct "
41;"Elite Travel Services"
64;"Corporate Travel Management "
63;"Longren-Bamboo Hut Safaris"
82;"Travelport  Services (K) Ltd"
88;"Kilindini Travel Ltd"
92;"Georgetown Travel and Tours"
40;"Kearsley Tanzania Ltd"
46;"Incentive Travel"
84;"Globus Tours and Travel"
75;"Daymu Travel and Safaris Ltd."
8;"Express Travel Group"
91;"Elgeyo Travel Limited"
56;"DESIGNER TOURS TRAVEL"
87;"Bonfire Adventures Ltd"
16;"CONNECT TRAVEL LIMITED"
33;"CHRONICLE TOURS AND TRAVEL"
86;"Bridging The World"
7;"BCD TRAVEL HEAD OFFICE"
55;"Antelope Tours and Travel - Head Office"
53;"Karibu Travel & Tours"
14;"AKARIM AGENCIES COMPANY LTD"
13;"FCM Charleston Travel Head office"
17;"BCD TRAVEL UN OFFICE"
103;"Alo Boo Safaris "
80;"African Touch Safaris"
99;"Travelplan Tours and Safaris "
98;"Travelplan Tours and Safaris "
30;"UNIGLOBE SPEEDBIRD TRAVEL AND SAFARIS"
73;"Star Travel and Tours Ltd"
97;"Splash World Limited "
22;"Sagal Travel N Tours Agency"
89;"Onkod travel and Tours agency"
38;"Muthaiga Travel Ltd - Juba "
67;"MAGICAL HOLIDAYS LIMITED"
1;"Uniglobe Acharya Travel Agencies"
